Repository opensearch-project/opensearch-build, pull requests merged in 2021-09, with the labels that each got.

#411 Set the perm to 750 to match with security team original settings
  release/docker/dockerfiles/opensearch.al2.dockerfile
Labels: bug

#418 Opensearch manifest 1.1.0
  manifests/1.1.0/manifest.linux.arm64.1.1.0.yml
  manifests/1.1.0/manifest.linux.x64.1.1.0.yml
Labels: v1.1.0

#436 Add DISABLE parameters for OpenSearch and Dashboards for demo certs and security plugins
  release/docker/README.md
  release/docker/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
  release/docker/config/opensearch/opensearch-docker-entrypoint.sh
  release/docker/dockerfiles/opensearch.al2.dockerfile
  scripts/opensearch-onetime-setup.sh
Labels: bug

#463 Created artifacts are put in the current local directory
  bundle-workflow/src/build.py
  bundle-workflow/src/build_workflow/build_recorder.py
Labels: v1.1.0

#468 [Version] Bump opensearch-1.1.0.yml to new 1.1 branch
  manifests/opensearch-1.1.0.yml
Labels: v1.1.0

#625 Fix the lib location for deploy single cluster script
  scripts/deploy_single_tar_cluster.sh
Labels: bug

#626 Fix another related path in the code of deploy script
  scripts/deploy_single_tar_cluster.sh
Labels: bug

#627 Change Jenkins Docker Runner to CentOS7 so k-NN lib will not crash on OS with lower glibc version
  bundle-workflow/Jenkinsfile
  bundle-workflow/dockerfiles/ci-runner.centos7.dockerfile
Labels: bug, v1.1.0
