Repository opensearch-project/opensearch-build, pull requests merged in 2021-07, with the labels that each got.

#79 Fix trap handling on successful exits
  release/tar/linux/opensearch-dashboards-tar-build.sh
  release/tar/linux/opensearch-tar-build.sh
Labels: bug

#64 Add standard test related scripts to build repo
  lib/shell/file_management.sh
  lib/shell/process_control.sh
  tools/standard-test/README.md
  tools/standard-test/deploy_single_tar_cluster.sh
  tools/standard-test/integtest-runner.al2.dockerfile
  tools/standard-test/integtest_dependencies_opensearch-dashboards.sh
  tools/standard-test/integtest_dependencies_opensearch.sh
  tools/standard-test/nvm_install.sh
Labels: enhancement, integtest

#95 Add JAVA_HOME fixes for the docker opensearch images
  release/docker/dockerfiles/opensearch.al2.dockerfile
Labels: bug

#93 Optimize Docker images size
  release/docker/dockerfiles/opensearch-dashboards.al2.dockerfile
  release/docker/dockerfiles/opensearch.al2.dockerfile
  scripts/opensearch-onetime-setup.sh
Labels: enhancement
