Repository opensearch-project/opensearch-build, pull requests merged in 2021-10, with the labels that each got.

#666 Add snapshot location repo for IM test
  bundle-workflow/src/test_workflow/config/test_manifest.yml
Labels: bug, integtest

#672 Handle PUBLIC_ARTIFACT_URL without trailing slash
  bundle-workflow/src/assemble_workflow/bundle_recorder.py
  bundle-workflow/tests/tests_assemble_workflow/test_bundle_recorder.py
Labels: bug

#478 Add 1.1.0 releasenotes draft md file
  release-notes/opensearch-release-notes-1.1.0.md
Labels: v1.1.0, release

#711 Move docker release to docker folder and legacy script for tar to scripts folder
  docker/release/README.md
  docker/release/build-image-multi-arch.sh
  docker/release/build-image-single-arch.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
  docker/release/config/opensearch-dashboards/opensearch.example.org.cert
  docker/release/config/opensearch-dashboards/opensearch.example.org.key
  docker/release/config/opensearch-dashboards/opensearch_dashboards.yml
  docker/release/config/opensearch/log4j2.properties
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
  docker/release/config/opensearch/opensearch.yml
  docker/release/config/opensearch/performance-analyzer.properties
  docker/release/dockercomposefiles/docker-compose.yml
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
  docker/release/dockerfiles/opensearch.al2.dockerfile
  scripts/legacy/tar/linux/opensearch-dashboards-tar-build.sh
  scripts/legacy/tar/linux/opensearch-tar-build.sh
  scripts/legacy/tar/linux/opensearch-tar-install.sh
Labels: cicd

#717 [Build] Add OpenSearch Dashboards to Jenkinsfile
  jenkins/opensearch-dashboards/Jenkinsfile
  jenkins/opensearch/Jenkinsfile
  src/build_workflow/build_target.py
  tests/tests_build_workflow/test_build_target.py
Labels: opensearch-dashboards
