Repository opensearch-project/opensearch-build, pull requests merged in 2022-01, with the labels that each got.

#1130 Fix issue with docker volume-mounted config file
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
Labels: docker

#1424 [Dashboards][1.2.0] update plugins to use tags
  manifests/1.2.0/opensearch-dashboards-1.2.0.yml
Labels: opensearch-dashboards

#1437 Minor bugfix for signArtifacts.groovy
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  tests/jenkins/TestPrintArtifactDownloadUrlsForStaging.groovy
  tests/jenkins/TestSignArtifacts.groovy
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts.jenkinsfile.txt
  tests/jenkins/jobs/PrintArtifactDownloadUrlsForStaging_Jenkinsfile
  tests/jenkins/jobs/PrintArtifactDownloadUrlsForStaging_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_Jenkinsfile.txt
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile.txt
  vars/printArtifactDownloadUrlsForStaging.groovy
  vars/signArtifacts.groovy
Labels: bug

#1458 Resolve #1130 where sed and tee is trying to access files at the same time
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
Labels: bug, docker, v1.2.4

#1470 Remove Dashboards 1.3.0 version since 2.0.0 will be the next version
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.0/opensearch-dashboards-1.3.0-test.yml
  manifests/1.3.0/opensearch-dashboards-1.3.0.yml
Labels: bug

#1478 Create opensearch-1.2.4-test.yml
  manifests/1.2.4/opensearch-1.2.4-test.yml
Labels: v1.2.4

#1493 updated promote artifacts lib s3 upload
  tests/jenkins/jobs/PromoteArtifacts_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_OpenSearch_Dashboards_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_OpenSearch_Dashboards_Jenkinsfile.txt
  vars/promoteArtifacts.groovy
Labels: bug

#1501 added release notes for 1.2.4
  release-notes/opensearch-release-notes-1.2.4.md
Labels: documentation, v1.2.4

#1524 Disable tests to unblock the pipeline
  tests/jenkins/TestBuildAssembleUpload.groovy
Labels: bug

#1350 [Dashboards] Bumps Node version to 14.18.2 for Dashboards Node upgrade
  DEVELOPER_GUIDE.md
  docker/ci/dockerfiles/ci-runner.al2.dockerfile
  docker/ci/dockerfiles/ci-runner.centos7.dockerfile
Labels: opensearch-dashboards

#1507 Use docker entrypoint instead of command.
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
  docker/release/dockerfiles/opensearch.al2.dockerfile
Labels: docker

#1503 Update to use tags in 1.2.4 input manifests
  manifests/1.2.4/opensearch-1.2.4.yml
Labels: v1.2.4

#1527 Add CI Image for Dashboards Build
  docker/ci/dockerfiles/ci-runner.centos7.opensearch-dashboards.build.dockerfile
  manifests/2.0.0/opensearch-dashboards-2.0.0.yml
Labels: feature

#1562 refactor TestUploadToS3LibTester filename to match convention
  tests/jenkins/TestDataPrepperDistributionArtifacts.groovy
  tests/jenkins/TestSignStandaloneArtifactsJob.groovy
  tests/jenkins/TestUploadToS3.groovy
  tests/jenkins/lib-testers/UploadToS3LibTester.groovy
Labels: bug

#1574 Adding checksum for latest snapshots artifacts
  jenkins/opensearch/distribution-build.jenkinsfile
  tests/jenkins/TestUploadMinSnapshotsToS3.groovy
  tests/jenkins/data/opensearch-1.3.0.yml
  tests/jenkins/data/opensearch-1.3.0.yml.lock
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile.txt
  tests/jenkins/jobs/uploadSnapshotsToS3_Jenkinsfile.txt
  tests/jenkins/lib-testers/UploadMinSnapshotsToS3LibTester.groovy
  vars/uploadMinSnapshotsToS3.groovy
Labels: bug, cicd
