Repository opensearch-project/opensearch-build, pull requests merged in 2022-03, with the labels that each got.

#1676 [RPM M1] Combine two map into one for distribution class/extension
  src/assemble_workflow/bundle_recorder.py
  src/assemble_workflow/dist.py
  src/assemble_workflow/dists.py
  tests/tests_assemble_workflow/test_dists.py
Labels: enhancement, cicd, deb/rpm

#1698 [Dashboards] add test manifest to build checker
  jenkins/check-for-build.jenkinsfile
Labels: opensearch-dashboards

#1699 Add arm64 rpm build for dashboards
  scripts/components/OpenSearch-Dashboards/build.sh
Labels: cicd, deb/rpm

#1667 Update opensearch-dashboards-2.0.0.yml
  manifests/2.0.0/opensearch-dashboards-2.0.0.yml
Labels: v2.0.0, release

#1735 Adding rockylinux8 ci runner to run OSD FT IntegTests
  docker/ci/dockerfiles/build.al2.opensearch.x64.arm64.dockerfile-deprecated
  docker/ci/dockerfiles/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/docker-builder.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
Labels: integtest, cicd

#1774 Update cypress to 9.5.2 for dashboards functional tests
  docker/ci/dockerfiles/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
Labels: cicd, docker

#1726 [RPM M1] Add rpm assemble/bundle code for opensearch using rpmbuild
  scripts/components/OpenSearch-Dashboards/install.sh
  scripts/components/OpenSearch/install.sh
  scripts/pkg/build_templates/opensearch/opensearch.rpm.spec
  scripts/pkg/service_templates/opensearch-dashboards/usr/lib/systemd/system/opensearch-dashboards.service
  scripts/pkg/service_templates/opensearch/etc/sysconfig/opensearch
  scripts/pkg/service_templates/opensearch/usr/lib/systemd/system/opensearch-performance-analyzer.service
  scripts/pkg/service_templates/opensearch/usr/lib/systemd/system/opensearch.service
  src/assemble_workflow/README.md
  src/assemble_workflow/bundle.py
  src/assemble_workflow/bundle_rpm.py
  src/assemble_workflow/dist.py
  src/assemble_workflow/dists.py
  tests/tests_assemble_workflow/data/artifacts/dist/testfolder-1.3.0/opensearch.txt
  tests/tests_assemble_workflow/data/opensearch-build-rpm-1.3.0.yml
  tests/tests_assemble_workflow/test_bundle_opensearch.py
  tests/tests_assemble_workflow/test_bundle_rpm.py
  tests/tests_assemble_workflow/test_dist.py
  tests/tests_assemble_workflow/test_dists.py
Labels: cicd, deb/rpm

#1786 Update release template with feature freeze line
  .github/ISSUE_TEMPLATE/release_template.md
Labels: documentation, release

#1788 Update 2.0.0 opensearch manifest to use jdk17
  manifests/2.0.0/opensearch-2.0.0.yml
Labels: v2.0.0, release

#1793 Fix typo in common-utils build scripts
  scripts/components/common-utils/build.sh
Labels: v2.0.0, release

#1796 Fix common-utils to find maven artifacts with qualifiers
  scripts/components/common-utils/build.sh
Labels: v2.0.0, release

#1804 Opensearch data prepper ci docker images
  docker/ci/dockerfiles/data-prepper.ubuntu2004.x64.dockerfile
Labels: release, docker

#1816 [Tests][Integ] Fix without-security logic if no security plugin
  src/test_workflow/integ_test/service_opensearch.py
  src/test_workflow/integ_test/service_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch_dashboards.py
Labels: bug, ci-test-automation

#1815 Support arm64 rpm generation with dynamic version and any number of plugins
  scripts/pkg/build_templates/opensearch/.opensearch.rpm.spec.swp
  scripts/pkg/build_templates/opensearch/opensearch.rpm.spec
  src/assemble_workflow/bundle.py
  src/assemble_workflow/bundle_rpm.py
  src/assemble_workflow/dist.py
  src/assemble_workflow/dists.py
  src/system/os.py
  tests/tests_assemble_workflow/test_bundle_rpm.py
  tests/tests_assemble_workflow/test_dist.py
  tests/tests_assemble_workflow/test_dists.py
  tests/tests_system/test_os.py
Labels: release, deb/rpm

#1827 Remove small spec swp files added due to mistakes
  scripts/pkg/build_templates/opensearch/.opensearch.rpm.spec.swp
Labels: release, deb/rpm

#1829 Remove alt postfix in rpm assemble
  src/assemble_workflow/bundle_rpm.py
  tests/tests_assemble_workflow/test_bundle_rpm.py
Labels: release, deb/rpm

#1832 Make 2.0.0 trigger checks more often
  jenkins/check-for-build.jenkinsfile
Labels: v2.0.0, release

#1834 Remove other plugins to allow opensearch 2.0.0 snapshot clean push
  manifests/2.0.0/opensearch-2.0.0.yml
Labels: v2.0.0, release

#1835 Adding manifest back on 2.0.0 after #1834
  manifests/2.0.0/opensearch-2.0.0.yml
Labels: v2.0.0, release

#1838 Remove AD&ml-commons; Add qualifier support for opensearch plugins default build.sh
  manifests/2.0.0/opensearch-2.0.0.yml
  scripts/default/opensearch/build.sh
Labels: v2.0.0, release

#1842 Update 2.0.0 manifest to use 2.0 opensearch core branch
  manifests/2.0.0/opensearch-2.0.0.yml
Labels: v2.0.0, release

#1844 Add qualifier support for docker build task
  src/jenkins/InputManifest.groovy
  tests/jenkins/TestBuildDockerImage.groovy
  tests/jenkins/data/opensearch-2.0.0.yml
  tests/jenkins/jobs/BuildDockerImage_Qualifier_Jenkinsfile
  tests/jenkins/jobs/BuildDockerImage_Qualifier_Jenkinsfile_builds_both.txt
  vars/buildDockerImage.groovy
Labels: v2.0.0, release

#1867 Add qualifier support for ci workflows in build repo
  src/ci_workflow/ci_check_gradle_dependencies.py
  src/ci_workflow/ci_check_gradle_properties.py
  src/ci_workflow/ci_check_gradle_publish_to_maven_local.py
  src/ci_workflow/ci_check_npm_package_version.py
  src/ci_workflow/ci_input_manifest.py
  src/ci_workflow/ci_target.py
  tests/tests_ci_workflow/test_ci_check_gradle_dependencies.py
  tests/tests_ci_workflow/test_ci_check_gradle_dependencies_opensearch.py
  tests/tests_ci_workflow/test_ci_check_gradle_properties.py
  tests/tests_ci_workflow/test_ci_check_gradle_properties_version.py
  tests/tests_ci_workflow/test_ci_check_gradle_publish_to_maven_local.py
  tests/tests_ci_workflow/test_ci_check_lists_dist.py
  tests/tests_ci_workflow/test_ci_check_manifest_component.py
  tests/tests_ci_workflow/test_ci_check_npm_package_version.py
  tests/tests_ci_workflow/test_ci_check_package.py
  tests/tests_ci_workflow/test_ci_target.py
Labels: enhancement, v2.0.0, release
