Repository opensearch-project/opensearch-build, pull requests merged in 2022-04, with the labels that each got.

#1878 Add AD and Alerting to the manifest 2.0.0 and remove CU/Alerting build script
  manifests/2.0.0/opensearch-2.0.0.yml
  scripts/components/alerting/build.sh
  scripts/components/common-utils/build.sh
  tests/tests_build_workflow/test_builder_from_source.py
Labels: v2.0.0, release

#1886 [OSD][Tests] add test manifest for 1.3.1
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.1/opensearch-dashboards-1.3.1-test.yml
Labels: ci-test-automation

#1890 [OSD][1.3.1][Integ] add ftr repo
  manifests/1.3.1/opensearch-dashboards-1.3.1.yml
Labels: integtest, opensearch-dashboards

#1891 [OSD][1.3.1] add security plugin
  manifests/1.3.1/opensearch-dashboards-1.3.1.yml
Labels: opensearch-dashboards

#1888 Improve centos7 osd runner to correctly export fpm and allows dynamic node version switch
  docker/ci/config/build-opensearch-dashboards-entrypoint.sh
  docker/ci/dockerfiles/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  manifests/1.3.1/opensearch-dashboards-1.3.1.yml
  manifests/2.0.0/opensearch-dashboards-2.0.0.yml
Labels: v2.0.0, release

#1902 Fixed buildFailureMessage.groovy
  DEVELOPER_GUIDE.md
  vars/buildFailureMessage.groovy
Labels: bug

#1859 Update new docker jobs to make ECR optional
  jenkins/docker-ecr/docker-build-with-ecr.jenkinsfile
  jenkins/docker-ecr/docker-ecr-promote.jenkinsfile
  tests/jenkins/TestDockerBuildWithDockerhubOnlyJob.groovy
  tests/jenkins/TestDockerBuildWithEcrJob.groovy
  tests/jenkins/TestDockerPromoteWithDockerhubOnlyJob.groovy
  tests/jenkins/TestDockerPromoteWithEcrAndDockerhubJob.groovy
  tests/jenkins/TestDockerPromoteWithEcrOnlyJob.groovy
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-build-with-dockerhub-only.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-build-with-ecr-dockerhub.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-build-with-only-ecr.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-ecr-promote-with-ECR-dockerhub.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-ecr-promote-with-ECR-only.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-ecr-promote-with-dockerhub-only.jenkinsfile.txt
Labels: feature

#1929 Add sample component as we continue to move component specific scripts out of build repo
  scripts/components/sample_component/build.sh
  tests/tests_build_workflow/test_builder_from_source.py
Labels: v2.0.0, release

#1927 Remove the custom security build script
  scripts/components/security/build.sh
Labels: v2.0.0

#1932 Added cross-cluster-replication-plugin to 2.0 manifest yml.
  manifests/2.0.0/opensearch-2.0.0.yml
Labels: v2.0.0, release

#1931 add new data.search.usageTelemetry.enabled to opensearch_dashboards_vars
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
Labels: v2.0.0, release

#1940 Add qualifier for PA build.sh and remove RCA one
  scripts/components/performance-analyzer-rca/build.sh
  scripts/components/performance-analyzer/build.sh
Labels: release

#1944 Fix location in bundle manifest and update artifacts upload logic
  jenkins/promotion/tar-promotion.jenkinsfile
  src/jenkins/BuildManifest.groovy
  tests/jenkins/TestPromoteArtifacts.groovy
  tests/jenkins/jobs/ArchiveAssembleUpload_Jenkinsfile.txt
  tests/jenkins/jobs/AssembleUpload_Jenkinsfile.txt
  tests/jenkins/jobs/BuildAssembleUpload_Jenkinsfile.txt
  tests/jenkins/jobs/BuildManifest_Jenkinsfile
  tests/jenkins/jobs/BuildManifest_Jenkinsfile.txt
  tests/jenkins/jobs/BuildManifest_Jenkinsfile_component_no_artifact
  tests/jenkins/jobs/BuildManifest_Jenkinsfile_component_no_artifact.txt
  tests/jenkins/jobs/PromoteArtifacts_Jenkinsfile
  tests/jenkins/jobs/PromoteArtifacts_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_OpenSearch_Dashboards_Jenkinsfile
  tests/jenkins/jobs/PromoteArtifacts_OpenSearch_Dashboards_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_Jenkinsfile
  tests/jenkins/jobs/PromoteArtifacts_actions_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_OpenSearch_Dashboards_Jenkinsfile
  tests/jenkins/jobs/PromoteArtifacts_actions_OpenSearch_Dashboards_Jenkinsfile.txt
  vars/assembleManifest.groovy
  vars/promoteTarArtifacts.groovy
Labels: cicd, deb/rpm

#1942 update release issue with steps to update ansible and helm
  .github/ISSUE_TEMPLATE/release_template.md
Labels: documentation

#1955 install createrepo in docker image for RPM yum repo support
  docker/ci/dockerfiles/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/build.centos7.opensearch.x64.arm64.dockerfile
  manifests/2.0.0/opensearch-2.0.0.yml
  manifests/2.1.0/opensearch-2.1.0.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: cicd, deb/rpm

#1958 Add systemd docker for rpm service test
  docker/ci/dockerfiles/test.centos7.systemd-base.x64.arm64.dockerfile
Labels: cicd, deb/rpm

#1959 Make sure notifications is built correctly while passing ci checks
  manifests/2.0.0/opensearch-2.0.0.yml
  scripts/components/notifications-core/build.sh
  scripts/components/notifications/build.sh
Labels: v2.0.0, release

#1966 Treat dash as dot in rpm assemble
  src/assemble_workflow/bundle_rpm.py
  tests/tests_assemble_workflow/data/opensearch-build-rpm-2.0.0-alpha1.yml
  tests/tests_assemble_workflow/test_bundle_rpm.py
Labels: cicd, deb/rpm

#1969 Fix test manifest 2.0.0 having wrong docker repo
  manifests/2.0.0/opensearch-2.0.0-test.yml
Labels: v2.0.0, release

#1972 Tweak pkg installation msg for opensearch rpm
  scripts/pkg/build_templates/opensearch/opensearch.rpm.spec
Labels: cicd, deb/rpm

#1974 Remove opensearch-env backup as core has fixed the source in rpm
  src/assemble_workflow/bundle_rpm.py
  tests/tests_assemble_workflow/test_bundle_rpm.py
Labels: v2.0.0, release, cicd, deb/rpm

#1976 Add notificationsDashboards scripts
  scripts/components/notificationsDashboards/build.sh
Labels: v2.0.0, release

#1871 [Proposal] Release labels for OpenSearch project releases
  README.md
Labels: community, proposal

#1979 Reduce manifest workflow runtime and separate os/osd runners
  jenkins/check-for-build.jenkinsfile
  manifests/1.2.1/opensearch-dashboards-1.2.1.yml
  manifests/1.2.5/opensearch-1.2.5.yml
  manifests/1.3.2/opensearch-1.3.2.yml
  manifests/1.3.2/opensearch-dashboards-1.3.2.yml
  manifests/1.4.0/opensearch-1.4.0.yml
  src/manifests_workflow/component_opensearch_min.py
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_component_opensearch_min.py
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: enhancement, cicd

#1985 Clean up useless scripts and combine two dashboards yml
  config/opensearch.yml
  config/opensearch_dashboards.yml
  docker/release/build-image-multi-arch.sh
  docker/release/build-image-single-arch.sh
  docker/release/config/opensearch-dashboards/opensearch_dashboards.yml
  manifests/1.0.1/manifest.linux.arm64.1.0.1.yml
  manifests/1.0.1/manifest.linux.x64.1.0.1.yml
  manifests/1.1.0/manifest.linux.arm64.1.1.0.yml
  manifests/1.1.0/manifest.linux.x64.1.1.0.yml
  scripts/components/notebooksDashboards/build.sh
  scripts/legacy/tar/linux/opensearch-dashboards-tar-build.sh
  scripts/legacy/tar/linux/opensearch-tar-build.sh
Labels: enhancement

#1998 [OSD][2.0] bump OSD branch to 2.x
  manifests/2.0.0/opensearch-dashboards-2.0.0.yml
Labels: v2.0.0, opensearch-dashboards

#2007 Correct the RPM artifact link so docker can trigger correctly
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: bug, v2.0.0, release, cicd, docker, jenkins

#1990 Remove BWC test for now as BWC framework does not run correctly as well as rpm integTest as it requires root
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: v2.0.0, release

#2000 Add rpm support in integTest framework (2nd PR)
  src/test_workflow/integ_test/distribution.py
  src/test_workflow/integ_test/distribution_rpm.py
  src/test_workflow/integ_test/distribution_tar.py
  src/test_workflow/integ_test/distributions.py
  src/test_workflow/integ_test/local_test_cluster.py
  src/test_workflow/integ_test/local_test_cluster_opensearch_dashboards.py
  src/test_workflow/integ_test/service.py
  src/test_workflow/integ_test/service_opensearch.py
  src/test_workflow/integ_test/service_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/data/artifacts/dist/opensearch-min-1.3.0-linux-x64.tar.gz
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_tar.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distributions.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_local_test_cluster.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_local_test_cluster_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch_dashboards.py
Labels: enhancement, v2.0.0, integtest, release, cicd, deb/rpm

#2009 Revert #1990 and remove rpm integ/bwc test, and disable tar bwc test for 2.0.0
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  manifests/2.0.0/opensearch-2.0.0-test.yml
Labels: v2.0.0, release

#2013 Remove extra brackets so distribution task running correctly
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: bug, cicd, jenkins

#2015 Resolve docker does not build on dashboards (PR2)
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: bug, v2.0.0, release, cicd, docker

#2017 Add observability BE integTest and remove 2.0.0 builds trigger
  jenkins/check-for-build.jenkinsfile
  manifests/2.0.0/opensearch-2.0.0-test.yml
Labels: v2.0.0, release

#2020 Add uninstall function for tar integTest between plugins
  src/test_workflow/integ_test/distribution.py
  src/test_workflow/integ_test/distribution_tar.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_tar.py
Labels: bug, integtest, cicd

#2021 Add rpm-validation pipelines trigger to opensearch and dashboards distribution builds
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  src/jenkins/BuildManifest.groovy
Labels: cicd, deb/rpm

#2022 Add output rpm validation and descriptions for every build in Jenkins
  jenkins/docker/Jenkinsfile
  jenkins/opensearch-dashboards/bwc-test.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
Labels: enhancement, cicd, jenkins

#2030 Clean up ci-runner dockerfiles & upgrade to nodejs 14.19.1
  docker/ci/config/build-opensearch-dashboards-entrypoint.sh
  docker/ci/config/cypress-setup.sh
  docker/ci/config/jdk-setup.sh
  docker/ci/dockerfiles/build.al2.opensearch.x64.arm64.dockerfile-deprecated
  docker/ci/dockerfiles/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  jenkins/docker/Jenkinsfile
  manifests/1.2.5/opensearch-1.2.5.yml
  manifests/1.3.2/opensearch-1.3.2.yml
  manifests/1.3.2/opensearch-dashboards-1.3.2.yml
  manifests/1.4.0/opensearch-1.4.0.yml
  manifests/2.0.0/opensearch-2.0.0-test.yml
  manifests/2.0.0/opensearch-2.0.0.yml
  manifests/2.0.0/opensearch-dashboards-2.0.0-test.yml
  manifests/2.0.0/opensearch-dashboards-2.0.0.yml
  manifests/2.1.0/opensearch-2.1.0.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: v2.0.0, release, cicd, docker

#2035 [OSD][2.0] use Cypress 5.x test runner
  manifests/2.0.0/opensearch-dashboards-2.0.0-test.yml
Labels: v2.0.0, integtest, opensearch-dashboards

#2036 Add back binding to 0.0.0.0 for the OSD docker images
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
Labels: bug, v2.0.0, release, docker

#2038 Remove hardcode git clone for the jenkins
  jenkins/vulnerability-scan/whitesource-scan.jenkinsfile
  tests/jenkins/jobs/BuildDockerImage_Jenkinsfile_builds_both.txt
  tests/jenkins/jobs/BuildDockerImage_Jenkinsfile_skips_arm64.txt
  tests/jenkins/jobs/BuildDockerImage_Jenkinsfile_skips_both.txt
  tests/jenkins/jobs/BuildDockerImage_Jenkinsfile_skips_x64.txt
  tests/jenkins/jobs/BuildDockerImage_Qualifier_Jenkinsfile_builds_both.txt
  tests/jenkins/jobs/DetectDockerImage_Jenkinsfile.txt
  vars/buildDockerImage.groovy
  vars/detectDockerAgent.groovy
Labels: enhancement, cicd, jenkins

#2042 updated 3.0.0 manifest with JAVA_HOME arguement
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: bug

#2048 Make config folder dynamic using OPENSEARCH_PATH_CONF var
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
  docker/release/dockerfiles/opensearch.al2.dockerfile
  scripts/legacy/tar/linux/opensearch-tar-install.sh
  scripts/opensearch-onetime-setup.sh
  scripts/pkg/build_templates/opensearch/opensearch.rpm.spec
  scripts/pkg/service_templates/opensearch/usr/lib/systemd/system/opensearch-performance-analyzer.service
Labels: bug, v2.0.0, release

#2060 Make sure the build repo is pulled in docker-build stage
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: v2.0.0, release, cicd, jenkins

#2062 Add PA service stop before install and uninstall
  scripts/pkg/build_templates/opensearch/opensearch.rpm.spec
Labels: v2.0.0, release, deb/rpm

#2065 Update 2.0.0 test manifest to use cypress 9.5.4 runner
  manifests/2.0.0/opensearch-dashboards-2.0.0-test.yml
Labels: v2.0.0, release
