Repository opensearch-project/opensearch-build, pull requests merged in 2022-10, with the labels that each got.

#2687 Add remaining plugins and test manifests for 1.3.6 release
  manifests/1.3.6/opensearch-1.3.6-test.yml
  manifests/1.3.6/opensearch-1.3.6.yml
  manifests/1.3.6/opensearch-dashboards-1.3.6-test.yml
  manifests/1.3.6/opensearch-dashboards-1.3.6.yml
Labels: release, v1.3.6

#2694 Remove cron job for 1.3.6
  jenkins/check-for-build.jenkinsfile
Labels: v1.3.6

#2693 Add security to 3.0 manifest
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: v3.0.0

#2678 Resume Windows Build and Add Platform Specific Build Params
  jenkins/opensearch/distribution-build.jenkinsfile
  manifests/1.3.6/opensearch-1.3.6.yml
  manifests/2.3.1/opensearch-2.3.1.yml
  manifests/2.4.0/opensearch-2.4.0.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: enhancement, windows

#2700 Adding 1.0.1 libs to be used by docker-scan
  jenkins/docker/docker-scan.jenkinsfile
  tests/jenkins/TestDockerScanJob.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy-testCopyContainerDockerProdtoEcrProd.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy-testCopyContainerDockerStagingToDockerProd.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy-testCopyContainerDockerStagingToEcrProd.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy-testCopyContainerDockerStagingtoEcrStaging.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy-testCopyContainerECRStagingtoDockerProd.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy-testCopyContainerEcrStagingtoEcrProd.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-scan.jenkinsfile.txt
Labels: bug

#2721 Resolve install demo config access issue and use 1.0.2 lib to fix minUpload for Windows
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
  scripts/components/security/install.sh
Labels: bug

#2731 Slow the 240 build freq as it is breaking groupId due to #2521
  jenkins/check-for-build.jenkinsfile
Labels: release, v2.4.0

#2735 Fix error `InvalidMavenPublicationException`
  .github/ISSUE_TEMPLATE/plugin_onboarding_template.yaml
  scripts/components/notifications-core/build.sh
  scripts/components/notifications/build.sh
Labels: v2.4.0

#2738 Move JS to the correct position in 2.4.0 manifest.
  manifests/2.4.0/opensearch-2.4.0.yml
Labels: release, v2.4.0

#2730 Add windows specific plugin installation for dashboards
  scripts/components/OpenSearch-Dashboards/build.sh
  src/assemble_workflow/bundle_opensearch_dashboards.py
  tests/tests_assemble_workflow/test_bundle_opensearch_dashboards.py
Labels: enhancement, windows

#2756 Add platform selector to both check build and dashboards build
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: enhancement, windows

#2760 Add TestWhiteSourceScan.groov
  tests/jenkins/TestWhiteSourceScan.groovy
  tests/jenkins/jenkinsjob-regression-files/vulnerability-scan/whitesource-scan.jenkinsfile.txt
Labels: technical-debt

#2744 Added use_50_percent_heap configurable parameter for using 50% heap m…
  src/test_workflow/perf_test/perf_multi_node_cluster.py
  src/test_workflow/perf_test/perf_single_node_cluster.py
  src/test_workflow/perf_test/perf_test_cluster_config.py
  tests/tests_test_workflow/test_perf_workflow/perf_test/test_perf_multi_node_cluster.py
  tests/tests_test_workflow/test_perf_workflow/perf_test/test_perf_test_cluster_config.py
Labels: enhancement, performance

#2761 Add windows integTest to OpenSearch Clusters
  src/test_workflow/integ_test/distribution_zip.py
  src/test_workflow/integ_test/distributions.py
  src/test_workflow/integ_test/integ_test_suite.py
  src/test_workflow/integ_test/service_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/data/artifacts/dist/opensearch-min-2.4.0-windows-x64.zip
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch_dashboards.py
Labels: enhancement, integtest, windows

#2767 Add null checker to distribution platform parameter
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: bug, release, jenkins, v2.4.0

#2772 Allow docker build to use tags or commit checkout
  jenkins/docker/docker-build.jenkinsfile
Labels: bug, jenkins

#2765 Add TestReleaseNotesCheck.groovy
  tests/jenkins/TestReleaseNotesCheck.groovy
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
Labels: technical-debt

#2783 Remove additional quotes and bump build freq of 2.4.0 OS
  jenkins/check-for-build.jenkinsfile
Labels: bug

#2788 Add windows specific params for OSD build core
  scripts/components/OpenSearch-Dashboards/build.sh
Labels: enhancement, windows

#2795 New updated lib to resolve jenkins cves 20221024
  build.gradle
Labels: bug, security vulnerability, jenkins

#2790 Adding TestDockerBuild.groovy
  tests/jenkins/TestDockerBuild.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
Labels: technical-debt

#2792 Adding TestDockerCopy.groovy
  tests/jenkins/TestDockerCopy.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy.jenkinsfile.txt
Labels: technical-debt

#2812 Enable knn windows on 2.4.0 and add OSD/reportsDash changes
  manifests/2.4.0/opensearch-2.4.0.yml
  scripts/components/OpenSearch-Dashboards/build.sh
  scripts/components/reportsDashboards/build.sh
Labels: enhancement, windows

#2818 Remove quotes from parameters of windows script
  scripts/startup/zip/windows/opensearch-windows-install.bat
Labels: bug
