Repository opensearch-project/opensearch-build, pull requests merged in 2022-09, with the labels that each got.

#2550 Re-adding the windows snapshot with new changes
  jenkins/opensearch/distribution-build.jenkinsfile
  src/system/temporary_directory.py
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile.txt
  vars/createSha512Checksums.groovy
  vars/uploadMinSnapshotsToS3.groovy
Labels: bug

#2577 Add FTRepo to manifest 2.3
  manifests/2.3.0/opensearch-dashboards-2.3.0.yml
Labels: v2.3.0

#2586 Update OSD repo to 2.3
  manifests/2.3.0/opensearch-dashboards-2.3.0.yml
Labels: v2.3.0

#2610 Add the with security test for reports scheduler/observability
  manifests/2.3.0/opensearch-2.3.0-test.yml
Labels: integtest

#2647 Switching to the correct action name as searching condition for releases.yml
  .github/workflows/releases.yml
Labels: bug

#2659 Add min snapshots information
  README.md
Labels: documentation

#2660 Add jenkins config file and job details for all tests
  src/test_workflow/README.md
Labels: documentation

#2672 Fix zip distribution does not include leading directory
  src/assemble_workflow/dist.py
  tests/tests_assemble_workflow/test_bundle_opensearch.py
Labels: bug, windows
