Repository opensearch-project/opensearch-build, pull requests merged in 2022-02, with the labels that each got.

#1579 Permanent fix for OpenSearch and temp fix for Dashboards startup configurations
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
Labels: bug

#1581 Rename internal filename of sha512 so checksum pass
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile.txt
  vars/uploadMinSnapshotsToS3.groovy
Labels: bug, cicd

#1596 remove 1.2.4 from autobuild
  jenkins/check-for-build.jenkinsfile
Labels: release

#1597 Align sign off with DCO expectation
  .github/workflows/versions.yml
  README.md
Labels: bug

#1598 1.0.0 changelog: mention no breaking changes
  release-notes/opensearch-release-notes-1.0.0.md
Labels: documentation

#1603 BWC test workflow
  ONBOARDING.md
  manifests/2.0.0/opensearch-dashboards-2.0.0-test.yml
  src/run_bwc_test.py
  src/test_workflow/README.md
  src/test_workflow/bwc_test/bwc_test_runner.py
  src/test_workflow/bwc_test/bwc_test_runner_opensearch.py
  src/test_workflow/bwc_test/bwc_test_runner_opensearch_dashboards.py
  src/test_workflow/bwc_test/bwc_test_runners.py
  src/test_workflow/bwc_test/bwc_test_start_properties.py
  src/test_workflow/bwc_test/bwc_test_start_properties_opensearch.py
  src/test_workflow/bwc_test/bwc_test_start_properties_opensearch_dashboards.py
  src/test_workflow/bwc_test/bwc_test_suite.py
  src/test_workflow/bwc_test/bwc_test_suite_opensearch.py
  src/test_workflow/bwc_test/bwc_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/data/build_manifest.yml
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/data/bundle_manifest.yml
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/data/test_manifest.yml
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_suite.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_runner_opensearch.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_runner_opensearch_dashboards.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_runners.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_start_properties_opensearch.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_start_properties_opensearch_dashboards.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_suite_opensearch.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_bwc_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_bwc_workflow/bwc_test/test_run_bwc_test.py
Labels: test

#1605 added support for .crate files in signer for crate.io
  src/sign_workflow/signer.py
  tests/tests_sign_workflow/test_signer.py
Labels: enhancement

#1609 CopyContainer documentation
  jenkins/docker-ecr/docker-build-with-ecr.jenkinsfile
  jenkins/docker-ecr/docker-ecr-promote.jenkinsfile
  tests/jenkins/TestCopyContainerImage.groovy
  tests/jenkins/TestDockerBuildWithEcrJob.groovy
  tests/jenkins/TestDockerPromoteJob.groovy
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-build-with-ecr.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker-ecr/docker-ecr-promote.jenkinsfile.txt
  tests/jenkins/jobs/CopyContainer_docker_Jenkinsfile
  tests/jenkins/jobs/CopyContainer_docker_Jenkinsfile.txt
  tests/jenkins/jobs/CopyDockerImage_docker_Jenkinsfile.txt
  tests/jenkins/lib-testers/CopyContainerLibTester.groovy
  vars/copyContainer.groovy
Labels: documentation

#1629 (Re-open) Update build workflow to build based on distribution (OpenSearch)
  scripts/components/OpenSearch/build.sh
  src/build_workflow/README.md
  src/build_workflow/build_args.py
  src/build_workflow/build_recorder.py
  src/build_workflow/build_target.py
  src/build_workflow/builder_from_source.py
  src/manifests/build_manifest.py
  src/run_build.py
  tests/tests_build_workflow/test_build_args.py
  tests/tests_build_workflow/test_build_recorder.py
  tests/tests_build_workflow/test_build_target.py
  tests/tests_build_workflow/test_builder_from_source.py
  tests/tests_manifests/data/opensearch-build-1.3.0.yml
  tests/tests_manifests/test_build_manifest.py
Labels: cicd, deb/rpm

#1631 Update security to use gradle instead of maven build
  scripts/components/security/build.sh
Labels: bug

#1656 Update dashboards build script to consume distribution
  scripts/components/OpenSearch-Dashboards/build.sh
Labels: enhancement, cicd, deb/rpm

#1652 Add distribution supported components list so only specific scripts can take -d parameter
  src/build_workflow/builder_from_source.py
  tests/tests_build_workflow/test_builder_from_source.py
Labels: cicd, deb/rpm

#1669 Temporarily remove Alerting and Index Management from 1.3.0 manifest
  manifests/1.3.0/opensearch-1.3.0.yml
Labels: bug, v1.3.0

#1658 Add test manifest for OpenSearch Dashboards 1.3.0
  manifests/1.3.0/opensearch-dashboards-1.3.0-test.yml
Labels: ci-test-automation

#1660 Migrate CfUrlRewriter Lambda from JavaScript to TypeScript
  deployment/.gitignore
  deployment/lambdas/cf-url-rewriter/cf-url-rewriter.ts
  deployment/lambdas/cf-url-rewriter/package-lock.json
  deployment/lambdas/cf-url-rewriter/package.json
  deployment/lib/artifacts-public-access.ts
  deployment/package.json
  deployment/test/build-artifact-stack.test.ts
  deployment/test/lambdas/cf-url-rewriter/cf-url-rewriter.test.ts
Labels: ci-test-automation

#1659 [RPM M1] Assemble artifacts based on distribution not file extension
  src/assemble_workflow/bundle.py
  src/assemble_workflow/bundle_recorder.py
  src/assemble_workflow/dist.py
  src/assemble_workflow/dists.py
  src/manifests/build_manifest.py
  src/manifests/bundle_manifest.py
  tests/tests_assemble_workflow/data/artifacts/dist/opensearch-1.3.0/opensearch.txt
  tests/tests_assemble_workflow/data/artifacts/dist/opensearch-dashboards-min-1.3.0-windows-x64.zip
  tests/tests_assemble_workflow/data/artifacts/dist/opensearch-min-1.3.0-linux-x64.tar.gz
  tests/tests_assemble_workflow/data/artifacts/dist/opensearch-min-1.3.0-windows-x64.zip
  tests/tests_assemble_workflow/data/opensearch-build-windows-1.3.0.yml
  tests/tests_assemble_workflow/data/opensearch-dashboards-build-windows-1.3.0.yml
  tests/tests_assemble_workflow/test_bundle.py
  tests/tests_assemble_workflow/test_bundle_opensearch.py
  tests/tests_assemble_workflow/test_bundle_recorder.py
  tests/tests_assemble_workflow/test_dist.py
  tests/tests_assemble_workflow/test_dists.py
  tests/tests_manifests/data/opensearch-bundle-1.3.0.yml
  tests/tests_manifests/test_bundle_manifest.py
Labels: cicd, deb/rpm
