Repository opensearch-project/opensearch-build, pull requests merged in 2022-07, with the labels that each got.

#2298 Switch runner of gradle check to c524xlarge for more stable runs
  jenkins/gradle/gradle-check.jenkinsfile
Labels: enhancement

#2300 Add jdk14 for gradle check 1.x version
  jenkins/gradle/gradle-check.jenkinsfile
Labels: bug, cicd, jenkins

#2315 Add handling of push events on gradle check
  jenkins/gradle/gradle-check.jenkinsfile
Labels: cicd, jenkins

#2353 Make agent label have consistent capital naming (opensearch-build)
  jenkins/check-for-build.jenkinsfile
  jenkins/cross-cluster-replication/perf-test.jenkinsfile
  jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/docker/docker-build.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/opensearch-dashboards/bwc-test.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-ruby/Jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/perf-test.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
  jenkins/promotion/promote-docker-ecr.jenkinsfile
  jenkins/promotion/promote-yum-repos.jenkinsfile
  jenkins/release-tag/release-tag.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/vulnerability-scan/whitesource-scan.jenkinsfile
  tests/jenkins/TestOpenSearchBwcTest.groovy
  tests/jenkins/TestOpenSearchDashboardsBwcTest.groovy
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/cross-cluster-replication/perf-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test-with-security.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDocker.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-tag/release-tag-dashboards.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-tag/release-tag.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
  tests/jenkins/jobs/Build_OpenSearch_Dashboards_Jenkinsfile
  tests/jenkins/jobs/ParallelMessages_Jenkinsfile
  tests/jenkins/jobs/data-prepper/promote-distribution-artifacts.jenkinsfile.txt
  tests/jenkins/lib-testers/RunPerfTestScriptLibTest.groovy
Labels: enhancement

#2365 Use 2.6.0 Ruby and tweak jdk tool naming to be consistent with docker images
  docker/ci/config/jdk-setup.sh
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/gradle/gradle-check.jenkinsfile
Labels: enhancement

#2369 Adds dashboards-maps plugin to meta
  meta/.gitignore
  meta/.meta
Labels: v2.2.0

#2371 Rename ruby jenkinsfile and update runner tag
  jenkins/opensearch-ruby/opensearch-ruby.jenkinsfile
Labels: bug

#2333 Add legacy-manifests folder
  legacy-manifests/1.0.0/opensearch-1.0.0-maven.yml
  legacy-manifests/1.0.0/opensearch-1.0.0-test.yml
  legacy-manifests/1.0.0/opensearch-1.0.0.yml
  legacy-manifests/1.0.1/opensearch-1.0.1-test.yml
  legacy-manifests/1.0.1/opensearch-1.0.1.yml
  legacy-manifests/1.0.1/opensearch-dashboards-1.0.1.yml
  legacy-manifests/1.1.0/opensearch-1.1.0-test.yml
  legacy-manifests/1.1.0/opensearch-1.1.0.yml
  legacy-manifests/1.1.0/opensearch-dashboards-1.1.0-test.yml
  legacy-manifests/1.1.0/opensearch-dashboards-1.1.0.yml
  legacy-manifests/1.1.1/opensearch-1.1.1-test.yml
  legacy-manifests/1.1.1/opensearch-1.1.1.yml
  legacy-manifests/1.1.1/opensearch-dashboards-1.1.1-test.yml
  legacy-manifests/1.1.1/opensearch-dashboards-1.1.1.yml
  legacy-manifests/1.2.0/opensearch-1.2.0-test.yml
  legacy-manifests/1.2.0/opensearch-1.2.0.yml
  legacy-manifests/1.2.0/opensearch-dashboards-1.2.0-test.yml
  legacy-manifests/1.2.0/opensearch-dashboards-1.2.0.yml
  legacy-manifests/1.2.1/opensearch-1.2.1-test.yml
  legacy-manifests/1.2.1/opensearch-1.2.1.yml
  legacy-manifests/1.2.1/opensearch-dashboards-1.2.1.yml
  legacy-manifests/1.2.2/opensearch-1.2.2-test.yml
  legacy-manifests/1.2.2/opensearch-1.2.2.yml
  legacy-manifests/1.2.3/opensearch-1.2.3-test.yml
  legacy-manifests/1.2.3/opensearch-1.2.3.yml
  legacy-manifests/1.2.4/opensearch-1.2.4-test.yml
  legacy-manifests/1.2.4/opensearch-1.2.4.yml
  legacy-manifests/1.2.5/opensearch-1.2.5.yml
  manifests/templates/opensearch-dashboards/1.x/osd-template-1.1.0.yml
  manifests/templates/opensearch/1.x/os-template-1.0.0.yml
  manifests/templates/opensearch/1.x/os-template-1.1.0.yml
  manifests/templates/opensearch/1.x/os-template-1.2.0.yml
  tests/jenkins/jobs/DetectDockerImage_Jenkinsfile
  tests/jenkins/jobs/DetectDockerImage_Jenkinsfile.txt
  tests/jenkins/jobs/InputManifest_Jenkinsfile
  tests/jenkins/jobs/InputManifest_Jenkinsfile.txt
  tests/test_run_build.py
  tests/test_run_checkout.py
  tests/test_run_ci.py
  tests/test_run_manifests.py
  tests/tests_assemble_workflow/test_assemble_args.py
  tests/tests_build_workflow/test_build_args.py
  tests/tests_checkout_workflow/test_checkout_args.py
  tests/tests_ci_workflow/test_ci_args.py
  tests/tests_manifests/test_input_manifest.py
  tests/tests_manifests/test_input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch_dashboards.py
Labels: bug, enhancement

#2381 Switch gradle check to 15 max parallel runs
  .github/ISSUE_TEMPLATE/release_template.md
  jenkins/gradle/gradle-check.jenkinsfile
Labels: cicd, jenkins
