Repository opensearch-project/opensearch-build, pull requests merged in 2022-08, with the labels that each got.

#2390 Add commits.yml generation stage before builds
  docker/ci/dockerfiles/current/yq.alpine3.x64.arm64.dockerfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  tests/jenkins/TestGetRepositoryCommit.groovy
  tests/jenkins/jobs/GetRepositoryCommit_Jenkinsfile
  tests/jenkins/jobs/GetRepositoryCommit_Jenkinsfile.txt
  tests/jenkins/lib-testers/GetRepositoryCommitLibTester.groovy
  vars/getRepositoryCommit.groovy
Labels: enhancement, jenkins

#2382 Add documentation for signing artifacts
  README.md
Labels: documentation

#2408 Boost 2.2.0 build freq and fix commits.yml postclean
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  manifests/2.2.0/opensearch-2.2.0-test.yml
  manifests/2.2.0/opensearch-dashboards-2.2.0-test.yml
Labels: release, v2.2.0

#2417 Add jq/yq/gh to the build docker images
  docker/ci/config/yq-setup.sh
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/yq.alpine3.x64.arm64.dockerfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: enhancement, cicd, docker, jenkins

#2431 Temporary solution to unblock notifications 2.2.0 to publishtomavenlocal / publishzips
  scripts/components/notifications-core/build.sh
  scripts/components/notifications/build.sh
Labels: bug, release, v2.2.0

#2432 Remove 2.2.0 auto cron trigger now
  jenkins/check-for-build.jenkinsfile
Labels: bug

#2436 Add PA 2.2.0.0 version to input manifest
  manifests/2.2.0/opensearch-2.2.0.yml
Labels: release, v2.2.0

#2440 Add docker scan lib and workflow as part of the distribution builds
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  tests/jenkins/TestScanDockerImage.groovy
  tests/jenkins/jobs/BuildDockerImage_Jenkinsfile_builds_both.txt
  tests/jenkins/jobs/BuildDockerImage_Qualifier_Jenkinsfile_builds_both.txt
  tests/jenkins/jobs/ScanDockerImage_Jenkinsfile
  tests/jenkins/jobs/ScanDockerImage_Jenkinsfile.txt
  tests/jenkins/lib-testers/ScanDockerImageLibTester.groovy
  vars/buildDockerImage.groovy
  vars/scanDockerImage.groovy
Labels: enhancement, docker

#2442 Temporary comment out the macos build section snapshots
  manifests/2.2.0/opensearch-2.2.0.yml
Labels: bug

#2443 Update nodejs version to 14.20.0 for 2.2.0
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
Labels: enhancement, cicd, docker

#2445 Add 2.2.0 release notes draft for distribution
  release-notes/opensearch-release-notes-2.2.0.md
Labels: release, v2.2.0

#2450 All 2.2.0 reference change to tag name
  jenkins/check-for-build.jenkinsfile
  manifests/2.2.0/opensearch-2.2.0.yml
  manifests/2.2.0/opensearch-dashboards-2.2.0.yml
Labels: release, v2.2.0

#2475 Remove jq pasing to show correct output in gradle check payload
  scripts/gradle/gradle-check.sh
Labels: bug

#2476 Add special character removal filter to pr title on gradle check
  scripts/gradle/gradle-check.sh
Labels: enhancement

#2479 Add spacing to the gradle check descriptions
  scripts/gradle/gradle-check.sh
Labels: enhancement

#2438 Release Notes tracker for component repos
  Pipfile
  Pipfile.lock
  README.md
  release_notes.sh
  src/git/git_commit.py
  src/git/git_repository.py
  src/release_notes_workflow/README.md
  src/release_notes_workflow/__init__.py
  src/release_notes_workflow/release_notes.py
  src/release_notes_workflow/release_notes_check_args.py
  src/release_notes_workflow/release_notes_component.py
  src/run_releasenotes_check.py
  tests/test_run_releasenotes_check.py
  tests/tests_git/test_git_repository.py
  tests/tests_release_notes_workflow/__init__.py
  tests/tests_release_notes_workflow/test_release_notes.py
  tests/tests_release_notes_workflow/test_release_notes_component.py
  tests/tests_release_notes_workflow/test_releasenotes_check_args.py
Labels: feature

#2483 Add Windows Min Artifacts Building on Jenkins
  jenkins/opensearch/distribution-build.jenkinsfile
  src/system/temporary_directory.py
Labels: enhancement, windows

#2501 Simplify the Jenkins integTest runs with awscli s3
  jenkins/opensearch/integ-test.jenkinsfile
  src/jenkins/BuildManifest.groovy
  src/jenkins/BundleManifest.groovy
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/TestRunIntegTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Jenkinsfile
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_OpenSearch_Dashboards_Jenkinsfile.txt
  tests/jenkins/lib-testers/RunIntegTestScriptLibTest.groovy
  vars/runIntegTestScript.groovy
Labels: bug

#2511 Update release yml workflow to use v3.0.0 of create github issue
  .github/workflows/releases.yml
Labels: bug

#2514 Add curl validation for standalone sign artifact workflows
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
Labels: bug

#2516 Temp block windows to unblock 2.2.1/1.3.5 releases
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: bug

#2515 Add heap dump files if the run failed
  jenkins/gradle/gradle-check.jenkinsfile
Labels: enhancement
