Repository opensearch-project/opensearch-build, pull requests merged in 2023-11, with the labels that each got.

#4189 Add nightly runs using snapshots
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4192 Add benchmark runs with snapshots
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4195 Fix 7.10.2 nightly snapshot base path
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4193 Update docker-re-release jenkins-file to accomodate shared library changes
  jenkins/docker/docker-re-release.jenkinsfile
  tests/jenkins/TestDockerReRelease.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-re-release.jenkinsfile.txt
Labels: all-star-contributor

#4200 Switch default 1000 ci docker image user to ci-runner
  docker/ci/config/windows-servercore-setup.ps1
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: enhancement, cicd, docker, distinguished-contributor

#4204 Remove single-node runs and add log_byte_merge policy runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4205 [Benchmark] Fix log_byte_merge run and add zstd codec runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4206 Fix benchmark jenkinsfile format
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4208 add zstd nightly runs for nyc_taxis and pmc
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4194 Use single line to extract duplicate component names
  src/ci_workflow/ci_manifests.py
  tests/tests_ci_workflow/data/opensearch-1.3.11-with-duplicates.yml
  tests/tests_ci_workflow/test_duplicate_components_in_manifest_file.py
Labels: first-time-contributor

#4211 Fix missing paranthesis in benchmark jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4213 Add cu, js and security plugins to OS manifest
  manifests/2.11.1/opensearch-2.11.1.yml
Labels: all-star-contributor

#4187 Add all components to 2.11.1 OS and OSD manifests
  manifests/2.11.1/opensearch-2.11.1.yml
  manifests/2.11.1/opensearch-dashboards-2.11.1.yml
Labels: all-star-contributor

#4214 Update nightly benchmark runs to use new snapshots
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4215 Minor adjustments in nightly run schedule
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4218 Add test manifests for 2.11.1 and update cron job
  jenkins/check-for-build.jenkinsfile
  manifests/2.11.1/opensearch-2.11.1-test.yml
  manifests/2.11.1/opensearch-dashboards-2.11.0-test.yml
Labels: all-star-contributor

#4219 Lock commits for 2.11.1 OS and OSD
  manifests/2.11.1/opensearch-2.11.1.yml
  manifests/2.11.1/opensearch-dashboards-2.11.1.yml
Labels: all-star-contributor

#4220 Update test manifest typo for 2.11.1 OSD file
  manifests/2.11.1/opensearch-dashboards-2.11.1-test.yml
Labels: all-star-contributor

#4221 [Benchmark] Remove log_byte_size policy runs for 2.12.0
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4222 Update commit id for custom-codecs
  manifests/2.11.1/opensearch-2.11.1.yml
Labels: all-star-contributor

#4226 Add security to 1.3.14 manifest
  manifests/1.3.14/opensearch-1.3.14.yml
Labels: valued-contributor

#4228 Increase timeout for OSD Integtests
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: all-star-contributor

#4229 Onboarded flow-framework plugin to 2.12 manifest
  manifests/2.12.0/opensearch-2.12.0.yml
Labels: seasoned-contributor

#4230 Added ml-commons to 2.12 manifest
  manifests/2.12.0/opensearch-2.12.0.yml
Labels: seasoned-contributor

#4207 Add commits differentiation logic for incremental build
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
  src/build_workflow/build_args.py
  src/build_workflow/build_incremental.py
  src/manifests/input_manifest.py
  src/run_build.py
  tests/tests_build_workflow/data/opensearch-build-tar-2.12.0.yml
  tests/tests_build_workflow/data/opensearch-dashboards-build-tar-2.12.0.yml
  tests/tests_build_workflow/data/opensearch-dashboards-input-2.12.0.yml
  tests/tests_build_workflow/data/opensearch-input-2.12.0.yml
  tests/tests_build_workflow/test_build_incremental.py
  tests/tests_manifests/test_input_manifest.py
Labels: distinguished-contributor

#4198 Automate Updating Github Wikis
  .github/workflows/publish-wiki.yml
  docs/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution.md
  docs/Home.md
Labels: first-time-contributor

#4234 Enable automatic merges only for opensearch-build
  .github/workflows/automatic-merges.yml
Labels: distinguished-contributor

#4239 Move 2.12.0 to use jdk version 21
  manifests/2.12.0/opensearch-2.12.0.yml
Labels: cicd, distinguished-contributor, v2.12.0

#4247 Update commit id's for OS 2.11.1 manifest
  manifests/2.11.1/opensearch-2.11.1.yml
Labels: distinguished-contributor

#4248 Update the final commit id's for OS 2.11
  manifests/2.11.1/opensearch-2.11.1.yml
Labels: distinguished-contributor

#4249 Update commit id's in 2.11.1 OSD input manifest
  manifests/2.11.1/opensearch-dashboards-2.11.1.yml
Labels: distinguished-contributor

#4251 Update OS commit id in 2.11.1 manifest
  manifests/2.11.1/opensearch-2.11.1.yml
Labels: distinguished-contributor

#4252 Add essential components to 1.3.14 manifest
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  manifests/1.3.14/opensearch-1.3.14.yml
Labels: distinguished-contributor

#4237 Add consolidated release notes for 2.11.1
  release-notes/opensearch-release-notes-2.11.1.md
Labels: distinguished-contributor
