Repository opensearch-project/opensearch-build, pull requests merged in 2023-09, with the labels that each got.

#3953 Tune nyc taxi & http logs workload params for remote store nightly runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: first-time-contributor

#3957 Removed hybrid search feature flag for test clusters
  manifests/2.10.0/opensearch-2.10.0-concurrent-search-test.yml
  manifests/2.10.0/opensearch-2.10.0-test.yml
Labels: repeat-contributor

#3958 Switch the benchmark agent back to m52xlarge due to network overload
  jenkins/opensearch/benchmark-test.jenkinsfile
Labels: cicd, performance, jenkins, distinguished-contributor

#3951 Use windows home dir as temp dir location
  src/system/temporary_directory.py
  tests/tests_system/test_temporary_directory.py
Labels: bug, enhancement, release, windows, jenkins, distributions, distinguished-contributor, v2.10.0

#3937 Add Jenkins job for Docker Patch jenkins shared library
  jenkins/docker/docker-re-release.jenkinsfile
  tests/jenkins/TestDockerReRelease.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-re-release.jenkinsfile.txt
Labels: all-star-contributor

#3960 Adding docker ci images getter scripts
  docker/ci/get-ci-images.sh
Labels: cicd, docker, distinguished-contributor

#3965 Add prefix of registry and repo name to get-ci-images.sh output
  docker/ci/get-ci-images.sh
Labels: enhancement, cicd, docker, distinguished-contributor

#3968 Switch core to 2.10 branch
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: distinguished-contributor

#3973 Start remote store nightly runs for 3.x version with minor tunings
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: first-time-contributor

#3967 [NodeJS18 Upgrade] Switch to AL2023 Runner and Rockylinux8 for NodeJS18 Upgrade
  jenkins/check-for-build.jenkinsfile
  jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/legacy/TestRunNonSecurityPerfTestScript.groovy.legacy
  jenkins/manifests-update.jenkinsFile
  jenkins/opensearch-dashboards/bwc-test.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
  jenkins/promotion/promote-docker-ecr.jenkinsfile
  jenkins/promotion/promote-repos.jenkinsfile
  jenkins/release-notes-check/release-notes-check.jenkinsfile
  jenkins/release-tag/release-tag.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  jenkins/vulnerability-scan/whitesource-scan.jenkinsfile
  manifests/2.10.0/opensearch-2.10.0-concurrent-search-test.yml
  manifests/2.10.0/opensearch-2.10.0-test.yml
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  manifests/templates/opensearch-dashboards/2.x/manifest.yml
  manifests/templates/opensearch-dashboards/3.x/manifest.yml
  manifests/templates/opensearch-dashboards/default/manifest.yml
  manifests/templates/opensearch/2.x/manifest.yml
  manifests/templates/opensearch/3.x/manifest.yml
  manifests/templates/opensearch/default/manifest.yml
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDocker.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/vulnerability-scan/whitesource-scan.jenkinsfile.txt
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: enhancement, release, cicd, docker, jenkins, distributions, distinguished-contributor, v2.10.0, nodejs upgrade

#3976 [Windows Container] Switch Windows Runner from Agents to Docker Container on Jenkins Distribution Build
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: enhancement, release, cicd, docker, windows, jenkins, distributions, Build Libraries & Interfaces, distinguished-contributor, v2.10.0

#3970 Update opensearch-2.10.0.yml for PA
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: repeat-contributor

#3977 Switch references to 2.10 branch
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
Labels: distinguished-contributor

#3981 Build 3.0.0 every 6 hours
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#3984 Remove cronjob for 2.10.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#3985 Remove additional configs from remote store nightly run commands as GA
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: repeat-contributor

#3975 Start remote store so workload nightly runs for 2.x and 3.x version
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: repeat-contributor

#3987 Add custom codecs plugin to 2.10.0 manifest
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: release, on-boarding, distinguished-contributor, v2.10.0

#3989 Treat release notes table branch name as string by adding bracket
  src/release_notes_workflow/release_notes.py
  tests/tests_release_notes_workflow/test_release_notes.py
Labels: bug, release, cicd, jenkins, Build Libraries & Interfaces, distinguished-contributor, v2.10.0

#3990 Add JS and CU components to 1.3.13 input manifest
  manifests/1.3.13/opensearch-1.3.13.yml
Labels: distinguished-contributor

#3983 Add more instructions of test report manifest to README
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  src/report_workflow/README.md
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
Labels: distinguished-contributor

#3994 Update cron for maven snapshot publish and add two plugins
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  manifests/1.3.13/opensearch-1.3.13.yml
Labels: distinguished-contributor

#3996 Lock commits for 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
Labels: distinguished-contributor

#3995 Run integration tests periodically for 2.10.0
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4001 Increase cron to run tests every 3 hours and fix dasboards URL
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3997 Make sure dnf always install latest patches when building docker release images
  docker/release/README.md
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
  docker/release/dockerfiles/opensearch-dashboards.al2023.dockerfile
  docker/release/dockerfiles/opensearch.al2.dockerfile
  docker/release/dockerfiles/opensearch.al2023.dockerfile
Labels: enhancement, release, cicd, docker, distributions, distinguished-contributor, v2.10.0

#4003 Fix the component issue creation workflow bug
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#4004 Fix the component issue creation workflow
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#3982 Remove instructions of updating the release branch
  .github/ISSUE_TEMPLATE/component_release_template.md
Labels: distinguished-contributor

#4002 Switch OpenSearch Build Image Back to CentOS7
  manifests/2.10.0/opensearch-2.10.0-concurrent-search-test.yml
  manifests/2.10.0/opensearch-2.10.0-test.yml
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/templates/opensearch/2.x/manifest.yml
  manifests/templates/opensearch/3.x/manifest.yml
  manifests/templates/opensearch/default/manifest.yml
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: release, cicd, docker, jenkins, distributions, distinguished-contributor, v2.10.0, nodejs upgrade

#4006 Update commits for second RC for 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: distinguished-contributor

#4007 Update sql dummy master key for testing
  manifests/2.10.0/opensearch-2.10.0-concurrent-search-test.yml
Labels: valued-contributor

#4008 Fix the component issue creation workflow
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#4010 Add custom-codecs integration tests into test manifiest
  manifests/2.10.0/opensearch-2.10.0-test.yml
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
Labels: valued-contributor

#4012 Add tests for maven publishing release workflow
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor

#4014 Update commits for third RC of 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: distinguished-contributor

#4011 Add remaining components to 1.3.13 input manifest
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.13/opensearch-1.3.13-test.yml
  manifests/1.3.13/opensearch-1.3.13.yml
  manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml
  manifests/1.3.13/opensearch-dashboards-1.3.13.yml
Labels: distinguished-contributor

#3823 Uninstall OpenSearch after testing on dashboards and modify the exception handle to skip irrelevant exception
  src/system/process.py
  src/test_workflow/test_cluster.py
  tests/tests_system/test_process.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_local_test_cluster_opensearch_dashboards.py
Labels: distinguished-contributor

#4017 Fix custom-codecs with security integration tests
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: valued-contributor

#4020 Fix the test manifest paths in cron
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4021 Remove remote-store runs fro nyc_taxis and so
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4022 Remove segment replication stat capture from remote-store runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4023 Make sure WindowsZip/LinuxTar remove correct dir when uninstall
  src/test_workflow/integ_test/distribution_tar.py
  src/test_workflow/integ_test/distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_tar.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
Labels: bug, integtest, release, cicd, windows, distinguished-contributor, v2.10.0

#4025 Update commits for 4th RC for 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
Labels: distinguished-contributor

#4026 Fix custom-codecs withy integration tests flipping
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: seasoned-contributor

#4028 Remove jenkins cron job for 1.3.13 distribution build
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4027 [Windows Container] Add Windows IntegTest support to Jenkins with Windows Docker Container
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: integtest, release, cicd, docker, windows, jenkins, distinguished-contributor, v2.10.0

#4029 Update commit for 5th RC for 2.10.0
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
Labels: distinguished-contributor

#4030 Remote node-stat from renote-store runs and spread the concurrent jobs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4034 Freeze commit ID after generating RC for 1.3.13
  manifests/1.3.13/opensearch-1.3.13.yml
  manifests/1.3.13/opensearch-dashboards-1.3.13.yml
Labels: distinguished-contributor

#4033 Add security plugin to 2.11 manifest
  manifests/2.11.0/opensearch-2.11.0.yml
Labels: distinguished-contributor

#4035 Update commits for 6th RC for 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: distinguished-contributor

#4037 Provision integTest container with resource locking
  jenkins/opensearch/integ-test.jenkinsfile
Labels: integtest, release, cicd, docker, jenkins, distributions, distinguished-contributor, v2.10.0

#4038 Allow opensearch-dashboard user to read its config
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
Labels: bug, release, rpm, distributions, deb, repeat-contributor, v2.10.0

#4039 Make all integTest having resource locking
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: enhancement, integtest, release, cicd, docker, jenkins, distributions, distinguished-contributor, v2.10.0

#4040 Reset resource locking which causes some integTest to error out
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: integtest, release, cicd, docker, jenkins, distinguished-contributor, v2.10.0

#4041 Reset deb rpm permissions to original state
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/opensearch-dashboards/deb/debmake_opensearch_dashboards_install.sh
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/opensearch/deb/debmake_opensearch_install.sh
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: distinguished-contributor

#4044 Remove OSD component from test manifest on 1.3.x
  manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml
Labels: distinguished-contributor

#4045 Update commits for 7th RC for 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
Labels: distinguished-contributor

#4048 Disable multi cluster integtest for CCR
  manifests/2.10.0/opensearch-2.10.0-test.yml
Labels: repeat-contributor

#4049 Disable multi cluster integtest for CCR
  manifests/2.10.0/opensearch-2.10.0-concurrent-search-test.yml
Labels: valued-contributor

#4046 Fix no logs on OS process failure issue
  src/test_workflow/integ_test/service.py
  src/test_workflow/test_cluster.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_local_test_cluster.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch.py
Labels: distinguished-contributor

#4050 Update systemd images with new user setups and related jenkinsfile changes to support AL2023
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: enhancement, integtest, release, cicd, docker, jenkins, rpm, distributions, deb, distinguished-contributor, v2.10.0

#4053 Fix test manifest path for 3.0.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4054 Update rpm validation and validate workflows docker args for AL2023
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
Labels: enhancement, integtest, release, cicd, docker, jenkins, distributions, distinguished-contributor, v2.10.0

#4051 Announce upcoming breaking changes in packaging
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: enhancement, release, rpm, distributions, deb, repeat-contributor

#4055 Update commits for next RC of 2.10.0
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: distinguished-contributor

#4056 Add pigz to integTest images for OpenSearch/Dashboards
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: enhancement, integtest, cicd, docker, jenkins, distributions, distinguished-contributor

#4058 Remove zstd codec benchmark runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4052 Add release notes for 1.3.13
  release-notes/opensearch-release-notes-1.3.13.md
Labels: distinguished-contributor

#4059 Replace ref with tags for 1.3.13
  manifests/1.3.13/opensearch-1.3.13.yml
  manifests/1.3.13/opensearch-dashboards-1.3.13.yml
Labels: distinguished-contributor

#4063 Add custom-codecs plugin to version increment workflow
  .github/workflows/os-increment-plugin-versions.yml
Labels: distinguished-contributor

#4065 Remove integration tests cronjob for 2.10.0
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3999 Add 2.10.0 consolidated release notes
  release-notes/opensearch-release-notes-2.10.0.md
Labels: distinguished-contributor

#4072 Add Insights repos to 2.11 manifest
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: first-time-contributor

#4074 Update refs to 2.10.0 tags
  manifests/2.10.0/opensearch-2.10.0.yml
  manifests/2.10.0/opensearch-dashboards-2.10.0.yml
Labels: distinguished-contributor

#4068 Add check before triggering tests from distribution build jobs
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4024 Separate min snapshot publication into separate workflow
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-darwin-build-manifest.yml
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-linux-build-manifest.yml
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-windows-build-manifest.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: distinguished-contributor
