Repository opensearch-project/opensearch-build, pull requests merged in 2023-10, with the labels that each got.

#4089 Adding AD to 2.11 manifests
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: valued-contributor

#4067 Add checks in case test type missing in report workflow
  .gitignore
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  src/report_workflow/test_report_runner.py
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3993 Validation Workflow enhancement to support run with different options for staging and local artifacts
  src/validation_workflow/api_test_cases.py
  src/validation_workflow/docker/validation_docker.py
  src/validation_workflow/download_utils.py
  src/validation_workflow/rpm/validation_rpm.py
  src/validation_workflow/tar/validation_tar.py
  src/validation_workflow/validation.py
  src/validation_workflow/validation_args.py
  src/validation_workflow/yum/validation_yum.py
  tests/tests_validation_workflow/test_api_test_cases.py
  tests/tests_validation_workflow/test_download_utils.py
  tests/tests_validation_workflow/test_validation.py
  tests/tests_validation_workflow/test_validation_args.py
  tests/tests_validation_workflow/test_validation_docker.py
  tests/tests_validation_workflow/test_validation_rpm.py
  tests/tests_validation_workflow/test_validation_tar.py
  tests/tests_validation_workflow/test_validation_yum.py
Labels: all-star-contributor

#4093 Add nightly runs for 2.11 and clean duplicate jobs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4095 Add all components to 2.11.0 manifest
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4098 Add support to run benchmarks using OpenSearch distribution url
  src/run_benchmark_test.py
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_runner.py
  src/test_workflow/benchmark_test/benchmark_test_runners.py
  tests/test_run_benchmark_test.py
  tests/tests_test_workflow/test_benchmark_args.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_runner_opensearch.py
Labels: distinguished-contributor

#4108 Update manifest ref to 2.11 for 2.11.0 release
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4110 Lock 2.11 commits and add test manifests
  jenkins/check-for-build.jenkinsfile
  manifests/2.11.0/opensearch-2.11.0-test.yml
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0-test.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4111 Update Ref back to 2.11
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4112 Only allow tar to create/close issues for integTests
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: release, distinguished-contributor, v2.11.0

#4083 Add entrance and exit criteria to release template
  .github/ISSUE_TEMPLATE/release_template.md
Labels: distinguished-contributor

#4119 Update commit-ids for 2.11.0 OS manifest
  manifests/2.11.0/opensearch-2.11.0.yml
Labels: distinguished-contributor

#4120 Update commit-ids for 2.11.0 OSD manifest
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4117 Fix: broken links and typos
  MAINTAINERS.md
  ONBOARDING.md
  README.md
  RELEASE_PROCESS_OPENSEARCH.md
  docker/release/README.md
  scripts/README.md
  zenhub_tab_image.png
Labels: documentation, first-time-contributor

#4122 Update OS and OSD component commit ids for 2.11
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4121 Onboard get-ci-image-tag in preparation for other repos
  .github/workflows/get-ci-image-tag.yml
  .github/workflows/python-tests.yml
Labels: enhancement, cicd, distinguished-contributor

#4125 Add simpler measure other workflows to retrieve docker images values
  .github/workflows/get-ci-image-tag.yml
  .github/workflows/python-tests.yml
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-windows-build-manifest.yml
Labels: enhancement, cicd, dependencies, distinguished-contributor

#4064 Automatically merge manifest changes after checks pass
  .github/workflows/automatic-merges.yml
Labels: distinguished-contributor

#4127 Freeze final commit-ids for 2.11 OS and OSD
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4129 Update release-notes commit-id for OS-2.11
  manifests/2.11.0/opensearch-2.11.0.yml
Labels: distinguished-contributor

#4128 Add build discarder for gradle check job
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4101 Run manifest check only aganist the changed manifest
  .github/workflows/manifests.yml
Labels: first-time-contributor

#4132 Add consolidated release notes for 2.11.0
  release-notes/opensearch-release-notes-2.11.0.md
Labels: distinguished-contributor

#4133 Update 2.11.0 tags in OS and OSD manifests
  manifests/2.11.0/opensearch-2.11.0.yml
  manifests/2.11.0/opensearch-dashboards-2.11.0.yml
Labels: distinguished-contributor

#4097 Support multinode cluster logging
  src/test_workflow/test_recorder/test_recorder.py
  tests/tests_test_workflow/test_recorder/test_test_recorder.py
Labels: valued-contributor

#4137 Add version and type entry for docker images retrieval
  .github/workflows/get-ci-image-tag.yml
Labels: enhancement, cicd, dependencies, distinguished-contributor

#4143 Improve windows java switch logic on Jenkins
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: bug, enhancement, cicd, docker, windows, jenkins, distributions, distinguished-contributor

#4135 Support automatic merging of new manifest files
  .github/workflows/automatic-merges.yml
Labels: distinguished-contributor

#4146 Add nightly benchmark runs for 2.12.0 and remove remote-store runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4147 Onboard 5.10.1 lib to fix the scoop issue on Windows Java verion switch
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: bug, integtest, cicd, docker, windows, jenkins, distributions, distinguished-contributor

#4148 BUNDLE_MANIFEST env var bug-fix in benchmark jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
Labels: distinguished-contributor

#4149 Bump peternied/discerning-merger from 2 to 3
  .github/workflows/automatic-merges.yml
Labels: distinguished-contributor

#4152 Update build library version in benchmark jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4116 Jenkins job updation for validation workflow
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  src/validation_workflow/validation_args.py
  tests/jenkins/TestValidateArtifacts.groovy
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: all-star-contributor

#4154 Update jdk setup to include jdk14 for gradle check
  docker/ci/config/jdk-setup.sh
Labels: cicd, docker, dependencies, distinguished-contributor

#4153 Support JDK-21 builds on Jenkins
  docker/ci/config/jdk-setup.sh
Labels: seasoned-contributor

#4158 bump Jenkins Test Harness
  build.gradle
Labels: all-star-contributor

#4162 Support JDK-21 builds on Windows
  docker/ci/config/windows-servercore-setup.ps1
Labels: seasoned-contributor

#4163 Adding license header to repo files
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.windows2019.servercore.x64.dockerfile
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/build.ubuntu18.opensearch.x64.dockerfile
  docker/ci/dockerfiles/legacy/data-prepper.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/legacy/test.centos7.gradle-check.x64.dockerfile
  docker/ci/dockerfiles/legacy/test.centos7.performance-test.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/test.centos7.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/yq.alpine3.x64.arm64.dockerfile
  docker/release/config/opensearch/log4j2.properties
  docker/release/config/opensearch/performance-analyzer.properties
  jenkins/check-for-build.jenkinsfile
  jenkins/cross-cluster-replication/perf-test.jenkinsfile
  jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/docker/docker-build.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-re-release.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/legacy/perf-test.jenkinsfile
  jenkins/manifests-update.jenkinsFile
  jenkins/opensearch-dashboards/bwc-test.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  jenkins/packer/packer-build.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
  jenkins/promotion/promote-docker-ecr.jenkinsfile
  jenkins/promotion/promote-repos.jenkinsfile
  jenkins/release-notes-check/release-notes-check.jenkinsfile
  jenkins/release-tag/release-tag.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  jenkins/vulnerability-scan/whitesource-scan.jenkinsfile
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
  scripts/pkg/service_templates/opensearch-dashboards/usr/lib/systemd/system/opensearch-dashboards.service
  scripts/pkg/service_templates/opensearch/usr/lib/systemd/system/opensearch-performance-analyzer.service
  scripts/pkg/service_templates/opensearch/usr/lib/systemd/system/opensearch.service
Labels: first-time-contributor

#4090 Throw error for duplicate component names in manifests YML
  src/ci_workflow/ci_manifests.py
  tests/tests_ci_workflow/data/opensearch-1.3.11.yml
  tests/tests_ci_workflow/test_duplicate_components_in_manifest_file.py
Labels: first-time-contributor

#4164 Revert CCR test setting for 2.11
  manifests/2.11.0/opensearch-2.11.0-test.yml
Labels: distinguished-contributor

#4168 Add nightly runs for ES-7.10.2
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4118 Updated license header checker to Deno License Checker
  .github/workflows/license-header-checker.yml
  .licenserc.json
Labels: first-time-contributor

#4172 Update JDK-21 to JDK-21.0.1 on Jenkins
  docker/ci/config/jdk-setup.sh
Labels: seasoned-contributor

#4174 Add docker-compose and fix docker-re-release lib version
  docker/ci/config/windows-servercore-setup.ps1
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  jenkins/docker/docker-re-release.jenkinsfile
  tests/jenkins/TestDockerReRelease.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-re-release.jenkinsfile.txt
Labels: bug, enhancement, cicd, docker, jenkins, distributions, distinguished-contributor

#4173 Add support for optional benchmark command line args
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_args.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster_min.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4177 Update checkout version to v3 as node12 is deprecated now
  .github/workflows/get-ci-image-tag.yml
Labels: enhancement, docker, dependencies, distinguished-contributor

#4178 Update the gradle check with docker command checks
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4180 Added support for test-procedure, exclude-tasks and include-tasks benchmark arguments
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4181 Add opensearch-cluster-cdk 1.x git branch support
  src/test_workflow/benchmark_test/benchmark_test_runner.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_runner_opensearch.py
Labels: distinguished-contributor

#4183 Minor bug fix in repo checkout logic for benchmark workflow
  src/test_workflow/benchmark_test/benchmark_test_runner.py
Labels: distinguished-contributor

#4184 Remove concurrent search nightlies and add multi-node ES-7.10.2 nightlies
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4182 Update 3.0.0 manifest to use JDK-21
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
Labels: seasoned-contributor

#4186 Update cron job for 2.11.1
  jenkins/check-for-build.jenkinsfile
Labels: all-star-contributor

#4188 Update version to latest release `5.11.1`: Solves creation and closing of multiple `AUTOCUT` issues
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor
