Repository opensearch-project/opensearch-build, pull requests merged in 2023-07, with the labels that each got.

#3698 Fix label description for newly created labels
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3703 Handle core label creation
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3658 [Python 3.9 Upgrade] OpenSearch-Build Repo Python Migration to 3.9 Version
  .github/workflows/manifests.yml
  .github/workflows/python-tests.yml
  .github/workflows/versions.yml
  .github/workflows/yaml-lint.yml
  Pipfile
  Pipfile.lock
  jenkins/cross-cluster-replication/perf-test.jenkinsfile
  jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/manifests-update.jenkinsFile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/perf-test.jenkinsfile
  jenkins/promotion/promote-repos.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  manifests/2.7.1/opensearch-dashboards-2.7.1.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
  manifests/2.8.1/opensearch-2.8.1.yml
  manifests/2.8.1/opensearch-dashboards-2.8.1.yml
  manifests/2.9.0/opensearch-2.9.0-seg-rep-test.yml
  manifests/2.9.0/opensearch-2.9.0-test.yml
  manifests/2.9.0/opensearch-2.9.0.yml
  manifests/2.9.0/opensearch-dashboards-2.9.0-test.yml
  manifests/2.9.0/opensearch-dashboards-2.9.0.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  manifests/templates/opensearch-dashboards/1.x/manifest.yml
  manifests/templates/opensearch-dashboards/2.x/manifest.yml
  manifests/templates/opensearch-dashboards/3.x/manifest.yml
  manifests/templates/opensearch-dashboards/default/manifest.yml
  manifests/templates/opensearch/1.x/manifest.yml
  manifests/templates/opensearch/2.x/manifest.yml
  manifests/templates/opensearch/3.x/manifest.yml
  manifests/templates/opensearch/default/manifest.yml
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
  tests/test_run_assemble.py
  tests/tests_manifests_workflow/test_input_manifests.py
  tests/tests_system/test_process.py
Labels: enhancement, release, jenkins, Build Libraries & Interfaces, python, distinguished-contributor, v2.9.0, python3.9 upgrade

#3705 Remove ml-commons-dashboards experiment keyword in config file
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
Labels: repeat-contributor

#3713 Add input-manifest argument to Github-issue-creation library
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: seasoned-contributor

#3711 [Python 3.9 Upgrade] [NodeJS Upgrade] Update perftest and benchmark test runner to AL2023
  jenkins/cross-cluster-replication/perf-test.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  jenkins/opensearch/perf-test.jenkinsfile
Labels: enhancement, cicd, performance, jenkins, distinguished-contributor, python3.9 upgrade, nodejs upgrade

#3714 [Python 3.9 Upgrade] [NodeJS Upgrade] Update developer guide for Python 3.9 Upgrade and Node Version Upgrade
  DEVELOPER_GUIDE.md
Labels: documentation, distinguished-contributor, python3.9 upgrade, nodejs upgrade

#3715 Update workload parameters to be passed as json
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#3720 Bump library version to 5.1.0 for benchmarks
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#3721 Add new runner for gradle check on Ubuntu
  jenkins/gradle/gradle-check.jenkinsfile
Labels: enhancement, jenkins, distinguished-contributor

#3722 Update cmake to 3.23.3 for k-NN in 2.9.0 in docker images
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: enhancement, release, cicd, jenkins, dependencies, distinguished-contributor, v2.9.0

#3723 Update workload-params to json format and add nightly runs for zstd_no_dict codec type
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#3725 Remove remote store configuration from segrep manifest file for 2.9
  manifests/2.9.0/opensearch-2.9.0-seg-rep-test.yml
Labels: repeat-contributor

#3726 Tweak description of gradle check to include better agent information
  jenkins/gradle/gradle-check.jenkinsfile
Labels: enhancement, jenkins, distinguished-contributor

#3728 Add check if security plugin exists in startup script
  scripts/startup/tar/linux/opensearch-tar-install.sh
  scripts/startup/zip/windows/opensearch-windows-install.bat
Labels: distinguished-contributor

#3730 [Release 2.9.0] Remove k-NN
  manifests/2.9.0/opensearch-2.9.0.yml
Labels: distinguished-contributor

#3732 Upgrade gcc to 8 with devtoolset-8 for k-NN faiss lib compilation
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
Labels: bug, release, distinguished-contributor, v2.9.0

#3734 [Release 2.9.0] Add k-NN back
  manifests/2.9.0/opensearch-2.9.0.yml
Labels: distinguished-contributor

#3735 Update the gcc version to 7 for knn lib on arm64
  docker/ci/config/scl_setup_devtoolset7
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
Labels: bug, release, cicd, docker, jenkins, distinguished-contributor, v2.9.0

#3736 [Release 2.9.0] Remove 2.9.0 cron
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#3708 Automation for component release issue creation
  .github/ISSUE_TEMPLATE/component_release_template.md
  .github/workflows/releases.yml
Labels: distinguished-contributor

#3739 Automation for component release issue creation: Fix bracket error
  .github/workflows/releases.yml
Labels: distinguished-contributor

#3740 [Release 2.9.0] Manifests commit lock
  manifests/2.9.0/opensearch-2.9.0.yml
  manifests/2.9.0/opensearch-dashboards-2.9.0.yml
Labels: distinguished-contributor

#3742 Automation for component release issue creation: Fix the GH 256 job limit
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
  .github/workflows/releases.yml
Labels: distinguished-contributor

#3744 Automation for component release issue creation: Fix the right outputs
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#3745 Automation component release issue: Fix the bugs
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#3796 [Release 2.9.0] Revert Manifests commit lock
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.9.0/opensearch-2.9.0.yml
  manifests/2.9.0/opensearch-dashboards-2.9.0.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3795 Automation component release issue: Fix the bugs
  .github/ISSUE_TEMPLATE/component_release_template.md
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#3797 Automation component release issue: Fix label add bug
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#3802 [Release 2.9.0] Update anomalyDetectionDashboards , alertingDashboards and OpenSearch-Dashboards for 3rd RC
  manifests/2.9.0/opensearch-dashboards-2.9.0.yml
Labels: distinguished-contributor

#3801 Automation component release issue: Workflow update
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#3803 [Release 2.9.0] Consolidated release notes
  release-notes/opensearch-release-notes-2.9.0.md
Labels: distinguished-contributor

#3807 [Release 2.9.0] Input Manifest tag update
  manifests/2.9.0/opensearch-2.9.0.yml
  manifests/2.9.0/opensearch-dashboards-2.9.0.yml
Labels: distinguished-contributor

#3800 Update docker related copy lib to new version
  jenkins/docker/docker-copy.jenkinsfile
  tests/jenkins/TestDockerCopy.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy.jenkinsfile.txt
Labels: bug, enhancement, cicd, docker, jenkins, Build Libraries & Interfaces, distinguished-contributor

#3810 Switch validation workflow for docker to run on AL2023 and Gradle Check to new M58xlarge runners
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: enhancement, release, cicd, jenkins, distinguished-contributor, v2.9.0, python3.9 upgrade

#3812 fix vcs url
  docker/release/dockerfiles/opensearch.al2.dockerfile
Labels: first-time-contributor

#3811 Fix integ tests for windows platform
  src/system/execute.py
  src/system/process.py
  src/test_workflow/test_recorder/test_recorder.py
  tests/tests_system/test_process.py
  tests/tests_test_workflow/test_recorder/test_test_recorder.py
Labels: distinguished-contributor

#3818 Close the created [AUTOCUT] issues
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  src/run_build.py
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3828 Close the created [AUTOCUT] issues : Move the `closeBuildSuccessGithubIssue` to post:always
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#3829 Fix the hardcoded query string bug for closeBuildSuccessGithubIssue
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3830 Add security to 2.10.0 manifest
  manifests/2.10.0/opensearch-2.10.0.yml
Labels: distinguished-contributor

#3831 Update nightly benchmark runs for OS-2.10
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor
