Repository opensearch-project/opensearch-build, pull requests merged in 2023-04, with the labels that each got.

#3360 Restore the component release issue template
  .github/ISSUE_TEMPLATE/component_release_template.md
  .github/ISSUE_TEMPLATE/release_template.md
Labels: distinguished-contributor

#3364 Switch jenkinsfile to use ecr registry
  jenkins/check-for-build.jenkinsfile
  jenkins/cross-cluster-replication/perf-test.jenkinsfile
  jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/docker/docker-build.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/opensearch-dashboards/bwc-test.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/perf-test.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
  jenkins/promotion/promote-docker-ecr.jenkinsfile
  jenkins/promotion/promote-repos.jenkinsfile
  jenkins/release-notes-check/release-notes-check.jenkinsfile
  jenkins/release-tag/release-tag.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/vulnerability-scan/whitesource-scan.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/cross-cluster-replication/perf-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDocker.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/vulnerability-scan/whitesource-scan.jenkinsfile.txt
Labels: cicd, jenkins, distinguished-contributor

#3356 [OSD] include Node 14.21.3
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/release.centos.clients.x64.arm64.dockerfile
  manifests/1.4.0/opensearch-dashboards-1.4.0.yml
Labels: all-star-contributor

#3366 Add observability, reporting, visualizations and query workbench to 2.7 manifest
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: valued-contributor

#3370 Make repo_name var to allow user specify different docker repo and increase Jenkins docker build timeout
  docker/ci/build-image-multi-arch.sh
  docker/ci/build-image-single-arch.sh
  jenkins/docker/docker-build.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
Labels: enhancement, cicd, docker, jenkins, distinguished-contributor

#3369 Update ref branch to 2.7 for OpenSearch-Spatial plugins
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: valued-contributor

#3367 Add dockerhub readonly user login before gradle check
  jenkins/docker/docker-build.jenkinsfile
  jenkins/gradle/gradle-check.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
Labels: enhancement, cicd, docker, distinguished-contributor

#3374 Adding docker login for the remote triggered gradle check
  jenkins/gradle/gradle-check.jenkinsfile
Labels: bug, docker, jenkins, distinguished-contributor

#3376 Switch docker copy to use only 2.2.1 version libs
  jenkins/docker/docker-copy.jenkinsfile
  tests/jenkins/TestDockerCopy.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy.jenkinsfile.txt
Labels: bug, docker, jenkins, distinguished-contributor

#3378 Remove AS plugin from 3.0.0 manifest
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: distinguished-contributor

#3377 Add notification plugin to 2.7 manifest
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: first-time-contributor

#3365 Add ml-commons-dashboards to 2.7.0 manifest
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: first-time-contributor

#3375 Add AD and AD-Dashboard 2.7 manifests
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: repeat-contributor

#3380 Add ISM and notification dashboard plugin into manifest
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: first-time-contributor

#3384 Add SQL and QueryWorkbench to 2.7.0 manifest
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: valued-contributor

#3389 Add Neural-Search Plugin and add windows to k-NN in 3.0.0 manifest
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: valued-contributor

#3368 Add new Jenkins workflow for build packer.
  jenkins/packer/packer-build.jenkinsfile
  tests/jenkins/TestDockerBuild.groovy
  tests/jenkins/TestPackerBuild.groovy
  tests/jenkins/jenkinsjob-regression-files/packer/packer-build.jenkinsfile.txt
Labels: distinguished-contributor

#3392 Add async search in 2.7 manifest
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: first-time-contributor

#3393 Add build args on the docker ci build scripts
  docker/ci/build-image-multi-arch.sh
  docker/ci/build-image-single-arch.sh
Labels: distinguished-contributor

#3397 Change ref to 2.7 for cross-cluster-replication
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: repeat-contributor

#3394 Tweak PA log path to be in sync with the latest changes
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
  jenkins/rpm-validation/rpm-validation.jenkinsfile
Labels: bug, docker, distinguished-contributor

#3395 Enable integration test failure notification via GitHub issues
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3398 Add autocut in issue title for integration test failures
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
Labels: distinguished-contributor

#3399 Added the alerting and security analytics front and backend plugins to the 2.7 manifest.
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: valued-contributor

#3388 Fixing CDK cluster left over issue when a performance testing job was aborted
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/TestRunNonSecurityPerfTestScript.groovy
Labels: seasoned-contributor

#3400 Add Security Dashboards Plugin into 2.7 manifest
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: repeat-contributor

#3402 Change security backend branch ref to 2.7 in manifest
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: repeat-contributor

#3403 Add distribution details to integration test failure issues
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
Labels: distinguished-contributor

#3405 Added ISM backend plugin to 2.7 manifest file.
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: valued-contributor

#3408 Add 1.3.9 perf test with https_logs load
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
Labels: performance, v1.3.9, distinguished-contributor

#3407 Add Peformance Analyzer to 2.7 manifest
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: valued-contributor

#3411 Add dashboards-search-relevance to 2.7 manifest
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: distinguished-contributor

#3416 Update 2.7.0 segment-replication manifest file with new feature flag
  manifests/2.7.0/opensearch-2.7.0-segment-replication-test.yml
Labels: first-time-contributor

#3414 Update 2.7 release branch in the distribution manifest for Performance Analyzer
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: first-time-contributor

#3417 switching searchRelevanceDashboards from 2.x to 2.7
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: first-time-contributor

#3419 Update opensearch-3.0.0.yml with PA plugin
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: first-time-contributor

#3406 Update ref to 2.7 branch for 2.7.0 build manifest
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: distinguished-contributor

#3420 Add dashboards test manifests for FT repo
  manifests/2.7.0/opensearch-dashboards-2.7.0-test.yml
Labels: distinguished-contributor

#3423 Remove cron job for 2.7.0 distribution build
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#3427 Replace the commits to freeze commits in 2.7.0 manifests
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: distinguished-contributor

#3430 Update commits for OSD and security analytics dashboards
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: distinguished-contributor

#3421 Correction on Fixing CDK cluster left over issue when a performance testing job was aborted
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/TestRunNonSecurityPerfTestScript.groovy
Labels: seasoned-contributor

#3429 Add jenkins file for manifest update workflow
  jenkins/manifests-update.jenkinsFile
Labels: distinguished-contributor

#3436 Add cu and js to 2.8.0 manifest
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: all-star-contributor

#3437 Update commit ID for OpenSearch
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: distinguished-contributor

#3439 Update the commits for OS and OSD
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: distinguished-contributor

#3444 [OSD][2.7] Update observability plugin commit
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: all-star-contributor

#3447 Add additional configs vis_builder for OSD test manifest
  manifests/2.7.0/opensearch-dashboards-2.7.0-test.yml
Labels: distinguished-contributor

#3445 Tweak integTest to use 4.1.1 libs for OS/OSD runs
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: bug, distinguished-contributor

#3451 Update commits ID for sql observability and reporting
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: distinguished-contributor

#3453 Fix missing local cluster logs when running integration test
  src/test_workflow/integ_test/service.py
  src/test_workflow/test_cluster.py
Labels: distinguished-contributor
