Repository opensearch-project/opensearch-build, pull requests merged in 2023-06, with the labels that each got.

#3586 Add 3.0 for nightly benchmark runs and update segrep setting.
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: all-star-contributor

#3587 Remove 2.8.0 check-for-build cron
  jenkins/check-for-build.jenkinsfile
Labels: all-star-contributor

#3579 Restore gradle check on windows agents and disable 2.7.1/2.8.0 builds and lock commitids
  jenkins/gradle/gradle-check.jenkinsfile
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: bug, cicd, jenkins, distinguished-contributor

#3588 Remove segrep benchmark run for 3.0
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: all-star-contributor

#3592 Add 300sec client timeout to benchmark command
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: all-star-contributor

#3590 Add additional cluster config support in OSD integTest
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  src/test_workflow/integ_test/service_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch_dashboards.py
Labels: bug, integtest, release, cicd, v2.8.0, distinguished-contributor

#3594 Add 2nd RC changes for 2.8.0 Version
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: release, v2.8.0, distinguished-contributor

#3595 Update 3.0.0 manifest to use JDK-20
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: valued-contributor

#3596 Update 2.8.0 3rd RC build commit ids
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: release, v2.8.0, distinguished-contributor

#3597 New ml change to fix shadow publication in 2.8.0 rc3
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: release, v2.8.0, distinguished-contributor

#3598 Remove 2.8.0 scheduled integTest and add more timeouts
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: integtest, release, v2.8.0, distinguished-contributor

#3600 Update ubuntu image chromium installation methods
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: bug, integtest, cicd, docker, jenkins, distinguished-contributor

#3601 Add new release notes scripts for consolidated release notes
  .shellcheckrc
  scripts/release-notes/release-notes.sh
Labels: release, v2.8.0, distinguished-contributor

#3603 Switch 2.8.0 ref in manifest to tags
  jenkins/check-for-build.jenkinsfile
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: release, v2.8.0, distinguished-contributor

#3605 Update opensearch-release-notes-2.8.0.md
  release-notes/opensearch-release-notes-2.8.0.md
Labels: first-time-contributor

#3608 Removed 2.7 benchmark run and added new metadata tags
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: all-star-contributor

#3609 Fix broken manifest workflow
  .github/workflows/osd-increment-plugin-versions.yml
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: distinguished-contributor

#3611 Add major-version metadata tag to benchmark run metrics.
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: all-star-contributor

#3555 Add Jenkins Job for Validation workflow
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  tests/jenkins/TestValidateArtifacts.groovy
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: seasoned-contributor

#3618 Added common-utils and job-scheduler to 2.9.0 manifest
  manifests/2.9.0/opensearch-2.9.0.yml
Labels: distinguished-contributor

#3624 Bug fix for docker validation digest mismatch in arm64
  src/validation_workflow/docker/inspect_docker_image.py
  tests/tests_validation_workflow/test_inspect_docker_image.py
Labels: all-star-contributor

#3627 Bump jenkins-test-harness version to 2002.v0b_78b_a_d69e5d
  build.gradle
Labels: distinguished-contributor

#3628 Add sql plugin and ml-commons to 2.9 snapshot
  manifests/2.9.0/opensearch-2.9.0.yml
Labels: first-time-contributor

#3626 Adding 1.3.11 manifest
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.11/opensearch-1.3.11.yml
  tests/test_run_manifests.py
Labels: all-star-contributor

#3632 Updating cron to build 1.3.11 hourly and adding dashboards manifest
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.11/opensearch-dashboards-1.3.11.yml
Labels: all-star-contributor

#3634 [Python 3.9 Update] Docker CI Images update 3.7 to 3.9 (Part 1)
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
Labels: enhancement, integtest, release, cicd, docker, jenkins, distinguished-contributor, upgrade, v2.9.0, python3.9 upgrade

#3639 [1.3.11] Correction on Input manifest
  manifests/1.3.11/opensearch-1.3.11.yml
Labels: all-star-contributor

#3640 [1.3.11] Updateing 1.3.11 maven SNAPSHOT publish
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
Labels: all-star-contributor

#3641 Change docker build jenkins workflow to use the v2 docker-builder images
  jenkins/docker/docker-build.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
Labels: cicd, docker, jenkins, distinguished-contributor

#3642 [1.3.11]correction on missing update
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
Labels: all-star-contributor

#3644 [1.3.11] Adding more compnents to input manifest
  manifests/1.3.11/opensearch-1.3.11.yml
  manifests/1.3.11/opensearch-dashboards-1.3.11.yml
Labels: all-star-contributor

#3646 [1.3.11] Adding Security component in OS input manifest
  manifests/1.3.11/opensearch-1.3.11.yml
Labels: all-star-contributor

#3650 Replace Python 3.9.17 to 3.9.7 to resolve compilation inconsistency on CentOS7
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
Labels: enhancement, integtest, release, cicd, docker, jenkins, distinguished-contributor, v2.9.0, python3.9 upgrade

#3654 [1.3.11] Updating input manifest - adding test yaml and adding more components
  manifests/1.3.11/opensearch-1.3.11-test.yml
  manifests/1.3.11/opensearch-1.3.11.yml
  manifests/1.3.11/opensearch-dashboards-1.3.11-test.yml
  manifests/1.3.11/opensearch-dashboards-1.3.11.yml
Labels: all-star-contributor

#3655 Add test manifests for 2.9.0
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.9.0/opensearch-2.9.0-seg-rep-test.yml
  manifests/2.9.0/opensearch-2.9.0-test.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3656 Add 2.9.0 all components to manifest
  manifests/2.9.0/opensearch-2.9.0.yml
Labels: distinguished-contributor

#3660 Release Label creation automation
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3662 Fix cron for jenkins
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3663 [1.3.11] Adding remaning components in OS input manifest
  manifests/1.3.11/opensearch-1.3.11.yml
Labels: all-star-contributor

#3664 Release Label creation automation - 2
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: enhancement, distinguished-contributor

#3665 Release Label creation automation - 3
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: enhancement, distinguished-contributor

#3666 [1.3.11] Lock RC and remove 1.3.11 check for build
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.11/opensearch-1.3.11.yml
  manifests/1.3.11/opensearch-dashboards-1.3.11.yml
Labels: all-star-contributor

#3667 Release Label creation automation - 4
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3668 [1.3.11] Update perf-test for 1.3.11
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
Labels: all-star-contributor

#3675 Make distribution build of OpenSearch to use 4.3.0 version lib
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: enhancement, distributions, distinguished-contributor

#3659 Add osd 2.9.0 related manifests to build repo
  jenkins/check-for-build.jenkinsfile
  manifests/2.9.0/opensearch-dashboards-2.9.0-test.yml
  manifests/2.9.0/opensearch-dashboards-2.9.0.yml
Labels: release, distinguished-contributor, v2.9.0

#3677 Add nighlty run for remote-store and 1-replica cluster config
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#3679 fix ADDITIONAL_CONFIG parameter value format
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#3645 Update README for distribution level BWC tests
  src/test_workflow/README.md
Labels: distinguished-contributor

#3681 Add sql to manifest 3.0
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: first-time-contributor

#3680 [Python 3.9 Upgrade] Add the test docker images upgrades to Python 3.9 (Part 2)
  docker/ci/dockerfiles/current/test.centos7.performance-test.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: enhancement, integtest, release, cicd, docker, jenkins, python, distinguished-contributor, v2.9.0, python3.9 upgrade

#3683 Disable longetivity performance tests
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
Labels: distinguished-contributor

#3550 Autocut Github issue when OSD Integ test component fails
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/data/opensearch-dashboards-3.0.0-build.yml
  tests/jenkins/data/opensearch-dashboards-3.0.0-test.yml
  tests/jenkins/data/opensearch-dashboards-3.0.0.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: seasoned-contributor

#3684 Add support to run benchmark against min distribution
  src/run_benchmark_test.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_runner.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch_plugins.py
  src/test_workflow/benchmark_test/benchmark_test_runners.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/data/min_distribution_manifest.yml
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster_min.py
Labels: distinguished-contributor

#3688 Add nightly benchmark run for min distribution
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#3687 [1.3.11] Consolidate 1.3.11 Release Notes
  release-notes/opensearch-release-notes-1.3.11.md
Labels: release, v1.3.11

#3693 [1.3.11] update manifest with tag 1.3.11
  manifests/1.3.11/opensearch-1.3.11.yml
  manifests/1.3.11/opensearch-dashboards-1.3.11.yml
Labels: all-star-contributor

#3695 Fix build issue creation library name for 4.3.0 version
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#3696 Add 2.9.0 test manifest to check-build
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor
