Repository opensearch-project/opensearch-build, pull requests merged in 2023-01, with the labels that each got.

#3040 Upgrade node version to 14.20.1 for 2.5.0
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
Labels: docker, v2.5.0

#3066 Add missing PA configuration files to TAR/Docker
  scripts/components/performance-analyzer/install.sh
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: bug, release, docker, v2.5.0

#3061 Move everything in 2.5.0 from 2.x to 2.5 branch in manifest
  manifests/2.5.0/opensearch-2.5.0.yml
  manifests/2.5.0/opensearch-dashboards-2.5.0.yml
Labels: release, v2.5.0

#3090 Add PA fix to missing config files errors
  scripts/components/OpenSearch-Dashboards/install.sh
  scripts/components/OpenSearch/install.sh
  scripts/components/performance-analyzer/install.sh
  scripts/default/install.sh
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: bug

#3094 Pause release 2.5.0 auto builds now
  jenkins/check-for-build.jenkinsfile
Labels: release, v2.5.0

#3060 Adding DEB Maintainers Scripts and Build CI Images
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  scripts/pkg/build_templates/opensearch-dashboards/deb/Makefile
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/control
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/copyright
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/preinst
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/prerm
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/rules
  scripts/pkg/build_templates/opensearch-dashboards/deb/debmake_opensearch_dashboards_install.sh
  scripts/pkg/build_templates/opensearch/deb/Makefile
  scripts/pkg/build_templates/opensearch/deb/debian/control
  scripts/pkg/build_templates/opensearch/deb/debian/copyright
  scripts/pkg/build_templates/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/opensearch/deb/debian/preinst
  scripts/pkg/build_templates/opensearch/deb/debian/prerm
  scripts/pkg/build_templates/opensearch/deb/debian/rules
  scripts/pkg/build_templates/opensearch/deb/debmake_opensearch_install.sh
  src/assemble_workflow/bundle_linux_deb.py
  tests/tests_assemble_workflow/test_bundle_linux_deb.py
Labels: deb

#3095 Add 1.5.4 as the new lib version for deb support
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
Labels: release, v2.5.0, deb

#3096 Including possible configs in the rpm data directory
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: bug, release, v2.5.0

#3114 Resolve service file not properly load k-NN libs
  scripts/pkg/service_templates/opensearch/etc/sysconfig/opensearch
Labels: release, v2.5.0

#3149 Add distribution selector for distribution builds on Jenkins
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: release, jenkins, v1.3.8

#3151 Revert OS build workflow to original state due to method too large error
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: release, jenkins, v1.3.8
