Repository opensearch-project/opensearch-build, pull requests merged in 2023-12, with the labels that each got.

#4254 Add concurrent snapshot benchmark runs for 2.12.0
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4257 Fix incorrect link in release notes
  release-notes/opensearch-release-notes-2.11.1.md
Labels: distinguished-contributor

#4258 Update 2.11.1 tags in OS and OSD manifests
  manifests/2.11.1/opensearch-2.11.1.yml
  manifests/2.11.1/opensearch-dashboards-2.11.1.yml
Labels: distinguished-contributor

#4255 Add more components to 1.3.14 manifest
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.14/opensearch-1.3.14-test.yml
  manifests/1.3.14/opensearch-1.3.14.yml
Labels: distinguished-contributor

#4261 Update manifests.yml to dynamically define jdk versions based on manifest image jdk export
  .github/workflows/manifests.yml
Labels: bug, cicd, distinguished-contributor

#4264 Add rest of components to 1.3.14 manifest
  .github/workflows/manifests.yml
  manifests/1.3.14/opensearch-1.3.14.yml
  manifests/1.3.14/opensearch-dashboards-1.3.14-test.yml
  manifests/1.3.14/opensearch-dashboards-1.3.14.yml
Labels: distinguished-contributor

#4196 Release notes automation
  .gitignore
  Pipfile
  Pipfile.lock
  src/release_notes_workflow/README.md
  src/release_notes_workflow/release_notes.py
  src/release_notes_workflow/release_notes_check_args.py
  src/release_notes_workflow/release_notes_component.py
  src/run_releasenotes_check.py
  tests/data/opensearch-test-main.yml
  tests/tests_release_notes_workflow/test_release_notes.py
  tests/tests_release_notes_workflow/test_releasenotes_check_args.py
Labels: first-time-contributor

#4268 Added neural-search to 2.12 manifest
  manifests/2.12.0/opensearch-2.12.0.yml
Labels: repeat-contributor

#4273 Freeze commit ids for 1.3.14 manifests
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.14/opensearch-1.3.14.yml
  manifests/1.3.14/opensearch-dashboards-1.3.14.yml
Labels: distinguished-contributor

#4197 [Release 2.12.0] Manifest components update
  manifests/2.12.0/opensearch-2.12.0.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
Labels: distinguished-contributor

#4277 Add consolidated release notes for 1314
  release-notes/opensearch-release-notes-1.3.14.md
Labels: distinguished-contributor

#4278 Using jenv to set Java version on Jenkins Mac agent node
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: all-star-contributor

#4282 Replace refs in manifests with tags for 1.3.14
  manifests/1.3.14/opensearch-1.3.14.yml
  manifests/1.3.14/opensearch-dashboards-1.3.14.yml
Labels: distinguished-contributor

#4224 Mark build stage as unstable if plugins failed to build
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4287 Move unstable functional call to post always block
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4244 Fix k-NN 2.10 Release Notes
  release-notes/opensearch-release-notes-2.10.0.md
Labels: valued-contributor

#4288 Bump lib version to 5.12.0 and remove previous unstable code
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4270 Add onboarding guide for pypi GHA release
  ONBOARDING.md
Labels: distinguished-contributor

#4293 Add jenkins build number to benchmark metric user-tags
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4299 [Release 2.12.0] Add test manifests
  manifests/2.12.0/opensearch-2.12.0-test.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0-test.yml
Labels: distinguished-contributor

#4300 [Release 2.12.0] Update the check-for-build.jenkinsfile with test manifest.
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4304 Support security demo script changes
  Pipfile
  Pipfile.lock
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_runner.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_runner_opensearch.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4306 Add strong password check on cluster connection.
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
Labels: distinguished-contributor

#4280 Central workflow to trigger pre-release workflows
  jenkins/promotion/release-promotion.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor

#4315 OpenSearch Dashboards restrict version increment files
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#4310 Fix path for publish wiki workflow
  .github/workflows/publish-wiki.yml
Labels: first-time-contributor
