Repository opensearch-project/opensearch-build, pull requests merged in 2023-05, with the labels that each got.

#3452 Add consolidated release notes for 2.7.0
  release-notes/opensearch-release-notes-2.7.0.md
Labels: distinguished-contributor

#3459 Fix typo in the tag creation workflow
  jenkins/release-tag/release-tag.jenkinsfile
Labels: distinguished-contributor

#3415 Workflow to run performance tests using opensearch-benchmark
  src/run_benchmark_test.py
  src/test_workflow/README.md
  src/test_workflow/benchmark_test/__init__.py
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_runner.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch_plugins.py
  src/test_workflow/benchmark_test/benchmark_test_runners.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  src/test_workflow/json_args.py
  test.sh
  tests/data/test-config.yml
  tests/test_run_benchmark_test.py
  tests/tests_test_workflow/data/test-config.yml
  tests/tests_test_workflow/test_benchmark_args.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/__init__.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/data/bundle_manifest.yml
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/data/test-config.yml
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_runner_opensearch.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: all-star-contributor

#3460 Replace refs with tags for 2.7.0 manifests and remove cron
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/perf-test.jenkinsfile
  manifests/2.7.0/opensearch-2.7.0.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
Labels: distinguished-contributor

#3466 Workflow for OSD Version Increment
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3467 Workflow for OSD Version Increment: Update plugin_helpers
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3469 OSD Version Increment: Add subpath support
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3325 docker validation improvement
  src/run_validation.py
  src/validation_workflow/api_test_cases.py
  src/validation_workflow/docker/inspect_docker_image.py
  src/validation_workflow/docker/validation_docker.py
  src/validation_workflow/validation.py
  src/validation_workflow/validation_args.py
  tests/test_run_validation.py
  tests/tests_validation_workflow/test_validation_args.py
  tests/tests_validation_workflow/test_validation_docker.py
Labels: seasoned-contributor

#3474 Install gh package from git-cli
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/current/test.centos7.performance-test.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
Labels: seasoned-contributor

#3316 Updated integ-tests implementation to run all the OSD plugins.
  src/test_workflow/integ_test/integ_test_suite.py
  src/test_workflow/integ_test/integ_test_suite_opensearch.py
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch_dashboards.py
Labels: seasoned-contributor

#3465 Jenkins Job to run OSDInteg in Parallel
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: seasoned-contributor

#3472 Enable knn in 2.8
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: seasoned-contributor

#3477 Add 3.0.0 osd test manifest
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
Labels: seasoned-contributor

#3435 Make systemd-tmpfiles optional
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: rpm, deb, first-time-contributor

#3479 Resolve PA proc not disown and ml_dashboards settings missing in OSD docker entrypoint
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
Labels: bug, docker, distinguished-contributor

#3481 Add new optional parameters for OS cluster and benchmark
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/data/test-config.yml
  tests/tests_test_workflow/data/test-config.yml
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/data/test-config.yml
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: all-star-contributor

#3487 Make trivy installation auto pickup latest version
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
Labels: enhancement, docker, distinguished-contributor, scanning

#3488 Remove test-mode flag from opensearch-benchmark command
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: all-star-contributor

#3489 Update comment information to OS Integtest Jenkins job
  jenkins/opensearch/integ-test.jenkinsfile
Labels: seasoned-contributor

#3491 Update test cases for OS Integ Jenkins file
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: seasoned-contributor

#3492 OSD version increment workflow add cron
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3484 Add CCR and security to test manifest
  manifests/2.8.0/opensearch-2.8.0-test.yml
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: repeat-contributor

#3490 Add crane/krane as part of the executable binary in docker-builder image
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
Labels: enhancement, docker, jenkins, distinguished-contributor

#3450 Added Label as name of Release Dockerfile and Note in comments.
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
  docker/release/dockerfiles/opensearch.al2.dockerfile
Labels: CCI, first-time-contributor

#3498 Update Cron time for 1.3.10 release
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#3471 Add async search in 2.8 manifest
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: repeat-contributor

#3501 Release 1.3.10 Add common-utils
  manifests/1.3.10/opensearch-1.3.10.yml
Labels: distinguished-contributor

#3483 Modifying README file
  docker/README.md
Labels: documentation, first-time-contributor

#3504 Update integ-test with 2.8.0
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: seasoned-contributor

#3507 Add maven publish for 1.3.x release
  .codecov.yml
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  publish/publish-snapshot.sh
Labels: distinguished-contributor

#3508 OSD version increment tmp fix for opensearch-dashboards-functional-test
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3509 OSD version increment tmp fix
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3510 OSD version increment tmp fix
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#3511 Remove ml-commons and neural search from 3.0.0
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: distinguished-contributor

#3512 Add ml-commons and security plugin
  manifests/1.3.10/opensearch-1.3.10.yml
Labels: distinguished-contributor, v1.3.10

#3514 [Release 1.3.10] Onboard test manifests and add remaining components
  manifests/1.3.10/opensearch-1.3.10-test.yml
  manifests/1.3.10/opensearch-1.3.10.yml
  manifests/1.3.10/opensearch-dashboards-1.3.10-test.yml
  manifests/1.3.10/opensearch-dashboards-1.3.10.yml
Labels: distinguished-contributor

#3506 [Bug] Fixing not correct path in Readme
  docker/README.md
  docker/ci/README.md
Labels: documentation, CCI, first-time-contributor

#3515 Add opensearch build repo logo image
  README.md
  opensearch_build_image.png
Labels: documentation, enhancement, distinguished-contributor

#3521 Remove SQL plugin from 3.0.0 manifest
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: seasoned-contributor

#3523 Release 1.3.10 commit lock
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  manifests/1.3.10/opensearch-1.3.10.yml
  manifests/1.3.10/opensearch-dashboards-1.3.10.yml
Labels: distinguished-contributor

#3494 Adding dashboards-search-relevance to 2.8 and 2.7.1 manifests
  manifests/2.7.1/opensearch-dashboards-2.7.1.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: first-time-contributor

#3522 Add 1.3.10 and 2.8.0 to Performance Testing
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
Labels: seasoned-contributor

#3525 Resolve securityDashboards not correctly removed on DEB/RPM
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
  src/test_workflow/integ_test/service_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch_dashboards.py
Labels: integtest, release, cicd, docker, rpm, deb, distinguished-contributor, v1.3.10

#3517 Adding DISTRIBUTION_NAME to Promote-Artifacts jenkins job description
  jenkins/promotion/promote-artifacts.jenkinsfile
Labels: documentation, CCI, first-time-contributor

#3528 Update opensearch-2.8.0.yml for PA
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: first-time-contributor

#3530 Update opensearch-2.7.1.yml for PA plugin
  manifests/2.7.1/opensearch-2.7.1.yml
Labels: repeat-contributor

#3529 Add Neural-search to 3.0.0 manifest
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: first-time-contributor

#3532 Consolidated Release Notes 1.3.10
  release-notes/opensearch-release-notes-1.3.10.md
Labels: distinguished-contributor

#3513 Added more outputs to clarify the OpenSearch build script
  scripts/components/OpenSearch/build.sh
Labels: CCI, first-time-contributor

#3536 Update gh package for rockylinux images in stage 1
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
Labels: seasoned-contributor

#3531 Add Geospatial and Dashboards-Maps plugins to 2.8.0 manifest
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: valued-contributor

#3457 Support JDK-20 builds on Jenkins
  docker/ci/config/jdk-setup.sh
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: cicd, docker, jenkins, valued-contributor

#3538 Upgrade jenkins version to 2.387.1
  build.gradle
Labels: distinguished-contributor

#3540 Revert component-based scripts lookup
  src/paths/script_finder.py
  tests/tests_paths/data/git/component_with_scripts_in_component_folder/Component/build.sh
  tests/tests_paths/data/git/component_with_scripts_in_component_folder/Component/bwctest.sh
  tests/tests_paths/data/git/component_with_scripts_in_component_folder/Component/install.sh
  tests/tests_paths/data/git/component_with_scripts_in_component_folder/Component/integtest.sh
  tests/tests_paths/test_script_finder.py
Labels: valued-contributor

#3519 Add jenkinsfile for benchmark job and minor improvements
  jenkins/opensearch/benchmark-test.jenkinsfile
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: all-star-contributor

#3497 Add new base-path parameter to enhance the component yml from test workflow
  src/test_workflow/integ_test/integ_test_runner.py
  src/test_workflow/integ_test/integ_test_suite.py
  src/test_workflow/integ_test/integ_test_suite_opensearch.py
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  src/test_workflow/test_args.py
  src/test_workflow/test_recorder/test_recorder.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_recorder/test_local_cluster_logs.py
  tests/tests_test_workflow/test_recorder/test_test_recorder.py
  tests/tests_test_workflow/test_test_args.py
Labels: distinguished-contributor

#3542 Bump opensearch-build-library version to 4.2.1
  jenkins/opensearch/benchmark-test.jenkinsfile
Labels: all-star-contributor

#3543 Revert 3.0.0 builds to jdk-17
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: distinguished-contributor

#3495 Add docker image sync all tags on Jenkins
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/packer/packer-build.jenkinsfile
  tests/jenkins/TestDockerCopy.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-copy.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/packer/packer-build.jenkinsfile.txt
Labels: enhancement, docker, jenkins, distinguished-contributor

#3551 Add ml-commons-dashboards plugin to 2.8.0 manifest
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: first-time-contributor

#3552 Add node@16.20.0 for build and node@18.16.0 / cypress@12.13.0 for OSD integTest
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/release.centos.clients.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.centos7.performance-test.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: enhancement, integtest, release, docker, jenkins, v2.8.0, distinguished-contributor

#3553 Update the integ tests jenkinsfile to enable base-path parameter
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3558 Make cypress@9.5.4 install from pre-compiled archive
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: enhancement, integtest, release, docker, jenkins, v2.8.0, distinguished-contributor

#3559 Revert #3544 and add a test on actual build images
  .github/workflows/dockerfile-lint.yml
  .github/workflows/groovy-tests.yml
  .github/workflows/python-tests.yml
  .github/workflows/yaml-lint.yml
  Pipfile
  Pipfile.lock
Labels: release, cicd, v2.8.0, distinguished-contributor

#3561 Add ml-commons plugin to 2.8.0 manifest
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: all-star-contributor

#3562 Fix latest URL of OpenSearch passed from the OSD integ test parameter
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: distinguished-contributor

#3563 Remove duplicate plugin in 3.0.0 manifest
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: distinguished-contributor

#3564 Add cron triggers for benchmark-test job
  jenkins/opensearch/benchmark-test.jenkinsfile
Labels: all-star-contributor

#3566 Add notification plugin to 2.8.0 manifest
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: first-time-contributor

#3569 Update ref branch to 2.8 for OpenSearch-Spatial plugins
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: repeat-contributor

#3570 Add IM, Alerting
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: valued-contributor

#3571 Auto bump actions change to 2.8 branch
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: enhancement, release, v2.8.0, distinguished-contributor

#3565 Add dashboards-notification to build manifest
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: first-time-contributor

#3577 Gradle Check disable cron run of Windows temporarily
  jenkins/gradle/gradle-check.jenkinsfile
Labels: bug, windows, jenkins, distinguished-contributor

#3578 feat: remove ml-commons-dashboards experiment keyword in comments
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
Labels: first-time-contributor

#3576 Update cross-cluster-replication branch for 2.8 release
  manifests/2.8.0/opensearch-2.8.0.yml
Labels: repeat-contributor

#3580 Update all plugins in 2.8.0 with 2.8 branch
  manifests/2.8.0/opensearch-2.8.0.yml
  manifests/2.8.0/opensearch-dashboards-2.8.0.yml
Labels: release, v2.8.0, distinguished-contributor

#3584 Add test for benchmark-test jenkinsfile job
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: all-star-contributor

#3585 Update devtoolset to v8 for CentOS7/Node16 upgrade
  docker/ci/config/build-opensearch-dashboards-entrypoint.sh
  docker/ci/config/scl_setup
  docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.centos7.performance-test.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
Labels: release, cicd, docker, jenkins, v2.8.0, distinguished-contributor
