Repository opensearch-project/opensearch-build, pull requests merged in 2023-03, with the labels that each got.

#3274 Add dotnet compilation for arm64 specifically
  docker/ci/dockerfiles/current/release.centos.clients.x64.arm64.dockerfile
Labels: bug, docker, clients

#3294 Increasing build frequence on OSD to be hourly - release 1.3.9
  jenkins/check-for-build.jenkinsfile
Labels: v1.3.9

#3295 Make sure 1.x line is crosscompiling ARM64 on X64 for DEB
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: bug, release, jenkins, v1.3.9

#3301 Adding test manifest yaml for 1.3.9
  manifests/1.3.9/opensearch-1.3.9-test.yml
  manifests/1.3.9/opensearch-dashboards-1.3.9-test.yml
Labels: v1.3.9

#3302 Reducing check-for-build freq to once a day for 1.3.9
  jenkins/check-for-build.jenkinsfile
Labels: v1.3.9

#3285 Support RPM IntegTest runs on Jenkins
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: enhancement, rpm

#3308 Resolve Windows having issue running bash conditional operator
  scripts/components/ganttChartDashboards/build.sh
  scripts/default/opensearch-dashboards/build.sh
Labels: bug, windows, jenkins

#3309 Resolve Windows having issue running bash conditional operator bug 2
  scripts/components/ganttChartDashboards/build.sh
Labels: bug, release, windows, jenkins, v1.3.9

#3313 Update Readme to fix Building Patches section
  README.md
Labels: distinguished-contributor

#3314 Resolve lychee errors in build repo push
  .lychee.excludes
Labels: bug, distinguished-contributor

#3317 Add 2.7 async search in manifest
  manifests/2.7.0/opensearch-2.7.0.yml
Labels: repeat-contributor

#3319 Added consolidated release notes for 1.3.9 release
  release-notes/opensearch-release-notes-1.3.9.md
Labels: release, v1.3.9, seasoned-contributor

#3322 Replace refs with tags for 1.3.9
  manifests/1.3.9/opensearch-1.3.9.yml
  manifests/1.3.9/opensearch-dashboards-1.3.9.yml
Labels: seasoned-contributor

#3321 Add more components to 2.7.0 test manifest
  manifests/2.7.0/opensearch-2.7.0-test.yml
Labels: distinguished-contributor

#3328 Add cypress 5.6.0 for the 1.x releases in integTest images
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
Labels: enhancement, integtest, jenkins, rpm, distinguished-contributor

#3329 Remove snapshot publication script as well as stage from build pipeline
  jenkins/opensearch/distribution-build.jenkinsfile
  publish/publish-snapshot.sh
Labels: distinguished-contributor

#3327 Add 1.3.10 manifest as 1.3.9 is released
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.10/opensearch-1.3.10.yml
  tests/test_run_manifests.py
Labels: release, seasoned-contributor

#3330 Tweak the cypress install order for 5.6.0 version
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
Labels: bug, integtest, jenkins, rpm, distinguished-contributor

#3335 Add test manifest in cron for 3.0.0 and add parameterized cron for 2.7.0
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3337 Add dockerfile linting workflow in GitHub Actions
  .github/workflows/dockerfile-lint.yml
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
Labels: enhancement, feature, test, docker, ci-test-automation, distinguished-contributor

#3336 Install packer in the docker build image
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
Labels: enhancement, docker, distinguished-contributor

#3340 Adding cmake to the systemd ubuntu2004 images for cypress
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: bug, integtest, docker, jenkins, deb, distinguished-contributor

#3344 Add DEB integTest support on Jenkins
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: enhancement, integtest, cicd, jenkins, deb, distinguished-contributor

#3346 Add additional test manifest with segment replication enabled
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.7.0/opensearch-2.7.0-segment-replication-test.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#3347 Make distribution build call sync with latest integ-test changes
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: enhancement, integtest, cicd, jenkins, rpm, deb, distinguished-contributor

#3348 Add dashboards manifests for 2.7.0 and 1.3.10
  .github/workflows/increment-plugin-versions.yml
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.10/opensearch-dashboards-1.3.10.yml
  manifests/2.7.0/opensearch-dashboards-2.7.0.yml
Labels: distinguished-contributor

#3352 Increase the build frequency for 2.7.0
  jenkins/check-for-build.jenkinsfile
Labels: release, v2.7.0, distinguished-contributor

#3354 Removing v1.3.8 out of perf test
  jenkins/opensearch/perf-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/perf-test.jenkinsfile.txt
Labels: seasoned-contributor

#3359 Make OSD docker to use OpenSearch as vendor like OS docker
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
Labels: docker, distinguished-contributor
