Repository opensearch-project/opensearch-build, pull requests merged in 2024-09, with the labels that each got.

#4987 Onboard opensearch-system-templates plugin for opensearch build
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/os-release-issues.yml
  manifests/2.17.0/opensearch-2.17.0-test.yml
  manifests/2.17.0/opensearch-2.17.0.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: first-time-contributor, manifest-ci-check

#4988 Increase build frequency for 2.17
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor, manifest-ci-check

#4984 Upgrade library version to fix CVEs
  build.gradle
Labels: distinguished-contributor

#4989 Switch to 2.17 release branch
  manifests/2.17.0/opensearch-2.17.0.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4992 Increase concurrent jobs limit to 30 for gradle-check
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4985 Update the clients release docker image to AlmaLinux 8
  docker/ci/dockerfiles/current/release.almalinux8.clients.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/release.centos7.clients.x64.arm64.dockerfile
Labels: first-time-contributor

#4993 Update gradle-check script to wait for workflow_url to be ready
  scripts/gradle/gradle-check.sh
Labels: enhancement, cicd, jenkins, distinguished-contributor

#4996 Stop auto-builds for 2.17
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4999 Add sleep for few seconds to ensure the container process are properly started - Part 2
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: distinguished-contributor

#5002 Add cluster config for opensearch-system-templates test
  manifests/2.17.0/opensearch-2.17.0-test.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
Labels: first-time-contributor

#5001 Add test_stdout and test_stderr path/url for test-report.yml
  pyproject.toml
  src/manifests/test_report_manifest.py
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/test_test_report_runner.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, jenkins, distinguished-contributor

#5007 Add workspace.enabled param as 2.x/default osd entrypoint
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: enhancement, docker, distinguished-contributor, v2.17.0

#5009 Update commits for RC3
  manifests/2.17.0/opensearch-2.17.0.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
Labels: distinguished-contributor, manifest-ci-check

#5011 Bump opensearch-benchmark docker version to 1.9.0
  src/test_workflow/benchmark_test/benchmark_test_suite_compare.py
  src/test_workflow/benchmark_test/benchmark_test_suite_execute.py
  tests/test_run_compare.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite_compare.py
Labels: distinguished-contributor

#5013 Update commits for RC4
  manifests/2.17.0/opensearch-2.17.0.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
Labels: distinguished-contributor, manifest-ci-check

#5012 Revert "Bump opensearch-benchmark docker version to 1.9.0"
  src/test_workflow/benchmark_test/benchmark_test_suite_compare.py
  src/test_workflow/benchmark_test/benchmark_test_suite_execute.py
  tests/test_run_compare.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite_compare.py
Labels: distinguished-contributor

#5014 Update commits for indexManagementDashboards
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
Labels: distinguished-contributor, manifest-ci-check

#5006 Add meta and signature validation to RPM dist in Validation workflow
  src/validation_workflow/rpm/validation_rpm.py
  tests/tests_validation_workflow/test_validation_rpm.py
Labels: distinguished-contributor

#5024 Update folder structure for release notes
  jenkins/release-workflows/release-notes-check.jenkinsfile
  tests/jenkins/TestReleaseNotesCheckAndCompile.groovy
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-compile.jenkinsfile.txt
Labels: distinguished-contributor

#5025 Update commits for RC7
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
Labels: distinguished-contributor, manifest-ci-check

#5026 Refresh snapshot benchmarks to use snapshot created on 2.16 version
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5027 Add component repository key value pair to report yml
  src/manifests/test_report_manifest.py
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/test_test_report_runner.py
  tests/tests_report_workflow/test_test_report_runner_dashboards.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, Build Libraries & Interfaces, distinguished-contributor

#5030 Add mend scan to foundation-website repo
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor, scanning

#5032 Update to 6.9.1 which adds new fields to integration test and distribution build documents
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5034 Fix release version page hyperlink
  release-notes/opensearch-release-notes-2.17.0.md
Labels: distinguished-contributor

#5036 Add workflow to publish release on GitHub
  .github/workflows/publish-release.yml
Labels: distinguished-contributor

#5039 Update the build documentation and remove duplicates
  README.md
  docs/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution.md
Labels: distinguished-contributor

#5040 Remove rpm-validation jenkins job in build repo
  docs/Releasing-the-Distribution.md
  jenkins/legacy/rpm-validation.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5041 Update big5 runs to use ordered data snapshots
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5043 Add new stage in gradle-check to check and abort stale runs
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#5044 Fix position of abort stale job script in gradle-check
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#5031 Refactor release issue template and release wiki based on new changes
  .github/ISSUE_TEMPLATE/release_template.md
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#5050 Remove 2.17.1 builds
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor, v2.17.1

#5052 onboard skills repo to 3.0.0
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: first-time-contributor, manifest-ci-check

#5056 Added automation-app to whitesource config
  tools/vulnerability-scan/wss-scan.config
Labels: repeat-contributor

#5064 Refresh nightly runs to track 2.18 version
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor
