Repository opensearch-project/opensearch-build, pull requests merged in 2024-05, with the labels that each got.

#4666 Add Dashboards var for UI Metric Collectors
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: first-time-contributor

#4673 Fix the bundle_artifact_path value and remove wrong comments for deb assemble
  src/assemble_workflow/bundle_linux_deb.py
Labels: bug, Build Libraries & Interfaces, deb, distinguished-contributor

#4677 update OS commit ids for 2.14 release
  manifests/2.14.0/opensearch-2.14.0.yml
Labels: distinguished-contributor

#4678 update OSD commit ids for 2.14 release
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
Labels: distinguished-contributor

#4679 Update manifest lock `COMPONENTS` parameter description
  jenkins/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile
Labels: distinguished-contributor

#4680 Update manifest lock COMPONENTS parameter description
  jenkins/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile
Labels: distinguished-contributor

#4664 Validation for OS and OSD fail with error when executed multiple times on local
  src/run_validation.py
  src/validation_workflow/deb/validation_deb.py
  src/validation_workflow/docker/validation_docker.py
  src/validation_workflow/rpm/validation_rpm.py
  src/validation_workflow/tar/validation_tar.py
  src/validation_workflow/validation.py
  src/validation_workflow/validation_test_runner.py
  src/validation_workflow/yum/validation_yum.py
  src/validation_workflow/zip/validation_zip.py
  tests/tests_validation_workflow/test_validation.py
  tests/tests_validation_workflow/test_validation_deb.py
  tests/tests_validation_workflow/test_validation_docker.py
  tests/tests_validation_workflow/test_validation_rpm.py
  tests/tests_validation_workflow/test_validation_tar.py
  tests/tests_validation_workflow/test_validation_test_runner.py
  tests/tests_validation_workflow/test_validation_yum.py
  tests/tests_validation_workflow/test_validation_zip.py
Labels: distinguished-contributor

#4490 Add OpenSearch Project Build System Quick Overview Wiki Page
  docs/OpenSearch-Project-Build-System-Quick-Overview.md
  docs/images/2-1-1-flow.png
  docs/images/2-1-2-flow.png
  docs/images/2-1-3-benchmark-page.png
  docs/images/2-1-3-flow.png
  docs/images/2-1-4-flow.png
  docs/images/2-1-4-gradle-check-fail.png
  docs/images/2-1-4-gradle-check-success.png
  docs/images/2-1-4-gradle-check-unstable.png
  docs/images/2-1-5-flow.png
Labels: documentation, cicd, jenkins, distinguished-contributor

#4688 Update wiki home page with OpenSearch-Project-Build-System-Quick-Overview.md
  docs/Home.md
Labels: documentation, distinguished-contributor

#4689 Adding footer and sidebar for build repo wiki
  docs/Home.md
  docs/_Footer.md
  docs/_Sidebar.md
Labels: documentation, distinguished-contributor

#4692 Switch linux OSD to use electron for 2.14.0 cypress test
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
Labels: integtest, test, release, docker, ci-test-automation, distinguished-contributor, v2.14.0

#4697 Use 2.14 ref for FTR
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
Labels: distinguished-contributor

#4699 Change functional test repo ref to release branch
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
Labels: distinguished-contributor

#4686 [Benchmark] Add mechanism to retreive the logs from test-execution.json
  Pipfile
  Pipfile.lock
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/jenkins/TestRunBenchmarkTestEndpoint.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4701 Exclude `functionalTestDashboards` repo in manifest lock
  jenkins/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile
  tests/jenkins/TestReleaseManifestCommitLock.groovy
  tests/jenkins/data/opensearch-dashboards-3.0.0.yml
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testUpdateToRecentCommit_excludeFTRepo.txt
Labels: distinguished-contributor

#4702 [OSD][2.14] add additional cluster configs
  manifests/2.14.0/opensearch-dashboards-2.14.0-test.yml
Labels: distinguished-contributor

#4703 Add new configurations for concurrent search runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4704 Update OSD commit on 2.14
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
Labels: distinguished-contributor

#4707 Added release notes for 2.14.0 release
  release-notes/opensearch-release-notes-2.14.0.md
Labels: distinguished-contributor

#4705 Update gradle publish to handle invokeType
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4706 Add 2.15.0 OpenSearch Dashboards manifest
  jenkins/check-for-build.jenkinsfile
  manifests/2.15.0/opensearch-dashboards-2.15.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4709 upgrade nightly benchmarks distribution version
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4710 Gradle check bug replace `pr_title` with `pullRequestTitle`
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4694 docker: start opensearch with exec for graceful termination
  docker/release/config/opensearch/opensearch-docker-entrypoint-1.x.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint-2.x.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint-default.x.sh
Labels: first-time-contributor

#4713 Add default baseline runs for r5.8xlarge runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4716 Updating security reachout email
  README.md
Labels: first-time-contributor

#4714 Adding AL2 image to support knnlib builds
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: enhancement, release, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, v2.15.0

#4719 Jenkinsfile update for Gradle Check Publish Optimization
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4721 Gradle Check Optimization: Update gradle check bash script
  scripts/gradle/gradle-check.sh
Labels: distinguished-contributor

#4722 Update al2 dockerfile for knn build
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: valued-contributor

#4724 Update repo promotion to use lib 6.7.4
  jenkins/promotion/promote-repos.jenkinsfile
Labels: enhancement, cicd, jenkins, Build Libraries & Interfaces, deb, distinguished-contributor

#4725 Set target_throughput to none for NYC taxis nightly benchmarks
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: first-time-contributor

#4727 Explicitly set up CXX env for knn in AL2 build env
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: valued-contributor

#4729 Remove macos platform for OSD builds
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4728 Remove maintainer access for @bbarani @jordarlu on build repo
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: valued-contributor

#4732 Add test manifests for 1.3.17 and update cron
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.17/opensearch-1.3.17-test.yml
  manifests/1.3.17/opensearch-dashboards-1.3.17-test.yml
Labels: distinguished-contributor

#4733 Setup a nightly runs for semantic search at noaa workload.
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4734 Move jordarlu to emertius section
  .github/workflows/automatic-merges.yml
  MAINTAINERS.md
Labels: distinguished-contributor

#4735 Update openblas source version and gfortran path in AL2 build
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: seasoned-contributor

#4738 Switch from CentOS7 to AL2 for 2.15.0
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.15.0/opensearch-2.15.0.yml
Labels: release, docker, distinguished-contributor, v2.15.0

#4740 Remove cron for 1.3.17
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4741 Update the gradle-check.jenkinsfile library version to 6.4.8
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4742 Lock commits for 1.3.17
  manifests/1.3.17/opensearch-1.3.17.yml
  manifests/1.3.17/opensearch-dashboards-1.3.17.yml
Labels: distinguished-contributor, manifest-ci-check
