Repository opensearch-project/opensearch-build, pull requests merged in 2024-02, with the labels that each got.

#4394 [Release 2.12.0] Update 2.12.0 build frequency
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4393 Switch docker re-release to use 6.2.0 lib in jenkinsfile
  jenkins/docker/docker-re-release.jenkinsfile
  tests/jenkins/TestDockerReRelease.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-re-release.jenkinsfile.txt
Labels: enhancement, cicd, docker, jenkins, dependencies, Build Libraries & Interfaces, distinguished-contributor

#4395 Updates Docker release README to reflect admin password requirements
  docker/release/README.md
Labels: seasoned-contributor

#4397 Adds doc website link in the message printed for custom admin password requirement
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
  scripts/pkg/build_templates/opensearch/deb/debian/preinst
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
  scripts/startup/tar/linux/opensearch-tar-install.sh
  scripts/startup/zip/windows/opensearch-windows-install.bat
Labels: seasoned-contributor

#4398 Update the build library tag for distribution build jobs
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4403 Pass in cred to admin credentials based on version to alerting integtest
  scripts/components/alerting/integtest.sh
Labels: valued-contributor

#4375 remove sub working directory for gantt-chart
  .github/workflows/osd-increment-plugin-versions.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  scripts/components/ganttChartDashboards/build.sh
Labels: seasoned-contributor

#4409 Windows integTest fix for 2.12 with admin:admin security changes
  src/test_workflow/integ_test/distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
Labels: bug, integtest, test, release, cicd, docker, windows, ci-test-automation, jenkins, distinguished-contributor, v2.12.0

#4402 feat: remove useless config
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
  manifests/2.12.0/opensearch-dashboards-2.12.0-test.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
Labels: repeat-contributor

#4400 Enable label handling for integ-test workflows
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4414 [Release 2.12.0] Update 2.12.0 manifests to release branch
  jenkins/check-for-build.jenkinsfile
  manifests/2.12.0/opensearch-2.12.0.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
Labels: distinguished-contributor

#4408 Update the 3.0.0 manifest to schema 1.1 with depends_on
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  tests/tests_manifests/test_input_manifests.py
Labels: distinguished-contributor

#4415 Disable remote cluster test settings added in 998 PR of ftrepo
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/.test_integ_test_suite_opensearch_dashboards.py.swp
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch_dashboards.py
Labels: bug, integtest, test, release, cicd, ci-test-automation, jenkins, v2.12.0

#4412 Add zstd and zstd_no_dict codec runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4418 Update Jenkinsfiles to reduce cron builds
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4417 Install fonts on windows docker image for chromium-based browser and lock docker version
  docker/ci/config/windows-servercore-setup.ps1
Labels: bug, integtest, test, release, cicd, docker, windows, ci-test-automation, jenkins, distinguished-contributor, v2.12.0

#4420 Enable issue notification and labelling for all distributions
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4419 Switch ftrepo checkout based on ref instead of commit_id
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/data/build_manifest_osd.yml
  tests/tests_test_workflow/test_integ_workflow/integ_test/data/bundle_manifest_osd.yml
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch_dashboards.py
Labels: enhancement, integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.12.0

#4422 Disable testing for 3.0.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4426 Upgrade node version to 18.19.0 in sync with OSD core
  docker/ci/config/windows-servercore-setup.ps1
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: cicd, docker, distinguished-contributor, maintenance

#4429 Add 2.13.0 manifests
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
  jenkins/check-for-build.jenkinsfile
  manifests/2.13.0/opensearch-2.13.0-test.yml
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0-test.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: seasoned-contributor

#4431 Update the template manifest for manifest workflow
  manifests/templates/opensearch-dashboards/2.x/manifest.yml
  manifests/templates/opensearch-dashboards/3.x/manifest.yml
  manifests/templates/opensearch-dashboards/default/manifest.yml
  manifests/templates/opensearch/2.x/manifest.yml
  manifests/templates/opensearch/3.x/manifest.yml
  manifests/templates/opensearch/default/manifest.yml
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: distinguished-contributor

#4434 Add publishToMavenLocal in default script
  scripts/default/opensearch/build.sh
Labels: first-time-contributor

#4436 Remove publishToMavenLocal from default build scripts
  scripts/default/opensearch/build.sh
Labels: distinguished-contributor

#4440 Disable incremental build for 2.12.0 release
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4377 Add option to validate with/without security and new password for latest versions
  src/test_workflow/integ_test/utils.py
  src/validation_workflow/api_request.py
  src/validation_workflow/api_test_cases.py
  src/validation_workflow/docker/validation_docker.py
  src/validation_workflow/rpm/validation_rpm.py
  src/validation_workflow/tar/validation_tar.py
  src/validation_workflow/validation.py
  src/validation_workflow/validation_args.py
  src/validation_workflow/yum/validation_yum.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_utils.py
  tests/tests_validation_workflow/test_api_request.py
  tests/tests_validation_workflow/test_api_test_cases.py
  tests/tests_validation_workflow/test_validation.py
  tests/tests_validation_workflow/test_validation_args.py
  tests/tests_validation_workflow/test_validation_docker.py
  tests/tests_validation_workflow/test_validation_rpm.py
  tests/tests_validation_workflow/test_validation_tar.py
  tests/tests_validation_workflow/test_validation_yum.py
Labels: distinguished-contributor

#4437 Change publishToMavenLocal to publishPluginToMavenLocal only
  scripts/default/opensearch/build.sh
Labels: first-time-contributor

#4443 [Release 2.12.0] Disable 2.12.0 auto runs
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4449 Remove the concurrent search experimental flags from manifest
  manifests/2.12.0/opensearch-2.12.0-concurrent-search-test.yml
Labels: first-time-contributor

#4446 [Docker] Fixes security enabled logic to execute demo config only if security plugin is enabled
  docker/release/README.md
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
Labels: seasoned-contributor

#4448 Schedule new nightly runs for concurrent search
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4450 Fixes docker release README
  docker/release/README.md
Labels: seasoned-contributor

#4453 Removes check to validate presence of `OPENSEARCH_INITIAL_ADMIN_PASSWORD` variable from preinst script of DEB distribution
  scripts/components/OpenSearch/install.sh
  scripts/pkg/build_templates/opensearch/deb/debian/preinst
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: seasoned-contributor

#4452 Properly separate 1.x/2.x/default opensearch docker entrypoint like in opensearch-dashboards
  docker/release/README.md
  docker/release/config/opensearch/opensearch-docker-entrypoint-1.x.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint-2.x.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint-default.x.sh
  docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile
  docker/release/dockerfiles/opensearch.al2.dockerfile
  docker/release/dockerfiles/opensearch.al2023.dockerfile
Labels: bug, enhancement, release, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, v2.12.0

#4456 Fix typo in benchmark run
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4457 Remove BROWSER_PATH=electron for Windows so integTest can run chromium114
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
Labels: bug, enhancement, integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.12.0

#4460 [Release 2.12.0] RC commit lock
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.12.0/opensearch-2.12.0.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4463 [Release 2.12.0] Consolidated release notes
  release-notes/opensearch-release-notes-2.12.0.md
Labels: distinguished-contributor

#4465 Update nightly benchmark jobs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4467 [Release 2.12.0] Update the ref to 2.12.0 tag
  manifests/2.12.0/opensearch-2.12.0.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
Labels: distinguished-contributor

#4438 Update integ test runner to record each configuration separately
  src/test_workflow/integ_test/integ_test_runner.py
  src/test_workflow/integ_test/integ_test_suite_opensearch.py
  src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py
  src/test_workflow/test_recorder/test_recorder.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch_dashboards.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch.py
  tests/tests_test_workflow/test_recorder/test_test_recorder.py
Labels: distinguished-contributor

#4470 Fix `choice` parameter bug in central promotion workflow
  jenkins/promotion/release-promotion.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor

#4305 Adding a retry logic when the API call was failed on Gradle-check
  scripts/gradle/gradle-check.sh
Labels: all-star-contributor

#4473 Update jenkinsjob for Validation Workflow
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  tests/jenkins/TestValidateArtifacts.groovy
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: distinguished-contributor

#4479 Remove 2.8-2.11 auto incremental version bump
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: release, distinguished-contributor, maintenance

#4480 Remove chromium installation as it is installed in opensearch-project/opensearch-dashboards-functional-test#1123
  docker/ci/config/windows-servercore-setup.ps1
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: integtest, test, cicd, docker, ci-test-automation, jenkins, distinguished-contributor

#4482 Updated benchmark runs for concurrent search
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4484 Remove nightly runs for pmc workload
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4458 Switch windows/servercore to windows image as base to resolve multiple lib missing issues
  docker/ci/config/legacy/windows-servercore-setup.ps1
  docker/ci/config/windows-setup.ps1
  docker/ci/dockerfiles/current/build.windows2019.x64.dockerfile
  docker/ci/dockerfiles/legacy/build.windows2019.servercore.x64.dockerfile
Labels: bug, integtest, test, cicd, docker, windows, ci-test-automation, distinguished-contributor

#4477 Adding components to 1.3.15 and update to hourly build
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  manifests/1.3.15/opensearch-1.3.15.yml
  manifests/1.3.15/opensearch-dashboards-1.3.15.yml
Labels: release, all-star-contributor, v1.3.15

#4486 Adding more components and test yaml
  manifests/1.3.15/opensearch-1.3.15-test.yml
  manifests/1.3.15/opensearch-1.3.15.yml
  manifests/1.3.15/opensearch-dashboards-1.3.15-test.yml
Labels: all-star-contributor

#4488 Udpate OSD manifest schema to 1.1
  manifests/1.3.15/opensearch-dashboards-1.3.15.yml
Labels: all-star-contributor
