Repository opensearch-project/opensearch-build, pull requests merged in 2024-07, with the labels that each got.

#4809 Re-switch centos7 to AL2 for 2.16.0 test
  .github/workflows/get-ci-image-tag.yml
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.15.0/opensearch-2.15.0.yml
Labels: integtest, test, release, cicd, docker, ci-test-automation, jenkins, distinguished-contributor, v2.16.0

#4811 Add bwc.checkout.align parameter support in gradle-check
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4807 [BENCHMARK] Save test_execution.json to the workspace
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4818 [BENCHMARK] Copy the contents from sub-directory test_executions
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4820 Move CentOS7 build image to legacy
  docker/ci/dockerfiles/legacy/build.centos7.opensearch.x64.arm64.ppc64le.dockerfile
Labels: cicd, docker, jenkins, distinguished-contributor

#4822 Bump up cmake version to 3.26.4
  .github/workflows/python-tests.yml
  docker/ci/config/windows-setup.ps1
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
Labels: valued-contributor

#4827 Switch from C54xlarge Windows Docker Builder to M54xlarge and lock public_suffix to 5.1.1 on almalinux OSD image
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  jenkins/docker/docker-build.jenkinsfile
Labels: cicd, docker, jenkins, distinguished-contributor

#4830 Add test manifests for 1.3.18 and increase build frequency
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.18/opensearch-1.3.18-test.yml
  manifests/1.3.18/opensearch-dashboards-1.3.18-test.yml
Labels: distinguished-contributor, manifest-ci-check

#4824 Add estimate for plugin onboarding
  .github/ISSUE_TEMPLATE/plugin_onboarding_template.yaml
  ONBOARDING.md
Labels: distinguished-contributor

#4831 Add new jenkins job for benchmarking pull request
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request.jenkinsfile.txt
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4833 Remove cron job for building 1.3.18
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4835 copy benchmark results file to local for nightly runs as well
  src/test_workflow/benchmark_test/benchmark_test_suite.py
Labels: distinguished-contributor

#4836 copy benchmark restuls only for cluster_endpoint or distribution_url …
  src/test_workflow/benchmark_test/benchmark_test_suite.py
Labels: distinguished-contributor

#4839 Run benchmark-pull-request on single agent and other bug-fixes.
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#4840 Add nightly runs for 2.7 and 2.11
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4468 Add single version loose param for building plugins
  .github/workflows/osd-increment-plugin-versions.yml
Labels: valued-contributor

#4849 Automate retrospective issue creation
  .github/ISSUE_TEMPLATE/release_retrospective_template.md
  .github/workflows/releases.yml
Labels: distinguished-contributor

#4850 Add consolidated release notes for 1.3.18
  release-notes/opensearch-release-notes-1.3.18.md
Labels: distinguished-contributor

#4853 [Release 2.16.0] Increase the build frequency and onboard the test manifests.
  jenkins/check-for-build.jenkinsfile
  manifests/2.16.0/opensearch-2.16.0-test.yml
  manifests/2.16.0/opensearch-dashboards-2.16.0-test.yml
Labels: distinguished-contributor

#4846 Add script similar to gradle-check to invoke benchmark-pull-request job from github actions workflow
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  scripts/benchmark/benchmark-pull-request.sh
  tests/jenkins/TestBenchmarkPullRequest.groovy
Labels: distinguished-contributor

#4858 Switch 2.16.0 manifest to use al2 docker images
  manifests/2.16.0/opensearch-2.16.0.yml
Labels: release, cicd, distinguished-contributor, manifest-ci-check, v2.16.0

#4854 Update the release tag for 1.3.18
  manifests/1.3.18/opensearch-1.3.18.yml
  manifests/1.3.18/opensearch-dashboards-1.3.18.yml
Labels: distinguished-contributor, manifest-ci-check

#4860 Fix validation workflow params in central release workflow
  jenkins/promotion/release-promotion.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor

#4861 Onboard query-insights in 2.16
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/os-release-issues.yml
  manifests/2.16.0/opensearch-2.16.0.yml
  tools/vulnerability-scan/wss-scan.config
Labels: first-time-contributor, manifest-ci-check

#4862 [Release 2.16.0] Add alerting and job-scheduler dependency for security-analytics
  manifests/2.16.0/opensearch-2.16.0.yml
Labels: distinguished-contributor

#4863 Add macos arm64 min artifact builds to Jenkins
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-darwin-arm64-build-manifest.yml
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-darwin-x64-build-manifest.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: enhancement, cicd, macos, jenkins, distributions, Build Libraries & Interfaces, distinguished-contributor

#4852 Add dashboards-flow-framework to build repo
  .github/workflows/osd-increment-plugin-versions.yml
  .github/workflows/osd-release-issues.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  tools/vulnerability-scan/wss-scan.config
Labels: first-time-contributor

#4866 Bump publish min artifacts to use 6.6.1 libs
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: enhancement, cicd, macos, jenkins, distributions, Build Libraries & Interfaces, distinguished-contributor

#4865 Bump maven publish 1.x cron to 1.3.19 and switch docker copy agent to avoid cache cleaning race condition
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
Labels: cicd, docker, jenkins, distinguished-contributor

#4867 Avoid checking outdated branches during manifest update
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch_dashboards.py
Labels: enhancement, cicd, Build Libraries & Interfaces, distinguished-contributor

#4871 Improve logic of finding legacy branches to ignore manifest update
  src/manifests_workflow/input_manifests.py
Labels: enhancement, cicd, Build Libraries & Interfaces, distinguished-contributor

#4873 [Release 2.16.0] Update ref to 2.16
  jenkins/check-for-build.jenkinsfile
  manifests/2.16.0/opensearch-2.16.0.yml
  manifests/2.16.0/opensearch-dashboards-2.16.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4874 Trigger manifest lock workflow from release Tag workflow
  jenkins/release-tag/release-tag.jenkinsfile
Labels: distinguished-contributor

#4875 Add query-insights to test manifest
  manifests/2.16.0/opensearch-2.16.0-test.yml
Labels: first-time-contributor, manifest-ci-check

#4876 Update Integration and Build Jenkinsfile to add the publish library.
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4877 Use the build `RC_NUMBER` value for integration test build.
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4878 Reduce from 180 to 90 days for gradle check log rotation
  jenkins/gradle/gradle-check.jenkinsfile
Labels: enhancement, test, cicd, jenkins, Build Libraries & Interfaces, distinguished-contributor

#4881 Disable 2.16.0 cron on distribution build workflow
  jenkins/check-for-build.jenkinsfile
Labels: enhancement, release, distinguished-contributor, v2.16.0

#4879 Add release notes generation action
  jenkins/release-notes-check/release-notes-check.jenkinsfile
  tests/jenkins/TestReleaseNotesCheck.groovy
  tests/jenkins/TestReleaseNotesCheckAndCompile.groovy
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-compile.jenkinsfile.txt
Labels: distinguished-contributor

#4882 Move all release jenkins workflows under one folder
  jenkins/release-workflows/release-branch.jenkinsfile
  jenkins/release-workflows/release-manifest-commit-lock.jenkinsfile
  jenkins/release-workflows/release-notes-check.jenkinsfile
  jenkins/release-workflows/release-promotion.jenkinsfile
  jenkins/release-workflows/release-tag.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/TestReleaseBranch.groovy
  tests/jenkins/TestReleaseManifestCommitLock.groovy
  tests/jenkins/TestReleaseNotesCheckAndCompile.groovy
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-tag/release-tag-dashboards.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-tag/release-tag.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-branch-buildmanifest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-branch-inputmanifest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-check.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-compile.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-promotion.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_createPullRequest.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_matchBuildManifest.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_updateToRecentCommits.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_updateToTags.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testMatchBuildManifest.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testUpdateToRecentCommit.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testUpdateToRecentCommit_excludeFTRepo.txt
Labels: distinguished-contributor

#4883 Fix release notes checker workflow
  jenkins/release-workflows/release-notes-check.jenkinsfile
Labels: distinguished-contributor

#4884 Add nightly benchmark for OS-1.3.18
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4885 Bug fixes in `publishDistributionBuildResults` and `publishIntegTestResults`
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4891 Update OSD integ test file to fix the bug `Failed to extract test-report-<>.tar.gz`
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4892 Update OSD integ test file to fix the bug `hudson.AbortException: script returned exit code 23`
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4896 OS and OSD Integration and build Jenkinsfile library Update to `6.7.2`
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor
