Repository opensearch-project/opensearch-build, pull requests merged in 2024-03, with the labels that each got.

#4487 Add big5 workload to nightly benchmark runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4491 Update OpenSearch input manifest
  manifests/1.3.15/opensearch-1.3.15.yml
Labels: distinguished-contributor

#4494 fix missing quotes
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4496 Removing 1.3.15 hourly check-for-build
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4497 Fix opensearch-dashboards-functional-test version increment
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#4498 Lock in commit Id
  manifests/1.3.15/opensearch-1.3.15.yml
  manifests/1.3.15/opensearch-dashboards-1.3.15.yml
Labels: distinguished-contributor

#4503 Fix opensearch-dashboards-functional-test version increment update with unique `id`.
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#4499 Adding consolidation release-notes
  release-notes/opensearch-release-notes-1.3.15.md
Labels: distinguished-contributor

#4508 Ensure that artifact url is valid for Windows dist manifest
  src/assemble_workflow/bundle_url_location.py
  tests/tests_assemble_workflow/test_bundle_url_location.py
Labels: bug, windows, Build Libraries & Interfaces, distinguished-contributor

#4509 Add noaa workload for concurrent search
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4502 Using tags for Ref in 1.3.15 manifest
  manifests/1.3.15/opensearch-1.3.15.yml
  manifests/1.3.15/opensearch-dashboards-1.3.15.yml
Labels: distinguished-contributor

#4511 Switch all rockylinux8 images to almalinux8 to support ppc64le
  docker/ci/config/gcc-toolset-9-setup
  docker/ci/config/windows-setup.ps1
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/build.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/legacy/test.rockylinux8.systemd-base.x64.arm64.dockerfile
Labels: cicd, docker, distinguished-contributor

#4514 Resolve almalinux8/ubuntu2004 build image ppc64le compatibility issues
  docker/ci/config/gh-setup.sh
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
Labels: bug, enhancement, cicd, docker, distinguished-contributor, ppc64le

#4516 Add architecture param to support multiple arch selections
  docker/ci/build-image-multi-arch.sh
  jenkins/docker/docker-build.jenkinsfile
Labels: enhancement, docker, distinguished-contributor, ppc64le

#4517 Resolve almalinux8/ubuntu2004 build image ppc64le compatibility issues (part 2)
  docker/ci/config/windows-setup.ps1
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
Labels: bug, enhancement, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, ppc64le

#4519 Rename some ci dockerfiles to include ppc64le arch
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
Labels: enhancement, docker, distinguished-contributor, ppc64le

#4518 Add r5.8x runs for concurrent-search and remove lucene vectorsearch run
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4520 Add jenkins job to automate release branch creation during releases
  jenkins/release-branch/release-branch.jenkinsfile
  tests/jenkins/TestReleaseBranch.groovy
  tests/jenkins/jenkinsjob-regression-files/release-branch/release-branch-buildmanifest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-branch/release-branch-inputmanifest.jenkinsfile.txt
Labels: distinguished-contributor

#4521 Run aggs test-procedure for noaa workload
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4523 Generate new input manifest with previous latest version
  src/manifests_workflow/README.md
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/data/opensearch-2.12.1000.yml
  tests/tests_manifests_workflow/data/opensearch-dashboards-2.12.1000.yml
  tests/tests_manifests_workflow/test_input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch_dashboards.py
Labels: enhancement, Build Libraries & Interfaces, distinguished-contributor

#4526 Revert "[AUTO] Update input manifests (#4522)" to rerun the generation from #4523
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.16/opensearch-1.3.16.yml
Labels: enhancement, distinguished-contributor

#4535 Update CI image name to be with v3 on OpenSearch 1.4.0 manifest
  manifests/1.4.0/opensearch-1.4.0.yml
Labels: distinguished-contributor

#4043 [Resume] Improve ownership and permissions of files in OpenSearch/Dashboards deb and rpm packages
  scripts/pkg/build_templates/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/opensearch-dashboards/deb/debmake_opensearch_dashboards_install.sh
  scripts/pkg/build_templates/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/opensearch/deb/debmake_opensearch_install.sh
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: enhancement, release, rpm, deb, distinguished-contributor, v2.13.0

#4534 Support new deb/rpm permissions changes in #4043 on integTest
  src/test_workflow/integ_test/distribution.py
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  src/test_workflow/integ_test/distribution_tar.py
  src/test_workflow/integ_test/distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_tar.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
Labels: integtest, test, release, cicd, ci-test-automation, rpm, deb, distinguished-contributor, v2.13.0

#4536 Allow 1.x deb/rpm to use the old build templates
  scripts/components/OpenSearch-Dashboards/install.sh
  scripts/components/OpenSearch/install.sh
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/Makefile
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/control
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/copyright
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/preinst
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/prerm
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/rules
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debmake_opensearch_dashboards_install.sh
  scripts/pkg/build_templates/current/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/current/opensearch/deb/Makefile
  scripts/pkg/build_templates/current/opensearch/deb/debian/control
  scripts/pkg/build_templates/current/opensearch/deb/debian/copyright
  scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch/deb/debian/preinst
  scripts/pkg/build_templates/current/opensearch/deb/debian/prerm
  scripts/pkg/build_templates/current/opensearch/deb/debian/rules
  scripts/pkg/build_templates/current/opensearch/deb/debmake_opensearch_install.sh
  scripts/pkg/build_templates/current/opensearch/rpm/opensearch.rpm.spec
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/Makefile
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/control
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/copyright
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/preinst
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/prerm
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/rules
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debmake_opensearch_dashboards_install.sh
  scripts/pkg/build_templates/legacy/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/legacy/opensearch/deb/Makefile
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/control
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/copyright
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/preinst
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/prerm
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/rules
  scripts/pkg/build_templates/legacy/opensearch/deb/debmake_opensearch_install.sh
  scripts/pkg/build_templates/legacy/opensearch/rpm/opensearch.rpm.spec
Labels: enhancement, release, rpm, Build Libraries & Interfaces, deb, distinguished-contributor, v2.13.0

#4530 Automatic Service Restart (Debian)
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
Labels: release, deb, first-time-contributor, v2.13.0

#4539 Fix the incorrect location of pkg build_templates
  scripts/components/OpenSearch-Dashboards/install.sh
  scripts/components/OpenSearch/install.sh
Labels: bug, release, cicd, rpm, Build Libraries & Interfaces, deb, distinguished-contributor, v2.13.0

#4540 Updating Gradle_check API retry frequency
  scripts/gradle/gradle-check.sh
Labels: distinguished-contributor

#4542 Remove prein check in rpm to be consistent with deb pkg
  scripts/pkg/build_templates/current/opensearch/rpm/opensearch.rpm.spec
Labels: bug, release, cicd, rpm, Build Libraries & Interfaces, distinguished-contributor, v2.13.0

#4543 Remove vectorsearch cohere-10m workload runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4544 Enable integration testing for 2.13
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4546 Update 2.13.0 deb/rpm package permission change notice
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch/rpm/opensearch.rpm.spec
Labels: documentation, release, rpm, distributions, Build Libraries & Interfaces, deb, distinguished-contributor, v2.13.0

#4547 Update workload params for vectorsearch cohere-1m corpus runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4538 Switch components branches to 2.13 for release
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor

#4548 Allow current user to join os/osd group during deb/rpm test
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/legacy/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
Labels: enhancement, integtest, test, release, cicd, ci-test-automation, rpm, Build Libraries & Interfaces, deb, distinguished-contributor, v2.13.0

#4553 Add current user to adm group to access logs
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/legacy/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
Labels: enhancement, integtest, test, release, cicd, docker, ci-test-automation, rpm, Build Libraries & Interfaces, deb, distinguished-contributor, v2.13.0

#4550 Add gradle-check test results publishing script to post stage
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4555 Revert "Add gradle-check test results publishing script to post stage"
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4557 Cleanup deb/rpm integTest uninstallation properly
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/legacy/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
Labels: enhancement, integtest, test, release, docker, ci-test-automation, rpm, deb, distinguished-contributor, v2.13.0

#4558 Disable automated builds for 2.13.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4554 Add cohere-10m corpus nightly run for nmslib vectorsearch workload.
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4560 Lock commits for 2.13.0
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor

#4564 Add errors='replace' handling for execute methods
  src/system/execute.py
Labels: enhancement, integtest, test, release, cicd, windows, ci-test-automation, Build Libraries & Interfaces, v2.13.0

#4559 Add publishGradleCheckTestResults lib to gradle-check
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4565 Update vectorsearch nighlty runs settings
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4568 Run manifest ci check only when PR is labelled
  .github/workflows/manifests.yml
Labels: distinguished-contributor

#4570 Update commits for RC3
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4571 Update OpenSearch commit for RC3
  manifests/2.13.0/opensearch-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4575 Update commits for RC4
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4576 Update commits for RC4
  manifests/2.13.0/opensearch-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4577 Add vectorsearch benchmarks for lucene and faiss
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4581 Update lychee action to use v1 instead of specific patch number
  .github/workflows/link-checker.yml
  .lycheeignore
  DEVELOPER_GUIDE.md
  README.md
  release-notes/opensearch-release-notes-1.2.2.md
  release-notes/opensearch-release-notes-1.2.3.md
  release-notes/opensearch-release-notes-2.1.0.md
  src/report_workflow/README.md
Labels: enhancement, distinguished-contributor, github_actions

#4584 Add r5.8xlarge instance runs for concurrent search baseline
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4585 Update configs and entrypoint for observability.query_assist.enabled in 2.13.0
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: enhancement, release, docker, distributions, Build Libraries & Interfaces, distinguished-contributor, v2.13.0

#4586 Update commits for rc5
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4587 Update commits for flow framework
  manifests/2.13.0/opensearch-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4541 Add mechanism to run benchmark tests against a given cluster endpoint
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_create_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_runner.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  src/test_workflow/integ_test/utils.py
  tests/tests_test_workflow/test_benchmark_args.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_create_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster_min.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_runner_opensearch.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4590 Move old manifests to legacy
  legacy-manifests/1.3.11/opensearch-1.3.11-test.yml
  legacy-manifests/1.3.11/opensearch-1.3.11.yml
  legacy-manifests/1.3.11/opensearch-dashboards-1.3.11-test.yml
  legacy-manifests/1.3.11/opensearch-dashboards-1.3.11.yml
  legacy-manifests/1.3.12/opensearch-1.3.12-test.yml
  legacy-manifests/1.3.12/opensearch-1.3.12.yml
  legacy-manifests/1.3.12/opensearch-dashboards-1.3.12-test.yml
  legacy-manifests/1.3.12/opensearch-dashboards-1.3.12.yml
  legacy-manifests/1.3.13/opensearch-1.3.13-test.yml
  legacy-manifests/1.3.13/opensearch-1.3.13.yml
  legacy-manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml
  legacy-manifests/1.3.13/opensearch-dashboards-1.3.13.yml
  legacy-manifests/2.10.0/opensearch-2.10.0-concurrent-search-test.yml
  legacy-manifests/2.10.0/opensearch-2.10.0-test.yml
  legacy-manifests/2.10.0/opensearch-2.10.0.yml
  legacy-manifests/2.10.0/opensearch-dashboards-2.10.0-test.yml
  legacy-manifests/2.10.0/opensearch-dashboards-2.10.0.yml
  legacy-manifests/2.10.1/opensearch-2.10.1.yml
  legacy-manifests/2.10.1/opensearch-dashboards-2.10.1.yml
  legacy-manifests/2.11.0/opensearch-2.11.0-test.yml
  legacy-manifests/2.11.0/opensearch-2.11.0.yml
  legacy-manifests/2.11.0/opensearch-dashboards-2.11.0-test.yml
  legacy-manifests/2.11.0/opensearch-dashboards-2.11.0.yml
  legacy-manifests/2.11.1/opensearch-2.11.1-test.yml
  legacy-manifests/2.11.1/opensearch-2.11.1.yml
  legacy-manifests/2.11.1/opensearch-dashboards-2.11.1-test.yml
  legacy-manifests/2.11.1/opensearch-dashboards-2.11.1.yml
  legacy-manifests/2.11.2/opensearch-2.11.2.yml
  legacy-manifests/2.9.0/opensearch-2.9.0-seg-rep-test.yml
  legacy-manifests/2.9.0/opensearch-2.9.0-test.yml
  legacy-manifests/2.9.0/opensearch-2.9.0.yml
  legacy-manifests/2.9.0/opensearch-dashboards-2.9.0-test.yml
  legacy-manifests/2.9.0/opensearch-dashboards-2.9.0.yml
  legacy-manifests/2.9.1/opensearch-2.9.1.yml
Labels: distinguished-contributor

#4591 Update commits for RC6
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4593 Add synchronize to manifest-check
  .github/workflows/manifests.yml
Labels: distinguished-contributor

#4583 Manifest commit lock automation
  jenkins/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile
  manifests/2.13.0/opensearch-2.13.0.yml
  tests/jenkins/TestReleaseManifestCommitLock.groovy
  tests/jenkins/data/opensearch-2.0.0-build.yml
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testManifestCommitLock_createPullRequest.txt
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testManifestCommitLock_matchBuildManifest.txt
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testManifestCommitLock_updateToRecentCommits.txt
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testMatchBuildManifest.txt
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testUpdateToRecentCommit.txt
Labels: distinguished-contributor

#4594 Updating integTest to use the new M54xlarge/C6g4xlarge agents
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: enhancement, integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.13.0

#4597 Lock integTest resources to 4cpu/16g on linux agents
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.13.0
