Repository opensearch-project/opensearch-build, pull requests merged in 2024-11, with the labels that each got.

#5163 Added release notes for 2.18 release
  release-notes/opensearch-release-notes-2.18.0.md
Labels: distinguished-contributor

#5166 Update 2.18 dashboards assistant new experimental configs
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: enhancement, release, distinguished-contributor, v2.18.0

#5165 Upload core plugins snapshots / gradle check updates in lib 7.3.2
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: enhancement, cicd, jenkins, distinguished-contributor

#5169 Switch from ghcr.io to ecr for trivy db pull images
  jenkins/docker/docker-scan.jenkinsfile
Labels: release, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, scanning, v2.18.0

#5170 Update nightly benchmark runs to track 2.18 and 2.19
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5172 Fix refreshed snapshot names
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5176 Update publish min snapshots with jenkinslib 7.3.3
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: cicd, jenkins, Build Libraries & Interfaces, distinguished-contributor

#5175 Add release note entry for new phone number analyzers
  release-notes/opensearch-release-notes-2.18.0.md
Labels: first-time-contributor

#5180 Publish Min Artifacts with new 7.3.4 libs
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: enhancement, cicd, jenkins

#5187 Support custom start-command/start-options on GHA container runner and openssl1.1.1 on AL2 docker images
  .github/workflows/get-ci-image-tag.yml
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: enhancement, cicd, docker, distinguished-contributor

#5189 Enable custom start commands and options to resolve GHA issues
  .github/workflows/python-tests.yml
Labels: enhancement, distinguished-contributor

#5078 Retro update 2.12
  release-notes/opensearch-release-notes-2.12.0.md
Labels: valued-contributor

#5192 Refactor distribution build job
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor
