Repository opensearch-project/opensearch-build, pull requests merged in 2024-08, with the labels that each got.

#4903 Update 3.0.0 manifest to use AL2 runner for OpenSearch
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: v3.0.0, distinguished-contributor, manifests, manifest-ci-check

#4914 Make benchmark results comment on pull request collapsable
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#4916 Changed days to keep integ test logs from 30 to 60 in OS and OSD
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: first-time-contributor

#4922 update jenkins jobs
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/TestRunBenchmarkTestEndpoint.groovy
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: first-time-contributor

#4864 Add support for opensearch-benchmark's `compare` feature
  src/run_benchmark_test.py
  src/test_workflow/README.md
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_runner_opensearch.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  src/test_workflow/benchmark_test/benchmark_test_suite_compare.py
  src/test_workflow/benchmark_test/benchmark_test_suite_execute.py
  src/test_workflow/benchmark_test/benchmark_test_suite_runners.py
  test.sh
  tests/test_run_benchmark_test.py
  tests/test_run_compare.py
  tests/tests_test_workflow/test_benchmark_args.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_runner_opensearch.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite_compare.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite_runners.py
Labels: first-time-contributor

#4921 Add specific download path for `downloadBuildManifest`
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4923 Add specific download path for `downloadBuildManifest`
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4925 Add specific download path for downloadBuildManifest
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4924 Fix argument hierarchy in benchmark test workflow.
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_test_suite_compare.py
  tests/test_run_compare.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite_compare.py
Labels: distinguished-contributor

#4926 Uses Jenkins `retry` for `downloadBuildManifest` errors
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4917 [Release 2.16.0] Consolidated release notes
  release-notes/opensearch-release-notes-2.16.0.md
Labels: distinguished-contributor

#4905 Skipping integTest for rpm and deb distribution for CCR
  jenkins/opensearch/integ-test.jenkinsfile
Labels: first-time-contributor

#4931 Changes for adding benchmark compare feature
  jenkins/opensearch/benchmark-compare.jenkinsfile
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  scripts/benchmark/benchmark-pull-request.sh
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/TestCompareBenchmarks.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-compare.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/compare-benchmarks.jenkinsfile.txt
Labels: distinguished-contributor

#4935 fix parameter name in benchmark-pull-request job
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
Labels: distinguished-contributor

#4927 Fix for only adding modified files in release-notes-check compile script
  jenkins/release-workflows/release-notes-check.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-compile.jenkinsfile.txt
Labels: first-time-contributor

#4939 Add issue triaging document
  TRIAGING.md
Labels: distinguished-contributor

#4942 Update nightly benchmark runs to track 2.17.0
  .github/workflows/link-checker.yml
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4945 Rename generated release notes file
  jenkins/release-workflows/release-notes-check.jenkinsfile
  tests/jenkins/TestReleaseNotesCheckAndCompile.groovy
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-compile.jenkinsfile.txt
Labels: distinguished-contributor

#4947 Update post release activities
  .github/ISSUE_TEMPLATE/release_template.md
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#4948 Update untriaged issues link
  .github/workflows/link-checker.yml
  TRIAGING.md
Labels: distinguished-contributor

#4950 Update Release Templates and Documentation related to component release owner
  .github/ISSUE_TEMPLATE/release_template.md
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#4951 Added dashboard and test manifests for 1.3.19
  manifests/1.3.19/opensearch-1.3.19-test.yml
  manifests/1.3.19/opensearch-dashboards-1.3.19-test.yml
  manifests/1.3.19/opensearch-dashboards-1.3.19.yml
Labels: first-time-contributor, manifest-ci-check

#4954 [Release 2.17.0] Add 2.17.0 manifests
  manifests/2.17.0/opensearch-2.17.0-test.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0-test.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4955 Remove 1.3.19 check-for-build
  jenkins/check-for-build.jenkinsfile
Labels: repeat-contributor

#4956 Update integTest with 1.1 test-report.yml libs 6.8.3 version
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: enhancement, integtest, test, cicd, ci-test-automation, jenkins, distinguished-contributor

#4953 Add minimumCompilerVersion check for manifest update on OpenSearch Min branches
  legacy-manifests/1.3.14/opensearch-1.3.14-test.yml
  legacy-manifests/1.3.14/opensearch-1.3.14.yml
  legacy-manifests/1.3.14/opensearch-dashboards-1.3.14-test.yml
  legacy-manifests/1.3.14/opensearch-dashboards-1.3.14.yml
  legacy-manifests/1.3.15/opensearch-1.3.15-test.yml
  legacy-manifests/1.3.15/opensearch-1.3.15.yml
  legacy-manifests/1.3.15/opensearch-dashboards-1.3.15-test.yml
  legacy-manifests/1.3.15/opensearch-dashboards-1.3.15.yml
  legacy-manifests/1.3.16/opensearch-1.3.16-test.yml
  legacy-manifests/1.3.16/opensearch-1.3.16.yml
  legacy-manifests/1.3.16/opensearch-dashboards-1.3.16-test.yml
  legacy-manifests/1.3.16/opensearch-dashboards-1.3.16.yml
  legacy-manifests/2.12.0/opensearch-2.12.0-concurrent-search-test.yml
  legacy-manifests/2.12.0/opensearch-2.12.0-test.yml
  legacy-manifests/2.12.0/opensearch-2.12.0.yml
  legacy-manifests/2.12.0/opensearch-dashboards-2.12.0-test.yml
  legacy-manifests/2.12.0/opensearch-dashboards-2.12.0.yml
  legacy-manifests/2.12.1/opensearch-2.12.1.yml
  legacy-manifests/2.13.0/opensearch-2.13.0-test.yml
  legacy-manifests/2.13.0/opensearch-2.13.0.yml
  legacy-manifests/2.13.0/opensearch-dashboards-2.13.0-test.yml
  legacy-manifests/2.13.0/opensearch-dashboards-2.13.0.yml
  legacy-manifests/2.13.1/opensearch-2.13.1.yml
  legacy-manifests/2.14.0/opensearch-2.14.0-test.yml
  legacy-manifests/2.14.0/opensearch-2.14.0.yml
  legacy-manifests/2.14.0/opensearch-dashboards-2.14.0-test.yml
  legacy-manifests/2.14.0/opensearch-dashboards-2.14.0.yml
  legacy-manifests/2.14.1/opensearch-2.14.1.yml
  src/manifests_workflow/component_opensearch_min.py
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/data/repository/OpenSearch/buildSrc/src/main/resources/minimumCompilerVersion
  tests/tests_manifests_workflow/test_component_opensearch_min.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch_dashboards.py
Labels: enhancement, distinguished-contributor, manifests

#4957 Jenkins manifest update workflow switch runner and fix jdk14 install issues on docker images
  docker/ci/config/jdk-setup.sh
  jenkins/manifests-update.jenkinsFile
Labels: enhancement, distinguished-contributor, manifests

#4959 Add dashboards build for 2.17.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4961 Update integTest with lib version 6.8.4
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: enhancement, integtest, distinguished-contributor

#4960 Fix the report workflow to work with ci-group
  src/manifests/test_manifest.py
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/data/test-manifest-opensearch-dashboards.yml
  tests/tests_report_workflow/test_test_report_runner_dashboards.py
Labels: distinguished-contributor

#4964 Add sleep for few seconds to ensure the container process are properly started
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
Labels: distinguished-contributor

#4975 Enable check-for-build to trigger linux-tar integTest during distribution build cron
  jenkins/check-for-build.jenkinsfile
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, distributions, distinguished-contributor

#4963 Add TEST_PLATFORM and TEST_DISTRIBUTION param to fine-grain control integ-test triggers
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: enhancement, integtest, test, cicd, ci-test-automation, jenkins, distributions, distinguished-contributor

#4976 Fix the missing comma in check-for-build
  jenkins/check-for-build.jenkinsfile
Labels: enhancement, distinguished-contributor

#4974 Refactor releaseTag workflow and add tests
  jenkins/release-workflows/release-tag.jenkinsfile
  tests/jenkins/TestReleaseTagJob.groovy
  tests/jenkins/data/opensearch-dashboards-dist-2.16.0.yml
  tests/jenkins/data/opensearch-dist-2.16.0.yml
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-tag.jenkinsfile.txt
Labels: distinguished-contributor

#4978 Add opensearch system template repo to ws scan
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor
