Repository opensearch-project/opensearch-build, pull requests merged in 2024-01, with the labels that each got.

#4318 Replace jenv local with jenv global for macOS snapshots JDK switch
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: bug, cicd, macos, jenkins, Build Libraries & Interfaces, distinguished-contributor

#4289 Build incremental components through build workflow with loading previous build manifest
  jenkins/opensearch/distribution-build.jenkinsfile
  src/build_workflow/README.md
  src/build_workflow/build_args.py
  src/build_workflow/build_recorder.py
  src/run_build.py
  tests/test_run_build.py
  tests/tests_build_workflow/test_build_incremental.py
  tests/tests_build_workflow/test_build_recorder.py
Labels: distinguished-contributor

#4321 Categorize the on-boarding document to plugins and standalone components
  .github/ISSUE_TEMPLATE/plugin_onboarding_template.yaml
  .github/ISSUE_TEMPLATE/standalone_releases_template.yaml
  ONBOARDING.md
Labels: distinguished-contributor

#4323 Default not to create/update issues during integration test runs
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
Labels: distinguished-contributor

#4324 Add wiki page for testing a distribution
  docs/Testing-the-Distribution.md
Labels: distinguished-contributor

#4325 Update wiki home page
  docs/Home.md
Labels: distinguished-contributor

#4302 Pass in strong password instead to fix integtest workflow
  scripts/default/integtest.sh
  src/test_workflow/integ_test/distribution_tar.py
  src/test_workflow/integ_test/distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_tar.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch.py
Labels: first-time-contributor

#4331 Change password based on version in integtest health check
  src/test_workflow/integ_test/service_opensearch.py
  src/test_workflow/perf_test/perf_test_cluster.py
  tests/tests_test_workflow/test_perf_workflow/perf_test/data/bundle_manifest.yml
  tests/tests_test_workflow/test_perf_workflow/perf_test/test_perf_test_cluster.py
Labels: repeat-contributor

#4334 Pass in strong password to OSD integ test if version >= 2.12.0
  src/test_workflow/integ_test/service_opensearch.py
  src/test_workflow/integ_test/service_opensearch_dashboards.py
  src/test_workflow/integ_test/utils.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_utils.py
Labels: repeat-contributor

#4333 Updating jenkinsfile with using update-alternatives to switch JDK version
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: all-star-contributor

#4326 Add release process wiki
  .github/ISSUE_TEMPLATE/release_template.md
  docs/Home.md
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#4339 Fix the hyperlink in home page
  docs/Home.md
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#4338 Bump lib version for snapshots to 5.12.0
  .gitignore
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-linux-arm64-build-manifest.yml
  tests/jenkins/data/opensearch-min-3.0.0-snapshot-linux-x64-build-manifest.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: distinguished-contributor

#4317 add dashboards-assistant to build repo
  .github/workflows/osd-increment-plugin-versions.yml
  .github/workflows/osd-release-issues.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  tools/vulnerability-scan/wss-scan.config
Labels: seasoned-contributor

#4340 Fix maven multi url issues and update awscli==1.32.17 to support PyYAML 6.0.1 in ppc64le
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.rockylinux8.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/docker-builder.ubuntu2004.x64.dockerfile
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
Labels: cicd, docker, jenkins, distinguished-contributor

#4346 Fix the infra deployment info in readme
  README.md
Labels: distinguished-contributor

#4347 Fix release document broken links
  README.md
Labels: distinguished-contributor

#4343 Ensuring cleanup with OSD plugins when failed during continue-on-error
  scripts/components/ganttChartDashboards/build.sh
  scripts/default/opensearch-dashboards/build.sh
Labels: bug, release, distinguished-contributor, v2.12.0

#4250 Updates tar distribution to conform to changes in install demo configuration script in security plugin
  scripts/startup/tar/linux/opensearch-tar-install.sh
Labels: valued-contributor, v2.12.0

#4351 Improve osd components repo cleanup logics
  scripts/components/ganttChartDashboards/build.sh
  scripts/default/opensearch-dashboards/build.sh
Labels: bug, release, distinguished-contributor, v2.12.0

#4353 Tweak the path that get removed by osd plugin cleanups
  scripts/components/ganttChartDashboards/build.sh
  scripts/default/opensearch-dashboards/build.sh
Labels: bug, release, distinguished-contributor, v2.12.0

#4349 Run integtest for components present in test manifest
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/data/opensearch-3.0.0-build.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4355 Trigger manifest check only for mentioned paths
  .github/workflows/manifests.yml
Labels: distinguished-contributor

#4332 Updates rpm and deb distribution to adapt to admin password change
  scripts/components/OpenSearch/install.sh
  scripts/pkg/build_templates/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/opensearch/deb/debian/preinst
  scripts/pkg/build_templates/opensearch/rpm/opensearch.rpm.spec
Labels: valued-contributor, v2.12.0

#4341 Revert "Revert rpm/deb changes pending decision"
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
Labels: repeat-contributor, v2.12.0

#4274 Updates Docker and windows distribution build files to reflect to changes in admin user setup
  docker/release/config/opensearch/opensearch-docker-entrypoint.sh
  docker/release/dockercomposefiles/docker-compose-2.x.yml
  scripts/opensearch-onetime-setup.sh
  scripts/startup/zip/windows/opensearch-windows-install.bat
Labels: valued-contributor, v2.12.0

#4354 Add monthly rebuild cron for docker re-release
  jenkins/docker/docker-re-release.jenkinsfile
  tests/jenkins/TestDockerReRelease.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-re-release.jenkinsfile.txt
Labels: enhancement, docker, jenkins, distinguished-contributor

#4359 add update test procedure for nyc_taxis
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4363 add assistant to dashboard
  manifests/2.12.0/opensearch-dashboards-2.12.0-test.yml
  manifests/2.12.0/opensearch-dashboards-2.12.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
Labels: first-time-contributor

#4365 Adds security to 1.3.15 and 1.4.0 manifests
  manifests/1.3.15/opensearch-1.3.15.yml
  manifests/1.4.0/opensearch-1.4.0.yml
Labels: seasoned-contributor

#4311 Added documentation for Github Wiki Docs
  docs/README.md
Labels: first-time-contributor

#4286 Update index.json file at stage level for each distribution
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4368 Refactor and enable triggering integ-test for RPM, debian and windows
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4356 Update distribution build jenkins job with option for incremental build
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  manifests/2.12.0/opensearch-2.12.0.yml
  src/build_workflow/build_recorder.py
  src/run_build.py
  tests/test_run_build.py
  tests/tests_build_workflow/test_build_recorder.py
Labels: distinguished-contributor

#4362 feat: add experimental feature flag for dashboards-assistant plugin
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: repeat-contributor

#4352 Add opensearch cluster stdout and stderr logs to test results manifest
  src/manifests/test_report_manifest.py
  src/report_workflow/test_report_runner.py
  tests/tests_manifests/data/test-run.yml
  tests/tests_manifests/test_test_run_manifest.py
  tests/tests_report_workflow/test_test_report_runner.py
  tests/tests_report_workflow/test_test_report_runner_dashboards.py
Labels: distinguished-contributor

#4371 Refactor distribution-build.jenkinsfile for opensearch-dashboards
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: all-star-contributor

#4372 Update groovy library version for distribution build jobs
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4373 Refactor distrubution build job for dashboards
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4376 Fix deb/rpm integTest not install distribution correctly due to 2.12 security changes
  docker/ci/dockerfiles/current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
Labels: bug, integtest, test, cicd, docker, ci-test-automation, distinguished-contributor

#4380 Remove manifest addition workflow from GHA
  .github/workflows/versions.yml
Labels: distinguished-contributor

#4382 Removed BWC test for flow framework
  manifests/2.12.0/opensearch-2.12.0-test.yml
Labels: seasoned-contributor

#4385 Fix the variable name for issue creation
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4383 Override browser default from chromium to electron as Cypress 9.5.4 does not run with chromium 114+
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
Labels: bug, integtest, test, release, cicd, ci-test-automation, distinguished-contributor, v2.12.0

#4381 Remove opensearch 2.12.0/1.3.15 checks as distribution-build already taken care of issue reporting
  manifests/1.3.15/opensearch-1.3.15.yml
  manifests/2.12.0/opensearch-2.12.0.yml
Labels: enhancement, release, distinguished-contributor, v2.12.0

#4388 Fix the updateGitHubIssue boolean param
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchIntegTest.groovy
Labels: distinguished-contributor

#4374 Reactor and enable integ-tests for all distributions in OSD
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4391 Fix the release branch bug in `component_release_template.md`
  .github/ISSUE_TEMPLATE/component_release_template.md
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: bug, distinguished-contributor

#4387 Onboarding skills repo
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/os-release-issues.yml
  manifests/2.12.0/opensearch-2.12.0-concurrent-search-test.yml
  manifests/2.12.0/opensearch-2.12.0-test.yml
  manifests/2.12.0/opensearch-2.12.0.yml
Labels: release, on-boarding, first-time-contributor, v2.12.0

#4390 Enable incremental build as default for distribution build Jenkins job
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor
