Repository opensearch-project/opensearch-build, pull requests merged in 2024-04, with the labels that each got.

#4574 URL encode test result files
  src/test_workflow/test_recorder/test_recorder.py
  tests/tests_test_workflow/test_recorder/test_test_recorder.py
Labels: first-time-contributor

#4600 Bump shared library version to 6.4.2
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#4595 Add consolidated release notes for 2.13.0
  release-notes/opensearch-release-notes-2.13.0.md
Labels: distinguished-contributor

#4603 Update ref to tags for 2.13.0
  manifests/2.13.0/opensearch-2.13.0.yml
  manifests/2.13.0/opensearch-dashboards-2.13.0.yml
Labels: distinguished-contributor, manifest-ci-check

#4604 Update nightly benchmark to track 2.14 version
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4579 Add jenkins benchmark job for cluster endpoint runs
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunBenchmarkTestEndpoint.groovy
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4613 Fix build failure for benchmark-test-endpoint jenkins workflow
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
Labels: distinguished-contributor

#4614 Ignore release notes folder for link checker workflow
  .github/workflows/link-checker.yml
Labels: distinguished-contributor

#4617 Replace so workload with pmc in nightly runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4615 Update the build library tag version for build job
  .github/workflows/link-checker.yml
  docs/Releasing-the-Distribution.md
  docs/Testing-the-Distribution.md
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#4525 Switch ci images to almalinux8/windows2019/ubuntu20.04
  .github/workflows/get-ci-image-tag.yml
  jenkins/docker/docker-build.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-re-release.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  jenkins/packer/packer-build.jenkinsfile
  jenkins/promotion/promote-docker-ecr.jenkinsfile
  jenkins/promotion/promote-repos.jenkinsfile
  jenkins/rpm-validation/rpm-validation.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  manifests/templates/opensearch-dashboards/2.x/manifest.yml
  manifests/templates/opensearch-dashboards/3.x/manifest.yml
  manifests/templates/opensearch-dashboards/default/manifest.yml
  tests/jenkins/TestDockerBuild.groovy
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/packer/packer-build.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDocker.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
  tests/tests_manifests_workflow/test_input_manifests.py
Labels: integtest, cicd, docker, jenkins, Build Libraries & Interfaces, distinguished-contributor, ppc64le

#4618 Update the plugin_onboarding_template.yaml template to include a documentation field
  .github/ISSUE_TEMPLATE/plugin_onboarding_template.yaml
Labels: first-time-contributor

#4619 Update the ONBOARDING.md file with note about contributing documentation
  ONBOARDING.md
Labels: first-time-contributor

#4626 Update opensearch-release-notes-2.13.0.md
  release-notes/opensearch-release-notes-2.13.0.md
Labels: first-time-contributor

#4628 Ensure error stack trace is always printed out for each build
  src/run_build.py
Labels: bug, Build Libraries & Interfaces, distinguished-contributor

#4629 Replace http_logs for concurrent search nightlies with noaa
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4633 Enable snapshot runs for NOAA workload
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4636 Add snapshot enabled nightly runs for pmc
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4632 Upgrade ruby from 2.6.0 to 3.1.2 for opensearch-ruby 3.2.0 requirements
  docker/ci/dockerfiles/current/release.centos7.clients.x64.arm64.dockerfile
Labels: enhancement, docker, distinguished-contributor

#4639 Add test manifests for 1.3.16 and increase build frequency
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.16/opensearch-1.3.16-test.yml
  manifests/1.3.16/opensearch-dashboards-1.3.16-test.yml
Labels: distinguished-contributor

#4641 Update . to : for all chown coomands in deb/rpm build templates
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/current/opensearch/rpm/opensearch.rpm.spec
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/postinst
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/postinst
  scripts/pkg/build_templates/legacy/opensearch/rpm/opensearch.rpm.spec
Labels: enhancement, rpm, distributions, Build Libraries & Interfaces, deb, distinguished-contributor

#4642 Update jenkinsfile with latest Windows M54xlarge Agents
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: enhancement, integtest, test, cicd, windows, ci-test-automation, Build Libraries & Interfaces, distinguished-contributor

#4644 Add tiered policy snapshot runs for big5 workload for mainline
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4645 Use almalinux8 docker images for 2.14.0 builds
  docker/ci/dockerfiles/legacy/build.centos7.opensearch.x64.arm64.ppc64le.dockerfile
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.14.0/opensearch-2.14.0-test.yml
  manifests/2.14.0/opensearch-2.14.0.yml
Labels: release, docker, distinguished-contributor, v2.14.0

#4646 Remove cron for 1.3.16 build
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#4647 Update gcc from 9.2.1 to 12.2.1 to fix k-NN compile bug on ARM64
  docker/ci/config/gcc-toolset-12-setup
  docker/ci/config/gcc-toolset-9-setup
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
Labels: bug, enhancement, release, docker, Build Libraries & Interfaces, distinguished-contributor, v2.14.0

#4621 Add changes to benchmarks to securely pass Cluster endpoint details
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  run.sh
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_create_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_cluster.py
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  test.sh
  tests/jenkins/TestRunBenchmarkTestEndpoint.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_cluster.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4648 Lock manifest commit for 1.3.16 release candidates
  manifests/1.3.16/opensearch-1.3.16.yml
  manifests/1.3.16/opensearch-dashboards-1.3.16.yml
Labels: distinguished-contributor

#4652 Fix manifest lock automation bug to match the `commit_id`
  jenkins/release-manifest-commit-lock/release-manifest-commit-lock.jenkinsfile
  tests/jenkins/TestReleaseManifestCommitLock.groovy
  tests/jenkins/jenkinsjob-regression-files/release-manifest-commit-lock/testMatchBuildManifest.txt
Labels: distinguished-contributor

#4650 Create the consolidated release notes for 1.3.16 release and update refs to tags
  manifests/1.3.16/opensearch-1.3.16.yml
  manifests/1.3.16/opensearch-dashboards-1.3.16.yml
  release-notes/opensearch-release-notes-1.3.16.md
Labels: distinguished-contributor

#4653 Added Flow Framework to 3.0 manifest
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: seasoned-contributor

#4657 Update all get image defaults to almalinux8
  .github/workflows/get-ci-image-tag.yml
  docker/ci/get-ci-images.sh
Labels: enhancement, cicd, docker, distinguished-contributor

#4661 Add a step to update releases page
  .github/ISSUE_TEMPLATE/release_template.md
Labels: distinguished-contributor

#4663 Replace gcc12 with gcc11 due to binutils 2.38 bug
  docker/ci/config/gcc-toolset-11-setup
  docker/ci/config/gcc-toolset-12-setup
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
Labels: enhancement, release, cicd, docker, distinguished-contributor, v2.14.0

#4660 Fix manifest file escaping in URLs
  src/test_workflow/test_recorder/test_recorder.py
  tests/tests_test_workflow/test_recorder/test_test_recorder.py
Labels: first-time-contributor

#4662 Increase jvm heap size of test cluster from default 1G to 2G for integration tests.
  src/test_workflow/integ_test/distribution.py
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  src/test_workflow/integ_test/service_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_service_opensearch.py
Labels: distinguished-contributor

#4667 Revert #4651 #4654 and partially #4657 for KNN to use CentOS7 in 2.14.0
  .github/workflows/get-ci-image-tag.yml
  docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.ppc64le.dockerfile
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.14.0/opensearch-2.14.0-test.yml
  manifests/2.14.0/opensearch-2.14.0.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  tests/jenkins/jenkinsjob-regression-files/release-notes-check/release-notes-check.jenkinsfile.txt
Labels: release, distinguished-contributor, v2.14.0

#4668 Switch components branches to 2.14 for release
  jenkins/check-for-build.jenkinsfile
  manifests/2.14.0/opensearch-2.14.0.yml
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
Labels: distinguished-contributor
