Repository opensearch-project/opensearch-build, pull requests merged in 2024-06, with the labels that each got.

#4744 Update github ci checks opensearch build image to al2
  .github/ISSUE_TEMPLATE/release_template.md
  .github/workflows/get-ci-image-tag.yml
  jenkins/check-for-build.jenkinsfile
Labels: enhancement, release, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, v2.15.0

#4695 Update configs and entrypoint for logging.ignoreEnospcError in 2.15.0
  config/opensearch_dashboards-2.x.yml
  config/opensearch_dashboards-default.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: release, first-time-contributor, v2.15.0

#4747 Run promotion jobs in parallel
  jenkins/promotion/release-promotion-parallel.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionParallelTest.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion-parallel.jenkinsfile.txt
Labels: distinguished-contributor

#4746 Add consolidated release notes for 1.3.17
  release-notes/opensearch-release-notes-1.3.17.md
Labels: distinguished-contributor

#4749 Update release tags for 1.3.17
  manifests/1.3.17/opensearch-1.3.17.yml
  manifests/1.3.17/opensearch-dashboards-1.3.17.yml
Labels: distinguished-contributor, manifest-ci-check

#4720 Create 2.15.0 test manifest + add async search bwc tests
  manifests/2.15.0/opensearch-2.15.0-test.yml
  manifests/2.15.0/opensearch-dashboards-2.15.0-test.yml
Labels: release, first-time-contributor, manifest-ci-check, v2.15.0

#4755 add big5 workload runs for c5.2xlarge instance types
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4757 Upgrade Jenkins core version to 2.426.3
  build.gradle
Labels: distinguished-contributor

#4758 Update 2.14 manifests to use tags after release
  manifests/2.14.0/opensearch-2.14.0.yml
  manifests/2.14.0/opensearch-dashboards-2.14.0.yml
Labels: release, distinguished-contributor, v2.14.0, manifest-ci-check

#4760 Revert centos7 to al2 changes due to issues in 2.15.0
  .github/workflows/get-ci-image-tag.yml
  jenkins/opensearch/integ-test.jenkinsfile
  manifests/2.15.0/opensearch-2.15.0.yml
Labels: release, v2.15.0

#4753 Add additional workflows to central promotion workflows
  jenkins/promotion/release-promotion-parallel.jenkinsfile
  jenkins/promotion/release-promotion.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionParallelTest.groovy
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion-parallel.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor

#4759 Switch manifest to use specific branch 2.15
  jenkins/check-for-build.jenkinsfile
  manifests/2.15.0/opensearch-2.15.0.yml
  manifests/2.15.0/opensearch-dashboards-2.15.0.yml
Labels: release, distinguished-contributor, manifest-ci-check, v2.15.0

#4762 Add support to validate both docker and ECR as image source
  jenkins/promotion/release-promotion.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  src/run_validation.py
  src/validation_workflow/validation_args.py
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/TestValidateArtifacts.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
  tests/test_run_validation.py
  tests/tests_validation_workflow/test_validation_args.py
Labels: distinguished-contributor

#4768 Update yaml-lint to fix to 3.9.12 python
  .github/workflows/yaml-lint.yml
Labels: bug, distinguished-contributor, github_actions

#4770 Add condition for OSD integ tests on deb and rpm
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
Labels: distinguished-contributor

#4765 2.15.0 RC2 Changes
  manifests/2.15.0/opensearch-2.15.0.yml
  manifests/2.15.0/opensearch-dashboards-2.15.0.yml
Labels: release, distinguished-contributor, manifest-ci-check, v2.15.0

#4772 2.15.0 RC2 rev2
  manifests/2.15.0/opensearch-2.15.0.yml
  manifests/2.15.0/opensearch-dashboards-2.15.0.yml
Labels: release, distinguished-contributor, manifest-ci-check, v2.15.0

#4777 Update the lib to 6.5.0 and add `gradle-check-flaky-test-issue-creation.jenkinsfile`.
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#4778 Typo: wrong remote URL in `gradle-check-flaky-test-issue-creation.jenkinsfile`
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
Labels: distinguished-contributor

#4780 Update noaa_semantic_search benchmark run parameters
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4781 Update noaa_semantic_search performance run data instance to r5.2xlarge
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4779 Raise osd integTest timeout to 6 hours due to OSD core length
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: release, distinguished-contributor, v2.15.0

#4782 Update `gradle-check-flaky-test-issue-creation.jenkinsfile`.
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
Labels: distinguished-contributor

#4775 2.15.0 RC3 Changes
  manifests/2.15.0/opensearch-2.15.0.yml
  manifests/2.15.0/opensearch-dashboards-2.15.0.yml
Labels: release, distinguished-contributor, manifest-ci-check, v2.15.0

#4785 2.15.0 RC4 Changes
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  manifests/2.15.0/opensearch-2.15.0.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: release, distinguished-contributor, manifest-ci-check, v2.15.0

#4794 Make endpoint_string one line for ccr test
  src/test_workflow/integ_test/integ_test_suite_opensearch.py
Labels: integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.15.0

#4795 Increase osd integTest timeout to 6 hours for OSD core
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.15.0

#4797 Pin OSB docker version to 1.6.0
  src/test_workflow/benchmark_test/benchmark_test_suite.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_test_suite.py
Labels: distinguished-contributor

#4796 add ci-groups changes for OSD tests
  manifests/2.15.0/opensearch-dashboards-2.15.0-test.yml
  src/manifests/test_manifest.py
  src/test_workflow/integ_test/integ_test_runner.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch_dashboards.py
Labels: distinguished-contributor

#4798 Add cleanup for the data dir after integtests
  src/test_workflow/integ_test/distribution.py
  src/test_workflow/integ_test/distribution_deb.py
  src/test_workflow/integ_test/distribution_rpm.py
  src/test_workflow/integ_test/distribution_tar.py
  src/test_workflow/integ_test/distribution_zip.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_deb.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_rpm.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_tar.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
Labels: enhancement, integtest, test, release, cicd, ci-test-automation, jenkins, distinguished-contributor, v2.15.0

#4789 Adding the 2.15.0 consolidated release notes
  release-notes/opensearch-release-notes-2.15.0.md
Labels: release, distinguished-contributor, v2.15.0

#4800 Switch 2.15.0 input manifest from commit ids to tags
  manifests/2.15.0/opensearch-2.15.0.yml
  manifests/2.15.0/opensearch-dashboards-2.15.0.yml
Labels: release, distinguished-contributor, manifest-ci-check, v2.15.0

#4802 Enable DYNAMIC_ARCH for openblas in x64 AL2 build environment
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: seasoned-contributor

#4803 Bump nighlty benchmarks to 2.16 version
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#4805 Update the `gradle-check-flaky-test-issue-creation.jenkinsfile` with new library version
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
Labels: distinguished-contributor

#4808 Fix cloudfront validation role for promotion workflow
  jenkins/promotion/release-promotion.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor

#4812 Fix the docker promotion parameter types
  jenkins/promotion/release-promotion.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/jenkinsjob-regression-files/promotion/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor
