Repository opensearch-project/opensearch-build, pull requests merged in 2024-12, with the labels that each got.

#5194 Increase build frequency to prepare for 1.3.20 release
  jenkins/check-for-build.jenkinsfile
Labels: repeat-contributor

#5195 Enable 1.3.20 snapshots publishing on Jenkins runs
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
Labels: enhancement, release, distinguished-contributor, v1.3.20

#5179 Run OSD integ test ci-groups in parallel
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  src/test_workflow/integ_test/integ_test_runner.py
  src/test_workflow/test_args.py
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_runner_opensearch_dashboards.py
Labels: distinguished-contributor

#5197 Added core test manifest and changed cron for 1.3.20
  jenkins/check-for-build.jenkinsfile
  manifests/1.3.20/opensearch-1.3.20-test.yml
Labels: valued-contributor, manifest-ci-check

#5198 Removed 1.3.20 from check-for-build
  jenkins/check-for-build.jenkinsfile
Labels: valued-contributor

#5205 Increase timeout for validation workflow stages
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: distinguished-contributor
