Repository opensearch-project/opensearch-build, pull requests merged in 2024-10, with the labels that each got.

#5068 Update the `gradle-check-flaky-test-issue-creation.jenkinsfile` to use 6.9.2 library.
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
Labels: distinguished-contributor

#5063 Add consolidated release notes for 2.17.1
  release-notes/opensearch-release-notes-2.17.1.md
Labels: distinguished-contributor

#5070 Set segment count to 10 for big5 single shard runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5067 Update parameter requirement for manifest-commit-lock workflow
  jenkins/release-workflows/release-manifest-commit-lock.jenkinsfile
  tests/jenkins/TestReleaseManifestCommitLock.groovy
Labels: distinguished-contributor

#4971 Adding user-behavior-insights
  manifests/3.0.0/opensearch-3.0.0.yml
  tools/vulnerability-scan/wss-scan.config
Labels: first-time-contributor, manifest-ci-check

#5058 Remove typed-ast as it is deprecated
  Pipfile
  Pipfile.lock
  pyproject.toml
Labels: distinguished-contributor, maintenance

#5074 typos and bug-fixes in benchmark jobs
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5075 Adding Dashboards Flow Framework to 2.18.0 Manifest
  manifests/2.18.0/opensearch-dashboards-2.18.0.yml
Labels: first-time-contributor, manifest-ci-check

#5077 Update the snapshot for 2.16+ versions
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5079 Add support for instance based storge in nightly benchmark runs
  src/test_workflow/benchmark_test/benchmark_args.py
  src/test_workflow/benchmark_test/benchmark_create_cluster.py
  tests/tests_test_workflow/test_benchmark_args.py
  tests/tests_test_workflow/test_benchmark_workflow/benchmark_test/test_benchmark_create_cluster.py
Labels: distinguished-contributor

#5076 Switch build notification to metrics based data
  docs/Releasing-the-Distribution.md
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5081 Refactor integ-test notification
  jenkins/integ-test-notification.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5085 Support JDK-23 builds on Jenkins
  docker/ci/config/jdk-setup.sh
  docker/ci/config/legacy/windows-servercore-setup.ps1
Labels: seasoned-contributor

#5086 Update all c5 and c6g agents to m5 and m6g
  jenkins/check-for-build.jenkinsfile
  jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/integ-test-notification.jenkinsfile
  jenkins/legacy/TestRunNonSecurityPerfTestScript.groovy.legacy
  jenkins/legacy/rpm-validation.jenkinsfile
  jenkins/manifests-update.jenkinsFile
  jenkins/opensearch-dashboards/bwc-test.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/maven-publish-1.3.x.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  jenkins/promotion/promote-artifacts.jenkinsfile
  jenkins/promotion/promote-docker-ecr.jenkinsfile
  jenkins/promotion/promote-repos.jenkinsfile
  jenkins/release-workflows/release-branch.jenkinsfile
  jenkins/release-workflows/release-manifest-commit-lock.jenkinsfile
  jenkins/release-workflows/release-notes-check.jenkinsfile
  jenkins/release-workflows/release-promotion.jenkinsfile
  jenkins/release-workflows/release-tag.jenkinsfile
  jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  jenkins/vulnerability-scan/whitesource-scan.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/bwc-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDocker.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-branch-buildmanifest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-branch-inputmanifest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-check.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-compile.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-tag.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_createPullRequest.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_matchBuildManifest.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_updateToRecentCommits.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testManifestCommitLock_updateToTags.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testMatchBuildManifest.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testUpdateToRecentCommit.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/testUpdateToRecentCommit_excludeFTRepo.txt
  tests/jenkins/jenkinsjob-regression-files/sign-standalone-artifacts/sign-standalone-artifacts.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/vulnerability-scan/whitesource-scan.jenkinsfile.txt
Labels: enhancement, jenkins, distinguished-contributor

#5089 Add docker container and parameter check to jenkins workflow
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
  jenkins/integ-test-notification.jenkinsfile
Labels: distinguished-contributor

#5092 PR to Fix the missing Gradle Reports in `opensearch-integ-test/` folder
  src/test_workflow/integ_test/integ_test_suite_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch.py
Labels: distinguished-contributor

#5080 Update release template for branch creation
  .github/ISSUE_TEMPLATE/release_template.md
Labels: distinguished-contributor

#5090 Add conditional check for report workflow to skip component not in bundle
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/data/test_manifest.yml
  tests/tests_report_workflow/test_test_report_runner.py
Labels: distinguished-contributor

#5093 Resolve scoop Select-CurrentVersion error by locking to 0.4.2
  docker/ci/config/windows-setup.ps1
Labels: bug, docker, windows, distinguished-contributor

#5095 Update 3.0.0 manifests to use JDK-23
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: seasoned-contributor

#5098 Automate adding manifest to integTest notification cron
  src/manifests_workflow/input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch.py
  tests/tests_manifests_workflow/test_input_manifests_opensearch_dashboards.py
Labels: distinguished-contributor

#5097 Add support for instance based storge in nightly benchmark run
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5100 Add jdk23 support on windows docker
  docker/ci/config/windows-setup.ps1
Labels: enhancement, docker, windows, distinguished-contributor

#5101 Add OpenSearch failed Test Class and Name fields to test-report.yml
  .licenserc.json
  Pipfile
  Pipfile.lock
  src/manifests/test_report_manifest.py
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/data/test-results/123/integ-test/geospatial/with-security/geospatial.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/geospatial/with-security/opensearch-integ-test/index.html
  tests/tests_report_workflow/data/test-results/123/integ-test/geospatial/without-security/geospatial.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/geospatial/without-security/opensearch-integ-test/index.html
  tests/tests_report_workflow/data/test-results/123/integ-test/index-management/with-security/index-management.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/index-management/with-security/opensearch-integ-test/index.html
  tests/tests_report_workflow/data/test-results/123/integ-test/index-management/without-security/index-management.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/index-management/without-security/opensearch-integ-test/index.html
  tests/tests_report_workflow/test_test_report_runner.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, jenkins, distinguished-contributor

#5108 Integtest failed test case check will skip infobox class
  src/report_workflow/test_report_runner.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, jenkins, distinguished-contributor

#5107 (Part 2) PR to Fix the missing Gradle Reports in `opensearch-integ-test/` folder
  src/test_workflow/integ_test/integ_test_suite_opensearch.py
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_integ_test_suite_opensearch.py
Labels: distinguished-contributor

#5109 Add technical steering repo to whitesource scan
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5102 Bump lib to 7.1.0 and remove publishing notification
  jenkins/check-for-build.jenkinsfile
  jenkins/integ-test-notification.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/bwc-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/bwc-test.jenkinsfile.txt
Labels: distinguished-contributor

#5110 Update big5 multinode snapshot and k-nn run updates
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5113 Remove .i18nrc.json as OSD do not bundle it anymore
  scripts/pkg/build_templates/current/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
Labels: enhancement, release, cicd, rpm, Build Libraries & Interfaces, distinguished-contributor, v2.18.0

#5111 Record OpenSearch-Dashboards failed test cases in test-report.yml
  .licenserc.json
  Pipfile
  Pipfile.lock
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/data/test-results/123/integ-test/geospatial/with-security/geospatial.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/geospatial/without-security/geospatial.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/index-management/with-security/index-management.yml
  tests/tests_report_workflow/data/test-results/123/integ-test/index-management/without-security/index-management.yml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-5062ecef7f6a298367e7af1cd583a3b0.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-5441c23bc7904f2e3ae807b3892d1826.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-5ee10bd8f2a5675fa6c52bb7c8a72851.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-7e914e55a2afe10529f4c0d67dc37697.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-82ad12979cc59e52fd8c0a2cd75b6d95.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-9e349dca48a1827ab0e9010289eb11d2.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-b4c631214fc96fd9ed8f0514191f0b4e.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-b9c9797d5f184d7b631495b970b43b2d.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-bb90a3a46fc7de9e614eed6bd98f8539.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-cf442c2591be94d5872f97840cd10d49.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-d2342fd0f3566cdeb2b3231ef8141176.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-d988ed36c419a72ce03130f2446ddc2d.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-e2cf1cb9d6c739b22ca1e03d004e5da6.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-f045b381e7ec8a47ab9fa29bcc4db1a1.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-f1e74513b6beac38049c8ebad32ff853.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/cypress-report/results-f84a0b71111253725db3cfebaea5d74a.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/with-security/indexManagementDashboards.yml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-028e1c555e01111f2b313b660bb1dc5c.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-0d42e28a1647089d6453c65c8efed54e.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-2e55401e2180058e44f0b70deb136578.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-32fa4d51c2bc18ff356a85cdf9045f5a.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-4f0e3fab682ad0a756e40675fc16f861.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-5062ecef7f6a298367e7af1cd583a3b0.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-5441c23bc7904f2e3ae807b3892d1826.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-5ee10bd8f2a5675fa6c52bb7c8a72851.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-62b18f2cd4727b279bc86741d4f01df5.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-7e914e55a2afe10529f4c0d67dc37697.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-82ad12979cc59e52fd8c0a2cd75b6d95.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-9e349dca48a1827ab0e9010289eb11d2.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-b2783a0cd67c5e6087fe97eae52715c0.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-b4c631214fc96fd9ed8f0514191f0b4e.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-b9c9797d5f184d7b631495b970b43b2d.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-bb90a3a46fc7de9e614eed6bd98f8539.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-bbb86bba477caa03bb61464024115a98.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-bc3d3c2389e5806b79f005944f258a21.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-c9d5bc4a8863f3737f7b6c995fcda397.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-ca464c5fb83120ae5e2d732526d93292.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-cf442c2591be94d5872f97840cd10d49.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-d2342fd0f3566cdeb2b3231ef8141176.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-d988ed36c419a72ce03130f2446ddc2d.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-dbd7de2fb6db96c63e26c62c78f45f3e.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-df29cd8e61769095364b832907616322.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-e2cf1cb9d6c739b22ca1e03d004e5da6.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-e659a9102f817c4c1a602c6bc88be409.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-ec82be18957707c66eda5bfef39b0f52.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-f045b381e7ec8a47ab9fa29bcc4db1a1.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-f1e74513b6beac38049c8ebad32ff853.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-f456acfd2d8c13918c862b921d09342a.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/cypress-report/results-f84a0b71111253725db3cfebaea5d74a.xml
  tests/tests_report_workflow/data/test-results/123123/integ-test/indexManagementDashboards/without-security/indexManagementDashboards.yml
  tests/tests_report_workflow/test_test_report_runner.py
  tests/tests_report_workflow/test_test_report_runner_dashboards.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, jenkins, distinguished-contributor

#5114 Update OSD docker cgroup params with ops params
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-1.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh
Labels: enhancement, release, docker, Build Libraries & Interfaces, v3.0.0, distinguished-contributor, v1.3.20, v2.18.0

#5116 Use basename with extension as OSD test case class name
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/test_test_report_runner_dashboards.py
Labels: enhancement, integtest, test, cicd, ci-test-automation, Build Libraries & Interfaces, distinguished-contributor

#5119 Update library to `7.9.2`
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5123 shuffle nightly benchmark schedules
  jenkins/check-for-build.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5124 Add distribution build parameter to integ test notification workflow
  jenkins/integ-test-notification.jenkinsfile
Labels: distinguished-contributor

#5128 update 2.18 manifests with release branch
  manifests/2.18.0/opensearch-2.18.0.yml
  manifests/2.18.0/opensearch-dashboards-2.18.0.yml
Labels: distinguished-contributor, manifest-ci-check

#5129 Update tj-actions/changed-files to use sha ref
  .github/workflows/manifests.yml
Labels: distinguished-contributor

#5125 Add input manifest to build description
  jenkins/integ-test-notification.jenkinsfile
Labels: distinguished-contributor

#5132 Add retry for windows on min snapshot and distribution
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: release, cicd, windows, jenkins, Build Libraries & Interfaces, distinguished-contributor, v2.18.0

#5136 Update distribution build with 7.2.1 version libs
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: release, cicd, windows, jenkins, Build Libraries & Interfaces, distinguished-contributor, v2.18.0

#5137 Cluster setting for system templates plugin
  manifests/2.18.0/opensearch-2.18.0-test.yml
Labels: first-time-contributor

#5138 System template experimental setting
  manifests/2.18.0/opensearch-2.18.0-test.yml
Labels: first-time-contributor

#5142 Upgrade integ-test workflows to 7.3.0
  jenkins/integ-test-notification.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5144 Trigger integ-test notification workflow as post action
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5145 Fix release metrics data query
  jenkins/integ-test-notification.jenkinsfile
Labels: distinguished-contributor

#5146 change schedule of pull request benchmark nightlies
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#5147 clean up stale runs and update snapshots
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5149 Tweak 2.18/2.19 manifest and move old ones to legacy
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
  legacy-manifests/1.3.17/opensearch-1.3.17-test.yml
  legacy-manifests/1.3.17/opensearch-1.3.17.yml
  legacy-manifests/1.3.17/opensearch-dashboards-1.3.17-test.yml
  legacy-manifests/1.3.17/opensearch-dashboards-1.3.17.yml
  legacy-manifests/2.15.0/opensearch-2.15.0-test.yml
  legacy-manifests/2.15.0/opensearch-2.15.0.yml
  legacy-manifests/2.15.0/opensearch-dashboards-2.15.0-test.yml
  legacy-manifests/2.15.0/opensearch-dashboards-2.15.0.yml
  legacy-manifests/2.15.1/opensearch-2.15.1.yml
  legacy-manifests/2.16.0/opensearch-2.16.0-test.yml
  legacy-manifests/2.16.0/opensearch-2.16.0.yml
  legacy-manifests/2.16.0/opensearch-dashboards-2.16.0-test.yml
  legacy-manifests/2.16.0/opensearch-dashboards-2.16.0.yml
  legacy-manifests/2.16.1/opensearch-2.16.1-test.yml
  legacy-manifests/2.16.1/opensearch-2.16.1.yml
  manifests/2.18.0/opensearch-2.18.0-test.yml
  manifests/2.19.0/opensearch-2.19.0-test.yml
Labels: enhancement, release, Build Libraries & Interfaces, distinguished-contributor, manifests, manifest-ci-check, v2.18.0

#5141 Hard force Windows HOME Env Var in case bash.exe invoke late
  docker/ci/dockerfiles/current/build.windows2019.x64.dockerfile
Labels: enhancement, release, cicd, docker, jenkins, distinguished-contributor, v2.18.0

#5154 Remove SA dashboards from 3.0 manifest
  jenkins/integ-test-notification.jenkinsfile
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
Labels: distinguished-contributor

#5157 Remove redundant data from readme
  README.md
Labels: distinguished-contributor

#5158 Add OpenSearch-Dashboards artifact URLs to the documentation
  docs/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution.md
Labels: distinguished-contributor

#5127 Add smoke tests to the test manifest schema
  src/manifests/test_manifest.py
  tests/tests_manifests/data/opensearch-2.18.0-test.yml
  tests/tests_manifests/test_test_manifest.py
Labels: distinguished-contributor
