Repository opensearch-project/opensearch-build, pull requests merged in 2025-03, with the labels that each got.

#5359 Add single node benchmark run for 3.0.0-alpha1 version
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5346 Add smoke tests trigger in distribution build Jenkins job
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5361 Ubuntu2404 build image and test image updates
  docker/ci/dockerfiles/current/build.ubuntu2404.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/docker-builder.ubuntu2404.x64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2404.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/legacy/build.ubuntu2004.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/legacy/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
  scripts/components/OpenSearch/integtest.sh
  scripts/components/performance-analyzer/install.sh
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/control
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/copyright
  scripts/pkg/build_templates/current/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/current/opensearch/deb/debian/control
  scripts/pkg/build_templates/current/opensearch/deb/debian/copyright
  scripts/pkg/build_templates/current/opensearch/rpm/opensearch.rpm.spec
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/control
  scripts/pkg/build_templates/legacy/opensearch-dashboards/deb/debian/copyright
  scripts/pkg/build_templates/legacy/opensearch-dashboards/rpm/opensearch-dashboards.rpm.spec
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/control
  scripts/pkg/build_templates/legacy/opensearch/deb/debian/copyright
  scripts/pkg/build_templates/legacy/opensearch/rpm/opensearch.rpm.spec
  src/assemble_workflow/bundle_linux_deb.py
  tests/tests_assemble_workflow/test_bundle_linux_deb.py
Labels: release, docker, v3.0.0, distinguished-contributor

#5363 Update nightly runs run additional workloads
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5365 remove unsupported setting for nyc_taxis runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5364 Update ubuntu2004 with ubuntu2404 images now in Jenkinsfiles
  jenkins/docker/docker-build.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-re-release.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/packer/packer-build.jenkinsfile
  jenkins/release-workflows/promote-docker-ecr.jenkinsfile
  tests/jenkins/TestDockerBuild.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/packer/packer-build.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDocker.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerECRLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerLatestMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToDockerMajor.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/promotion/promote-container/promote-container-testPromoteContainerToECRLatestMajor.jenkinsfile.txt
Labels: release, docker, v3.0.0, distinguished-contributor

#5366 Disable 3.0.0-alpha1 builds and remove ppc64le from Ubuntu due to awscliv2 lacks support
  docker/ci/dockerfiles/current/build.ubuntu2404.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2404.systemd-base.x64.arm64.dockerfile
  jenkins/check-for-build.jenkinsfile
Labels: release, docker, v3.0.0, distinguished-contributor

#5368 typo and configuration fixes
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5370 Update the test spec file parameter to read from test manifest
  src/test_workflow/smoke_test/smoke_test_runner.py
  src/test_workflow/smoke_test/smoke_test_runner_opensearch.py
  tests/tests_test_workflow/test_smoke_workflow/smoke_test/test_smoke_test_runner.py
  tests/tests_test_workflow/test_smoke_workflow/smoke_test/test_smoke_test_runner_opensearch.py
Labels: distinguished-contributor

#5367 Update OS core systemd related test commands and switch to Ubuntu2404 Agents
  jenkins/docker/docker-build.jenkinsfile
  jenkins/docker/docker-copy.jenkinsfile
  jenkins/docker/docker-re-release.jenkinsfile
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/gradle/gradle-check.jenkinsfile
  jenkins/packer/packer-build.jenkinsfile
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1.yml
  scripts/components/OpenSearch/integtest.sh
  tests/jenkins/TestDockerBuild.groovy
  tests/jenkins/TestDockerScanJob.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-build.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/docker/docker-scan.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/packer/packer-build.jenkinsfile.txt
Labels: release, v3.0.0, distinguished-contributor

#5372 Set vex notice to off in docker scan
  jenkins/docker/docker-scan.jenkinsfile
Labels: release, docker, v3.0.0, distinguished-contributor

#5373 Add components to test manifest for smoke tests
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
Labels: distinguished-contributor

#5374 Update release notes workflows to support qualifier and update gradle check lib 8.2.3
  jenkins/gradle/gradle-check.jenkinsfile
  src/release_notes_workflow/release_notes.py
  src/release_notes_workflow/release_notes_component.py
  tests/data/opensearch-test-main-qualifier.yml
  tests/tests_release_notes_workflow/test_release_note_multiple_manifest.py
  tests/tests_release_notes_workflow/test_release_notes.py
  tests/tests_release_notes_workflow/test_release_notes_component.py
Labels: release, cicd, v3.0.0, distinguished-contributor

#5375 Add docker-compose file to support 3.0.0
  docker/release/dockercomposefiles/docker-compose-3.x.yml
  src/validation_workflow/docker/validation_docker.py
Labels: distinguished-contributor

#5377 Update 3.x files and support gradle 8.13 html in report workflows
  config/opensearch_dashboards-3.x.yml
  docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-3.x.sh
  docker/release/config/opensearch/opensearch-docker-entrypoint-3.x.sh
  src/report_workflow/test_report_runner.py
Labels: enhancement, integtest, test, release, cicd, v3.0.0, distinguished-contributor

#5378 Add qualifier support for validation Framework
  src/validation_workflow/rpm/validation_rpm.py
  src/validation_workflow/yum/validation_yum.py
Labels: distinguished-contributor

#5369 Add ML Commons smoke tests
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/ml-commons.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/ml-commons.yml
Labels: first-time-contributor

#5385 Update 3.0.0-alpha1 manifest back to main as a lot of changes incoming
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1.yml
  manifests/3.0.0-alpha1/opensearch-dashboards-3.0.0-alpha1.yml
Labels: release, v3.0.0, distinguished-contributor

#5387 add path.repo to KNN for 2.20 and 3.0.0-alpha1
  manifests/2.20.0/opensearch-2.20.0-test.yml
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
Labels: first-time-contributor

#5388 add node.attr.knn_cb_tier to 2.20.0 & 3.0.0-alpha1
  manifests/2.20.0/opensearch-2.20.0-test.yml
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
Labels: first-time-contributor

#5390 Update distribution builds to have revision replacing version
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: release, v3.0.0, distinguished-contributor

#5391 Reset jdk to 21 for test manifests and windows runner
  docker/ci/config/windows-setup.ps1
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
Labels: release, v3.0.0, distinguished-contributor

#5392 Add jVector to whitesource scan
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5393 Ensure scripted pipeline also pull latest docker images
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
Labels: release, jenkins, v3.0.0, distinguished-contributor

#5394 Bump lib version to fix qualifier parsing
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5395 Update integTests to match 8.3.2 libs updates
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: release, jenkins, v3.0.0, distinguished-contributor

#5396 Add opensearch-protobufs to wss config
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5397 Bump lib version to regex issue
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/TestReleaseChores.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5398 Update all ubuntu2004 to ubuntu2404 images
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/smoke-test.jenkinsfile
  jenkins/release-workflows/promote-repos.jenkinsfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
Labels: release, jenkins, v3.0.0, distinguished-contributor

#5399 Fixed dependency for ml-commons for 3.0 and 3.0-alpha-1
  manifests/2.20.0/opensearch-2.20.0.yml
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: seasoned-contributor

#5401 Update binaryspec for deb creation as debmake=4.3.2-1 and above introduced nodejs
  scripts/components/OpenSearch-Dashboards/install.sh
  src/assemble_workflow/bundle_linux_deb.py
  tests/tests_assemble_workflow/test_bundle_linux_deb.py
Labels: release, v3.0.0, deb, distinguished-contributor

#5403 add noaa and nested to nightly runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5402 Change tj-actions/changed-files usage from sha to latest version
  .github/workflows/manifests.yml
Labels: distinguished-contributor

#5404 Update manifest repopath and temp resolve osd compiling issues on windows
  manifests/2.19.1/opensearch-2.19.1-test.yml
  manifests/2.19.1/opensearch-2.19.1.yml
  manifests/2.20.0/opensearch-2.20.0-test.yml
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
  src/build_workflow/builder_from_source.py
  src/system/temporary_directory.py
  tests/tests_system/test_temporary_directory.py
Labels: release, v3.0.0, distinguished-contributor

#5405 Restore osd path as it does not correctly fix windows error
  manifests/3.0.0-alpha1/opensearch-dashboards-3.0.0-alpha1.yml
  src/build_workflow/builder_from_source.py
  src/system/temporary_directory.py
  tests/tests_system/test_temporary_directory.py
Labels: release, v3.0.0, distinguished-contributor

#5409 update snapshot repo version from 2.18 to 2.19.1
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5412 Switch repo promotion to use 8.3.4 version
  jenkins/release-workflows/promote-repos.jenkinsfile
Labels: release, v3.0.0, distinguished-contributor

#5411 Update beta1 builds and manifest entries
  jenkins/check-for-build.jenkinsfile
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1.yml
Labels: release, v3.0.0, distinguished-contributor

#5416 Update 3.0.0 from alpha1 to beta1
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5421 feat: created smoke tests for stats endpoint of opensearch-learning-to-rank-base
  manifests/2.19.0/opensearch-2.19.0-test.yml
  manifests/2.19.1/opensearch-2.19.1-test.yml
  manifests/2.20.0/opensearch-2.20.0-test.yml
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/opensearch-learning-to-rank-base.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/opensearch-learning-to-rank-base.yml
Labels: first-time-contributor

#5423 Add credentials to retrieve jenkins data
  scripts/benchmark/benchmark-pull-request.sh
Labels: distinguished-contributor

#5425 Authenticate jenkins calls for gradle check
  scripts/gradle/gradle-check.sh
Labels: distinguished-contributor

#5427 Remove silent from curl for debugging
  scripts/gradle/gradle-check.sh
Labels: distinguished-contributor

#5428 Fix gradle check malformed url error and reset debug change
  scripts/gradle/gradle-check.sh
Labels: distinguished-contributor

#5429 Add instructions about using jenkins auth
  docs/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution.md
  docs/OpenSearch-Project-Build-System-Quick-Overview.md
  docs/Releasing-the-Distribution.md
  docs/Testing-the-Distribution.md
Labels: distinguished-contributor
