Repository opensearch-project/opensearch-build, pull requests merged in 2025-06, with the labels that each got.

#5545 Bump library version for min snapshot build job
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: distinguished-contributor

#5534 Move 1.x manifests to legacy and add search-relevance to version increments
  .github/workflows/os-increment-plugin-versions.yml
  legacy-manifests/1.3.18/opensearch-1.3.18-test.yml
  legacy-manifests/1.3.18/opensearch-1.3.18.yml
  legacy-manifests/1.3.18/opensearch-dashboards-1.3.18-test.yml
  legacy-manifests/1.3.18/opensearch-dashboards-1.3.18.yml
  legacy-manifests/1.3.19/opensearch-1.3.19-test.yml
  legacy-manifests/1.3.19/opensearch-1.3.19.yml
  legacy-manifests/1.3.19/opensearch-dashboards-1.3.19-test.yml
  legacy-manifests/1.3.19/opensearch-dashboards-1.3.19.yml
  legacy-manifests/1.3.20/opensearch-1.3.20-test.yml
  legacy-manifests/1.3.20/opensearch-1.3.20.yml
  legacy-manifests/1.3.20/opensearch-dashboards-1.3.20-test.yml
  legacy-manifests/1.3.20/opensearch-dashboards-1.3.20.yml
  legacy-manifests/1.3.21/opensearch-1.3.21-test.yml
  legacy-manifests/1.3.21/opensearch-1.3.21.yml
  legacy-manifests/1.4.0/opensearch-1.4.0.yml
  legacy-manifests/1.4.0/opensearch-dashboards-1.4.0.yml
Labels: enhancement, release, distinguished-contributor, manifests

#5543 Add search relevance plugin to the distribution
  manifests/3.1.0/opensearch-3.1.0-test.yml
  manifests/3.1.0/opensearch-3.1.0.yml
Labels: repeat-contributor

#5547 Fix failing windows builds and integration test jobs
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5557 bump library version in distribution build job
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5559 add nightly benchmarks for neural search
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
Labels: distinguished-contributor

#5560 fix type in nightly benchmark configuration
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
Labels: distinguished-contributor

#5566 Update OSD distribution build to use new Docker Separation schema 1.2
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  manifests/2.19.3/opensearch-dashboards-2.19.3.yml
  manifests/3.1.0/opensearch-dashboards-3.1.0.yml
  manifests/templates/opensearch-dashboards/2.x/manifest.yml
  manifests/templates/opensearch-dashboards/3.x/manifest.yml
Labels: enhancement, cicd, jenkins, Build Libraries & Interfaces, distinguished-contributor, manifests, v3.1.0

#5571 Remove cron for 3.1.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#5576 Remove mandatory native plugin validation.
  src/validation_workflow/deb/validation_deb.py
  src/validation_workflow/docker/validation_docker.py
  src/validation_workflow/rpm/validation_rpm.py
  src/validation_workflow/tar/validation_tar.py
  src/validation_workflow/validation_args.py
  src/validation_workflow/yum/validation_yum.py
  src/validation_workflow/zip/validation_zip.py
  tests/tests_validation_workflow/test_validation_yum.py
Labels: distinguished-contributor

#5603 Upgrade library version for promotion jobs
  jenkins/release-workflows/promote-artifacts.jenkinsfile
  jenkins/release-workflows/promote-repos.jenkinsfile
Labels: distinguished-contributor

#5607 Move old jenkins to legacy and ignore tests
  jenkins/legacy/cross-cluster-replication/perf-test.jenkinsfile
  jenkins/legacy/data-prepper/release-data-prepper-all-artifacts.jenkinsfile
  jenkins/legacy/maven-sign-release.jenkinsfile
  jenkins/release-workflows/publish-to-maven.jenkinsfile
  tests/jenkins/TestCCRPerfTest.groovy
  tests/jenkins/TestDataPrepperReleaseArtifacts.groovy
  tests/jenkins/TestMavenSignReleaseJob.groovy
  tests/jenkins/TestPublishToMaven.groovy
Labels: distinguished-contributor

#5609 refresh benchmark runs for OS 3.2.0
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5611 Add size parameter in neural search benchmark and schedule to run on 2.19.1 version
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
Labels: first-time-contributor

#5616 Update jenkins branch and set autoPublish to false
  jenkins/release-workflows/publish-to-maven.jenkinsfile
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor
