Repository opensearch-project/opensearch-build, pull requests merged in 2025-01, with the labels that each got.

#5218 Add opensearch-remote-metadata-sdk
  tools/vulnerability-scan/wss-scan.config
Labels: enhancement, distinguished-contributor

#5220 Adding OpenSearch Flow to 2.19.0 Manifest
  manifests/2.19.0/opensearch-dashboards-2.19.0.yml
Labels: repeat-contributor, manifest-ci-check

#5221 Add automation app repo to triage session
  TRIAGING.md
Labels: distinguished-contributor

#5222 Added baseline run for nested workload
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#5225 Add a new Jenkins job for the smoke test
  jenkins/opensearch/smoke-test.jenkinsfile
  tests/jenkins/TestSmokeTest.groovy
  tests/jenkins/data/opensearch-2.19.0-build.yml
  tests/jenkins/data/opensearch-2.19.0-test.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/smoke-test.jenkinsfile.txt
Labels: distinguished-contributor

#5234 Allow all manifest PRs to run manifest-check workflow
  .github/workflows/manifests.yml
Labels: distinguished-contributor

#5237 Fix label creation issue by bumping the lib version
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/smoke-test.jenkinsfile.txt
Labels: distinguished-contributor

#5228 Add opensearch-remote-metadata-sdk to manifest
  manifests/2.19.0/opensearch-2.19.0.yml
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: first-time-contributor, manifest-ci-check

#5238 Update smoke test jenkinsfile to switch to non-root user for rpm & deb
  jenkins/opensearch/smoke-test.jenkinsfile
  tests/jenkins/TestSmokeTest.groovy
  tests/jenkins/data/opensearch-2.19.0-build-rpm.yml
  tests/jenkins/jenkinsjob-regression-files/opensearch/smoke-test-rpm.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/smoke-test.jenkinsfile.txt
Labels: distinguished-contributor

#5233 Query insights dashboard 2.19
  manifests/2.19.0/opensearch-dashboards-2.19.0.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
  tools/vulnerability-scan/wss-scan.config
Labels: valued-contributor, manifest-ci-check

#5245 Add opensearch-learning-to-rank-base to manifest
  manifests/2.19.0/opensearch-2.19.0.yml
Labels: first-time-contributor

#5246 Onboard opensearch-learning-to-rank-base to Test Workflow
  manifests/2.19.0/opensearch-2.19.0-test.yml
Labels: first-time-contributor

#5241 Update gcc to 12.4 to support avx512_fp16 in k-NN faiss lib and node20 on arm64
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
Labels: enhancement, release, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, v2.19.0

#5252 Ensure AL2 arm64 runs gcc10 while AL2 x64 runs gcc12
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: release, v3.0.0, distinguished-contributor

#5250 Refactor and update release wiki and template
  .github/ISSUE_TEMPLATE/release_template.md
  assests/distribution_build_os.png
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#5253 Ensure 3.0.0 use lucene9 for now
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
  manifests/3.0.0/opensearch-3.0.0.yml
Labels: release, v3.0.0, distinguished-contributor

#5258 Move texinfo specifically for binutils on al2 x64
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: release, docker, v3.0.0, distinguished-contributor

#5254 Add details to build parameters
  docs/Releasing-the-Distribution.md
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5259 Update release wiki
  docs/Releasing-the-Distribution.md
Labels: distinguished-contributor

#5260 Switch AL2 arm64 with libstdc++ 6.0.24 version of node 20 binaries
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: release, docker, v3.0.0, distinguished-contributor

#5262 Add opensearch-learning-to-rank-base to whitesource scan
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5263 Resolve plus sign causing access denied to node20 tarball
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: release, docker, v3.0.0, distinguished-contributor

#5264 Add flowFrameworkDashboards to test manifests
  manifests/2.19.0/opensearch-dashboards-2.19.0-test.yml
  manifests/3.0.0-alpha1/opensearch-dashboards-3.0.0-alpha1-test.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
Labels: seasoned-contributor

#5249 Add arm64 linux runners for python checks with Jenkins Docker Images
  .github/workflows/python-tests.yml
Labels: distinguished-contributor

#5271 Skipping DWZ as too few files for multifile optimization in DEB generation
  scripts/pkg/build_templates/current/opensearch-dashboards/deb/debian/rules
  scripts/pkg/build_templates/current/opensearch/deb/debian/rules
Labels: release, cicd, distributions, Build Libraries & Interfaces, deb, distinguished-contributor, v2.19.0

#5269 Validate distribution while building RC
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5244 Update README for smoke tests with usages and examples
  src/test_workflow/README.md
Labels: distinguished-contributor

#5272 Fail fast if input manifest is not provided
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5275 Enforce docker build with tag when RC is built
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5273 Add queryInsightsDashboards to 2.19, 3.0, 3.0.0-alpha1 dashboard test manifests
  .github/workflows/osd-release-issues.yml
  manifests/2.19.0/opensearch-dashboards-2.19.0-test.yml
  manifests/3.0.0-alpha1/opensearch-dashboards-3.0.0-alpha1-test.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
Labels: first-time-contributor, v2.19.0

#5277 Remove 2.18.1 and 2.19.0 from check-for-build
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#5278 Change manifest ref from 2.x to 2.19
  manifests/2.19.0/opensearch-2.19.0.yml
  manifests/2.19.0/opensearch-dashboards-2.19.0.yml
Labels: distinguished-contributor

#5279 Increase docker-build timeout to 150 minutes
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor

#5280 Update codecov to v5 with new token
  .github/workflows/groovy-tests.yml
  .github/workflows/python-tests.yml
Labels: enhancement, distinguished-contributor

#5282 Update validation workflow with retry twice
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/validate-artifacts/validate-artifacts.jenkinsfile.txt
Labels: release, cicd, distinguished-contributor, v2.19.0
