Repository opensearch-project/opensearch-build, pull requests merged in 2025-02, with the labels that each got.

#5289 Fix testing documentation
  docs/Testing-the-Distribution.md
Labels: distinguished-contributor

#5286 add testSnapshotFolder to path.repo
  manifests/2.19.0/opensearch-2.19.0-test.yml
Labels: first-time-contributor

#5291 Update OS release docker with libstdc++.so.6.0.30 for k-NN avx512_spr
  docker/release/dockerfiles/opensearch.al2023.dockerfile
Labels: enhancement, release, distinguished-contributor, v2.19.0

#5255 Add new plugins onboarding to smoke tests framework
  manifests/2.19.0/opensearch-2.19.0-test.yml
  src/test_workflow/smoke_test/smoke_test_runner_opensearch.py
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/index-management.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/k-NN.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/opensearch.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/security.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/sql.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/index-management.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/k-NN.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/opensearch.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/security.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/sql.yml
Labels: distinguished-contributor

#5294 Ensure libstdc++.so.6.0.30 only replace on x64 docker image
  docker/release/dockerfiles/opensearch.al2023.dockerfile
Labels: enhancement, release, distinguished-contributor, v2.19.0

#5298 update 3.0 snapshot to lucene-10 snapshots
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#5299 Add opensearch-traffic-gateway to mend scan tools config
  tools/vulnerability-scan/wss-scan.config
Labels: enhancement, distinguished-contributor

#5303 Fix central workflow hyperlink
  .github/ISSUE_TEMPLATE/release_template.md
Labels: distinguished-contributor

#5306 Ensure AL2 build image keep libstdc++.so.6.0.24 version
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
  docker/release/dockerfiles/opensearch.al2023.dockerfile
Labels: enhancement, release, cicd, docker, Build Libraries & Interfaces, v3.0.0, distinguished-contributor, v2.19.0

#5302 Fix OS min artirfact link to use alpha1 release
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#5305 Dynamically retrieve API spec yaml file from release asset
  src/test_workflow/smoke_test/smoke_test_runner_opensearch.py
  src/test_workflow/smoke_test/smoke_tests_spec/opensearch-openapi-local.yaml
  tests/tests_test_workflow/test_smoke_workflow/smoke_test/test_smoke_test_runner_opensearch.py
Labels: enhancement, distinguished-contributor

#5313 Update windows https transport to use openssl
  docker/ci/config/windows-setup.ps1
Labels: integtest, test, release, cicd, docker, windows, Build Libraries & Interfaces, distinguished-contributor, v2.19.0

#5311 Update AL2 x64 build image to have both gcc10 and gcc12
  docker/ci/dockerfiles/current/build.al2.opensearch.x64.arm64.dockerfile
Labels: integtest, test, release, cicd, docker, Build Libraries & Interfaces, distinguished-contributor, v2.19.0

#5283 Add onboarding doc for smoke tests
  ONBOARDING.md
Labels: distinguished-contributor

#5318 Release notes for 2.19
  release-notes/opensearch-release-notes-2.19.0.md
Labels: distinguished-contributor

#5321 Add local cluster logs recording to smoke tests framework
  src/test_workflow/smoke_test/smoke_test_cluster_opensearch.py
  tests/tests_test_workflow/test_smoke_workflow/smoke_test/test_smoke_test_cluster_opensearch.py
Labels: distinguished-contributor

#5326 Remove obsolete compose version specifier
  docker/release/dockercomposefiles/docker-compose-1.x.yml
  docker/release/dockercomposefiles/docker-compose-2.x.yml
  docker/release/dockercomposefiles/docker-compose-default.x.yml
Labels: first-time-contributor

#5327 Allow incremental build to respect version qualifier
  src/build_workflow/build_incremental.py
  tests/tests_build_workflow/data/opensearch-input-3.0.0-alpha1.yml
  tests/tests_build_workflow/test_build_incremental.py
Labels: enhancement, release, cicd, Build Libraries & Interfaces, v3.0.0, distinguished-contributor, manifests

#5328 Replace docker build image base from Ubuntu2004 to Ubuntu2404
  docker/ci/dockerfiles/current/docker-builder.ubuntu2404.x64.dockerfile
  docker/ci/dockerfiles/legacy/docker-builder.ubuntu2004.x64.dockerfile
Labels: enhancement, integtest, test, release, cicd, docker, jenkins, Build Libraries & Interfaces, v3.0.0, distinguished-contributor, deprecation

#5325 Add release-chores workflow
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/TestReleaseChores.groovy
Labels: distinguished-contributor

#5331 Fix security review link for release issue
  .github/ISSUE_TEMPLATE/release_template.md
Labels: distinguished-contributor

#5334 Update distribution build to use libs 8.2.1 and fix incremental builds with qualifier
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: enhancement, release, v3.0.0, distinguished-contributor

#5338 Remove cron for 2.19.1
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#5276 Update nodeJS version to 20.18.3 in support of 3.0.0
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
Labels: integtest, test, release, cicd, docker, Build Libraries & Interfaces, v3.0.0, distinguished-contributor, nodejs upgrade

#5339 Resolve fpm installation issues on docker ci images
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
Labels: docker, distinguished-contributor

#5337 Add 3.0.0-beta1 manifests for testing on node20/22 upgrade in OSD core
  jenkins/check-for-build.jenkinsfile
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1.yml
  manifests/3.0.0-beta1/opensearch-dashboards-3.0.0-beta1-test.yml
  manifests/3.0.0-beta1/opensearch-dashboards-3.0.0-beta1.yml
Labels: release, v3.0.0, distinguished-contributor

#5340 fix the min artifact url for 3.0.0-alpha1
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#5345 Support new OS core systemd and integTests in 3.0.0 and manifest updates
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2004.systemd-base.x64.arm64.ppc64le.dockerfile
  jenkins/check-for-build.jenkinsfile
  manifests/2.19.1/opensearch-2.19.1-test.yml
  manifests/2.20.0/opensearch-2.20.0-test.yml
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1-test.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1-test.yml
  manifests/3.0.0-beta1/opensearch-dashboards-3.0.0-beta1.yml
  scripts/components/OpenSearch/install.sh
  scripts/components/OpenSearch/integtest.sh
Labels: enhancement, integtest, test, release, cicd, rpm, Build Libraries & Interfaces, v3.0.0, deb, distinguished-contributor

#5347 Stepped dblock@ down to emeritus.
  MAINTAINERS.md
Labels: distinguished-contributor

#5348 Add geospatial as sql dependencies in 3.x
  manifests/3.0.0-alpha1/opensearch-3.0.0-alpha1.yml
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1.yml
Labels: release, v3.0.0, distinguished-contributor

#5344 Refactor release issue creation workflows
  .github/workflows/create-release-issues.yml
  .github/workflows/os-release-issues.yml
  .github/workflows/osd-release-issues.yml
Labels: distinguished-contributor

#5349 Removed dblock@ from CODEOWNERS.
  .github/CODEOWNERS
Labels: distinguished-contributor

#5350 Resolve issues where UPDATE_GITHUB_ISSUE is not supported in check-for-build
  jenkins/check-for-build.jenkinsfile
Labels: release, v3.0.0, distinguished-contributor

#5352 Add remote-vector-index-builder repo to vuln scans wss-scan.config
  tools/vulnerability-scan/wss-scan.config
Labels: first-time-contributor

#5351 Update mainline benchmark runs to use the correct version
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5353 Update version increment workflow to remove main/3.x updates
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: release, v3.0.0, distinguished-contributor

#5358 Remove ganttcharts in 3.0.0 and update deprecation notice
  manifests/3.0.0-alpha1/opensearch-dashboards-3.0.0-alpha1-test.yml
  manifests/3.0.0-alpha1/opensearch-dashboards-3.0.0-alpha1.yml
  manifests/3.0.0-beta1/opensearch-dashboards-3.0.0-beta1-test.yml
  manifests/3.0.0-beta1/opensearch-dashboards-3.0.0-beta1.yml
  release-notes/opensearch-release-notes-2.19.0.md
Labels: release, v3.0.0, distinguished-contributor
