Repository opensearch-project/opensearch-build, pull requests merged in 2025-04, with the labels that each got.

#5430 Enables vector derived source 3.0 benchmarks
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: seasoned-contributor

#5418 Update the report workflow to accommodate reporting for smoke test results
  src/report_workflow/test_report_runner.py
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/GET___plugins__ism_explain_ism-index-000001/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/GET___plugins__ism_explain_ism-index-000001/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/GET___plugins__ism_explain_ism-index-000001/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/GET___plugins__ism_policies/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/GET___plugins__ism_policies/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/GET___plugins__ism_policies/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST___plugins__ism_add_ism-index-000001/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST___plugins__ism_add_ism-index-000001/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST___plugins__ism_add_ism-index-000001/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST___plugins__ism_remove_ism-index-000001/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST___plugins__ism_remove_ism-index-000001/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST___plugins__ism_remove_ism-index-000001/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST__rollover-alias__rollover/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST__rollover-alias__rollover/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/POST__rollover-alias__rollover/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/PUT___plugins__ism_policies_policy_1/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/PUT___plugins__ism_policies_policy_1/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/PUT___plugins__ism_policies_policy_1/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/PUT__ism-index-000001/index-management.yml
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/PUT__ism-index-000001/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/index-management/PUT__ism-index-000001/stdout.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/local-cluster-logs/stderr.txt
  tests/tests_report_workflow/data/test-results/12345/smoke-test/local-cluster-logs/stdout.txt
  tests/tests_report_workflow/data/test_manifest.yml
  tests/tests_report_workflow/test_test_report_runner.py
Labels: distinguished-contributor

#5431 Update sign workflow to support email parameter for PGP signing
  src/run_sign.py
  src/sign_workflow/sign_args.py
  src/sign_workflow/sign_artifacts.py
  src/sign_workflow/signer.py
  src/sign_workflow/signer_pgp.py
  src/sign_workflow/signers.py
  tests/tests_sign_workflow/test_sign_args.py
  tests/tests_sign_workflow/test_sign_artifacts.py
  tests/tests_sign_workflow/test_signer_pgp.py
  tests/tests_sign_workflow/test_signers.py
Labels: distinguished-contributor

#5433 Push 3.0.0-beta1 changes to 3.0.0 GA input manifests
  legacy-manifests/2.17.0/opensearch-2.17.0-test.yml
  legacy-manifests/2.17.0/opensearch-2.17.0.yml
  legacy-manifests/2.17.0/opensearch-dashboards-2.17.0-test.yml
  legacy-manifests/2.17.0/opensearch-dashboards-2.17.0.yml
  legacy-manifests/2.17.1/opensearch-2.17.1-test.yml
  legacy-manifests/2.17.1/opensearch-2.17.1.yml
  legacy-manifests/2.17.1/opensearch-dashboards-2.17.1-test.yml
  legacy-manifests/2.17.1/opensearch-dashboards-2.17.1.yml
  legacy-manifests/2.17.2/opensearch-2.17.2-test.yml
  legacy-manifests/2.17.2/opensearch-2.17.2.yml
  manifests/3.0.0/PLEASE_UPDATE_3.0.0-alpha1_MANIFESTS_THANKS.txt
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
Labels: release, v3.0.0, distinguished-contributor, manifests

#5434 Move 2.17 manifests back to manifests dir for metrics
  manifests/2.17.0/opensearch-2.17.0-test.yml
  manifests/2.17.0/opensearch-2.17.0.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0-test.yml
  manifests/2.17.0/opensearch-dashboards-2.17.0.yml
  manifests/2.17.1/opensearch-2.17.1-test.yml
  manifests/2.17.1/opensearch-2.17.1.yml
  manifests/2.17.1/opensearch-dashboards-2.17.1-test.yml
  manifests/2.17.1/opensearch-dashboards-2.17.1.yml
  manifests/2.17.2/opensearch-2.17.2-test.yml
  manifests/2.17.2/opensearch-2.17.2.yml
Labels: enhancement, distinguished-contributor

#5437 Move 2.17.x to legacy manifests folder
  legacy-manifests/2.17.0/opensearch-2.17.0-test.yml
  legacy-manifests/2.17.0/opensearch-2.17.0.yml
  legacy-manifests/2.17.0/opensearch-dashboards-2.17.0-test.yml
  legacy-manifests/2.17.0/opensearch-dashboards-2.17.0.yml
  legacy-manifests/2.17.1/opensearch-2.17.1-test.yml
  legacy-manifests/2.17.1/opensearch-2.17.1.yml
  legacy-manifests/2.17.1/opensearch-dashboards-2.17.1-test.yml
  legacy-manifests/2.17.1/opensearch-dashboards-2.17.1.yml
  legacy-manifests/2.17.2/opensearch-2.17.2-test.yml
  legacy-manifests/2.17.2/opensearch-2.17.2.yml
Labels: distinguished-contributor

#5436 Update release chore workflow with additional chores
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/TestReleaseChores.groovy
Labels: distinguished-contributor

#5440 Fix version with qualifier for updating manifests with tags
  jenkins/release-workflows/release-manifest-commit-lock.jenkinsfile
Labels: distinguished-contributor

#5441 Add release new key imports for validation workflow
  src/validation_workflow/rpm/validation_rpm.py
  src/validation_workflow/yum/validation_yum.py
Labels: release, signing, v3.0.0, distinguished-contributor

#5447 Fix release chore bugs for rc comment and release issue queries
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/TestReleaseChores.groovy
Labels: distinguished-contributor

#5448 Fix default value in the release issue method
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/TestReleaseChores.groovy
Labels: distinguished-contributor

#5449 Add description to the release chore for quick view
  README.md
  TRIAGING.md
  jenkins/release-workflows/release-chores.jenkinsfile
Labels: distinguished-contributor

#5439 Add email selection in Maven release parameter based on major version
  README.md
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  jenkins/release-workflows/promote-artifacts.jenkinsfile
  jenkins/release-workflows/promote-repos.jenkinsfile
  tests/jenkins/TestMavenSignReleaseJob.groovy
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: distinguished-contributor

#5452 Bumping lib 9.0.1 on build/integTest/benchmark on Jenkins
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  jenkins/release-workflows/promote-artifacts.jenkinsfile
  jenkins/release-workflows/promote-repos.jenkinsfile
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/TestMavenSignReleaseJob.groovy
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
Labels: release, jenkins, v3.0.0, distinguished-contributor

#5453 Fix nmslib engine benchmark runs
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5455 bump benchmark-pull-request job to use 9.0.2 lib
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
Labels: distinguished-contributor

#5456 Add release@opensearch.org keyid to rpm validation
  src/validation_workflow/rpm/validation_rpm.py
  tests/tests_validation_workflow/test_validation_rpm.py
Labels: enhancement, release, rpm, signing, Build Libraries & Interfaces, v3.0.0, distinguished-contributor

#5457 Use component commitID to create new branch with build manifests on release-branch-creation
  jenkins/release-workflows/release-branch.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-branch-buildmanifest.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-branch-inputmanifest.jenkinsfile.txt
Labels: enhancement, release, cicd, jenkins, v3.0.0, distinguished-contributor, manifests

#5460 add nightly benchmark run for concurrent search enabled in auto mode
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5462 Update OS in 3.0.0-beta1 to onboard limit stack walking to frames PR
  manifests/3.0.0-beta1/opensearch-3.0.0-beta1.yml
Labels: release, v3.0.0, distinguished-contributor, manifests

#5463 Update docker image used for maven publish
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor

#5465 Change docker image with python 3.9 and JDK 11 for maven publish
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor

#5426 Support JDK-24 builds on Jenkins
  docker/ci/config/jdk-setup.sh
  docker/ci/config/legacy/windows-servercore-setup.ps1
Labels: seasoned-contributor

#5466 Update nightly benchmarks to track 3.0.0
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5467 Update jdk based on OS version for increment PRs and fix windows python
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
  .github/workflows/python-tests.yml
Labels: enhancement, cicd, distinguished-contributor

#5468 Add missing build repo checkout to detect jdk version
  .github/workflows/os-increment-plugin-versions.yml
  README.md
Labels: enhancement, release, v3.0.0, distinguished-contributor

#5471 Remove main check to ensure 3.1.0 changes wont slip into 3.0 for now
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: release, v3.0.0, distinguished-contributor

#5476 Update 3.0.0 to use 3.0 branch in manifest
  jenkins/check-for-build.jenkinsfile
  manifests/3.0.0/opensearch-3.0.0.yml
  manifests/3.0.0/opensearch-dashboards-3.0.0.yml
Labels: release, v3.0.0, distinguished-contributor

#5479 Make sure deb is correctly adding env file in OpenSearch
  scripts/components/OpenSearch/install.sh
Labels: release, v3.0.0, deb, distinguished-contributor

#5477 Bump pull request action version to v6
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#5486 Remove cron job for building 2.19.2
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#5485 Add consolidated release notes for 2.19.2
  release-notes/opensearch-release-notes-2.19.2.md
Labels: distinguished-contributor

#5491 Move 2.20.0 to legacy to prevent release issues being opened anymore
  jenkins/check-for-build.jenkinsfile
  legacy-manifests/2.20.0/opensearch-2.20.0-test.yml
  legacy-manifests/2.20.0/opensearch-2.20.0.yml
  legacy-manifests/2.20.0/opensearch-dashboards-2.20.0-test.yml
  legacy-manifests/2.20.0/opensearch-dashboards-2.20.0.yml
Labels: release, distinguished-contributor, manifests, manifest-ci-check

#5492 Update release notes for 2.19.2
  release-notes/opensearch-release-notes-2.19.2.md
Labels: distinguished-contributor

#5493 Add OS and OSD build number into validation parameter
  jenkins/release-workflows/release-promotion.jenkinsfile
  tests/jenkins/TestOpenSearchReleasePromotionTest.groovy
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-promotion.jenkinsfile.txt
Labels: distinguished-contributor

#5494 Add exit criteria chores
  jenkins/release-workflows/release-chores.jenkinsfile
  tests/jenkins/TestReleaseChores.groovy
Labels: distinguished-contributor
