Repository opensearch-project/opensearch-build, pull requests merged in 2025-08, with the labels that each got.

#5669 Added jenkins job for running release notes generation using LLM workflow.
  jenkins/release-workflows/release-notes-generate.jenkinsfile
  src/release_notes_workflow/release_notes_check_args.py
  tests/jenkins/TestReleaseNotesGenerate.groovy
  tests/jenkins/jenkinsjob-regression-files/release-workflows/release-notes-generate.jenkinsfile.txt
Labels: distinguished-contributor

#5673 Remove 12.13.0 cypress due to installation error and not being used
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2404.systemd-base.x64.arm64.dockerfile
Labels: enhancement, integtest, test, release, docker, distinguished-contributor, v3.2.0

#5674 Remove auto-build for 3.2.0
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#5676 Update CI group to 14 for OSD
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5677 Update missing plugin install permission on OS systemd test
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.ubuntu2404.systemd-base.x64.arm64.dockerfile
  jenkins/validate-artifacts/validate-artifacts.jenkinsfile
Labels: enhancement, release, distinguished-contributor, v3.2.0

#5678 Revert "Update CI group to 14 for OSD"
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  manifests/3.2.0/opensearch-dashboards-3.2.0-test.yml
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
Labels: distinguished-contributor

#5680 Add missing secret_github_bot secret env vars
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: enhancement, release, distinguished-contributor, v3.2.0

#5705 add cron in endpoint benchmark job
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  tests/jenkins/TestRunBenchmarkTestEndpoint.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
Labels: distinguished-contributor

#5707 refresh nightly benchmarks for OS-3.3.0
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5710 Add OSS endpoint benchmark run
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5711 Add missing RC parameter in smoke test trigger
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor
