Repository opensearch-project/opensearch-build, pull requests merged in 2025-05, with the labels that each got.

#5497 Attempt to resolve windows runner stuck on heavy-weight integTests
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  src/test_workflow/integ_test/distribution_zip.py
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
Labels: enhancement, integtest, test, release, cicd, v3.0.0, distinguished-contributor

#5499 Revert #5497 while keep the time increase in OS integTests
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  src/test_workflow/integ_test/distribution_zip.py
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/tests_test_workflow/test_integ_workflow/integ_test/test_distribution_zip.py
Labels: enhancement, release, v3.0.0, distinguished-contributor

#5500 Switch k-NN repo path to logs dir to avoid pathing issues on non-windows
  manifests/2.19.2/opensearch-2.19.2-test.yml
  manifests/3.0.0/opensearch-3.0.0-test.yml
  manifests/3.1.0/opensearch-3.1.0-test.yml
Labels: enhancement, integtest, test, release, cicd, v3.0.0, distinguished-contributor

#5505 Temp resolve path.repo not found issues on k-NN
  scripts/components/k-NN/integtest.sh
Labels: enhancement, release, v3.0.0, distinguished-contributor

#5510 Bump gh cli version
  docker/ci/config/gh-setup.sh
Labels: distinguished-contributor

#5511 Update vector workloads to enable node stats
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: seasoned-contributor

#5509 Upload smoke tests results to S3 and generate test-reports
  jenkins/opensearch/smoke-test.jenkinsfile
  tests/jenkins/TestSmokeTest.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/smoke-test-rpm.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/smoke-test.jenkinsfile.txt
Labels: distinguished-contributor

#5513 Update manifest dependencies for Flow Framework and k-NN
  manifests/2.19.3/opensearch-2.19.3.yml
  manifests/3.1.0/opensearch-3.1.0.yml
Labels: first-time-contributor

#5515 Refresh nightly benchmarks for 3.1.0
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5516 add osd plugins version bump back to main branch
  .github/workflows/osd-increment-plugin-versions.yml
Labels: first-time-contributor

#5517 enable node stats for vectorsearch nightlies
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5527 Upgrade library versions and fix groovy tests
  .github/workflows/groovy-tests.yml
  jenkins/docker/docker-scan.jenkinsfile
  jenkins/opensearch-dashboards/integ-test.jenkinsfile
  jenkins/opensearch-maven-release/maven-sign-release.jenkinsfile
  jenkins/opensearch-maven-release/publish-to-maven.jenkinsfile
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  jenkins/opensearch/integ-test.jenkinsfile
  jenkins/opensearch/publish-min-snapshots.jenkinsfile
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/TestDockerScanJob.groovy
  tests/jenkins/TestMavenSignReleaseJob.groovy
  tests/jenkins/TestOpenSearchDashboardsIntegTest.groovy
  tests/jenkins/TestOpenSearchIntegTest.groovy
  tests/jenkins/TestPublishMinSnapshots.groovy
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/docker/docker-scan.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/maven-sign-release/maven-sign-release.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-dashboards/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test-without-validation.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/integ-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/publish-min-snapshots.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5530 Add new repos to whitesource scaning tool
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5531 Refresh nightly benchmarks to use 10.2.1 lucene snapshots
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5521 Add smoke test for geospatial plugin
  manifests/2.19.3/opensearch-2.19.3-test.yml
  manifests/3.1.0/opensearch-3.1.0-test.yml
  src/test_workflow/smoke_test/smoke_tests_spec/2.x/geospatial.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/geospatial.yml
Labels: first-time-contributor

#5528 Add Smoke test for neural search plugin
  manifests/3.1.0/opensearch-3.1.0-test.yml
  src/test_workflow/smoke_test/smoke_tests_spec/default/neural-search.yml
Labels: first-time-contributor

#5532 Refactored benchmark-test job into two separate jobs
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5539 Update lib version for distribution build job
  jenkins/opensearch-dashboards/distribution-build.jenkinsfile
  jenkins/opensearch/distribution-build.jenkinsfile
Labels: distinguished-contributor
