Repository opensearch-project/opensearch-build, pull requests merged in 2025-09, with the labels that each got.

#5719 Add sql benchmark for OS-3.2.0
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5722 Add managed service benchmark for 3.1 version
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
Labels: distinguished-contributor

#5723 Using node20 to override node24 on github runner
  .github/workflows/get-ci-image-tag.yml
Labels: enhancement, distinguished-contributor

#5724 fix user tags in nightly endpoint benchmark runs
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
Labels: distinguished-contributor

#5726 Add UBI to the version increment and remove old config
  .github/workflows/os-increment-plugin-versions.yml
  .github/workflows/osd-increment-plugin-versions.yml
Labels: distinguished-contributor

#5734 revert build-lib version update change on benchmark jobs
  jenkins/opensearch/benchmark-compare.jenkinsfile
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  jenkins/opensearch/benchmark-test-vectorsearch.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/TestBenchmarkPullRequest.groovy
  tests/jenkins/TestCompareBenchmarks.groovy
  tests/jenkins/TestRunBenchmarkTestEndpoint.groovy
  tests/jenkins/TestRunBenchmarkTestScriptDistributionUrl.groovy
  tests/jenkins/TestRunNonSecBenchmarkTestScript.groovy
  tests/jenkins/TestRunSecureBenchmarkTestScript.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-compare.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5736 refresh snapshot to lucene version 10.3.0 for big5
  jenkins/opensearch/benchmark-pull-request.jenkinsfile
  jenkins/opensearch/benchmark-test.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-generic.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-pull-request-user.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-distribution-url.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/secure-benchmark-test.jenkinsfile.txt
Labels: distinguished-contributor

#5741 Add css enabled nightiy runs for aos domains
  jenkins/opensearch/benchmark-test-endpoint.jenkinsfile
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-insecure.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure-sigv4.jenkinsfile.txt
  tests/jenkins/jenkinsjob-regression-files/opensearch/benchmark-test-endpoint-secure.jenkinsfile.txt
Labels: distinguished-contributor

#5743 Fix the URL syntax when the target is a file
  src/assemble_workflow/bundle_opensearch.py
  tests/tests_assemble_workflow/test_bundle_opensearch.py
  tests/tests_assemble_workflow/test_bundle_opensearch_windows_uri.py
Labels: first-time-contributor

#5746 Add release chore to create and compile release notes
  jenkins/release-workflows/release-chores.jenkinsfile
  jenkins/release-workflows/release-notes-generate.jenkinsfile
  tests/jenkins/TestReleaseChores.groovy
Labels: distinguished-contributor
