Repository opensearch-project/opensearch-build, pull requests merged in 2025-07, with the labels that each got.

#5618 Update maven publishing workflow to accommodate nexus EOL
  jenkins/release-workflows/publish-to-maven.jenkinsfile
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor

#5628 Resolve codecov error upload coverage issues
  .codecov.yml
  .github/workflows/python-tests.yml
  Pipfile
  Pipfile.lock
Labels: enhancement, Build Libraries & Interfaces, distinguished-contributor, github_actions

#5633 Run gradle check job every two hours
  jenkins/gradle/gradle-check.jenkinsfile
Labels: distinguished-contributor

#5636 Stop build cron for 2.19.3
  jenkins/check-for-build.jenkinsfile
Labels: distinguished-contributor

#5635 Add opensearch-prometheus-exporter to wss config
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5644 Update test manifest to use ubuntu systemd image
  manifests/2.19.3/opensearch-2.19.3-test.yml
  manifests/2.19.3/opensearch-dashboards-2.19.3-test.yml
  manifests/3.2.0/opensearch-3.2.0-test.yml
Labels: enhancement, release, distinguished-contributor, v2.19.3

#5648 Add dashboards-investigation to wss
  tools/vulnerability-scan/wss-scan.config
Labels: distinguished-contributor

#5649 Fix maven auto-publish for distribution
  jenkins/release-workflows/publish-to-maven.jenkinsfile
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor

#5613 Upgrade Jenkins and plugins version
  .github/workflows/groovy-tests.yml
  DEVELOPER_GUIDE.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: distinguished-contributor

#5653 Change lib for Gradle issue Creation job
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
Labels: distinguished-contributor

#5656 Change lib version to 6.9.2 for gradle issue creation job
  jenkins/gradle/gradle-check-flaky-test-issue-creation.jenkinsfile
Labels: distinguished-contributor

#5658 Refator code to get build issue in first step
  .github/workflows/create-release-issues.yml
Labels: distinguished-contributor

#5660 Update curl to support sigv4 on almalinux8 images
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
Labels: enhancement, docker, distinguished-contributor

#5662 Relink ca-certs as curl binary is pointing to ubuntu version
  docker/ci/dockerfiles/current/build.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/build.almalinux8.opensearch.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.opensearch-dashboards.x64.arm64.ppc64le.dockerfile
  docker/ci/dockerfiles/current/test.almalinux8.systemd-base.x64.arm64.ppc64le.dockerfile
Labels: enhancement, docker, distinguished-contributor

#5666 Bump jenkin lib version to accommodate maven publishing fixes
  jenkins/release-workflows/publish-to-maven.jenkinsfile
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jenkinsjob-regression-files/opensearch-maven-release/publish-to-maven.jenkinsfile.txt
Labels: distinguished-contributor
